.m_activationchannel_agg_variables: &m_activationchannel_agg_variables
  JOB_NAME: "m-activationchannel-agg"
  M_ACTIVATIONCHANNEL_AGG_DIR: "si-jobs/monthly-activationchannel-agg"
  ARTIFACTS_DIR: "si-jobs/monthly-activationchannel-agg/artifacts"
  TERRAFORM_DIR: "si-jobs/monthly-activationchannel-agg/terraform"
  SCRIPTS_DIR: "si-jobs/monthly-activationchannel-agg/scripts"
  S3_ARTIFACTS_DIR: "si-jobs/monthly-activationchannel-agg"

m_activationchannel_agg_build:
  extends: .build
  variables:
    DDL_DIR: "$M_ACTIVATIONCHANNEL_AGG_DIR/ddl"
    HQL_DIR: "$M_ACTIVATIONCHANNEL_AGG_DIR/hql"
    <<: *m_activationchannel_agg_variables

#STG
m_activationchannel_agg_plan_stg:
  extends: .plan_stg
  variables:
    <<: *m_activationchannel_agg_variables
  dependencies:
    - m_activationchannel_agg_build

m_activationchannel_agg_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *m_activationchannel_agg_variables
  dependencies:
    - m_activationchannel_agg_build
    - m_activationchannel_agg_plan_stg

m_activationchannel_agg_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *m_activationchannel_agg_variables
  dependencies:
    - m_activationchannel_agg_build

#PROD
m_activationchannel_agg_plan_prod:
  extends: .plan_prod
  variables:
    <<: *m_activationchannel_agg_variables
  dependencies:
    - m_activationchannel_agg_build

m_activationchannel_agg_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *m_activationchannel_agg_variables
  dependencies:
    - m_activationchannel_agg_build
    - m_activationchannel_agg_plan_prod

m_activationchannel_agg_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *m_activationchannel_agg_variables
  dependencies:
    - m_activationchannel_agg_build
