.portals_ps_metric_agg_variables: &portals_ps_metric_agg_variables
  JOB_NAME: "parameterized-portals-ps-metric-agg"
  PORTALS_PS_METRIC_AGG_DIR: "parameterized/portals-ps-metric-agg"
  ARTIFACTS_DIR: "parameterized/portals-ps-metric-agg/artifacts"
  TERRAFORM_DIR: "parameterized/portals-ps-metric-agg/terraform"
  SCRIPTS_DIR: "parameterized/portals-ps-metric-agg/scripts"
  S3_ARTIFACTS_DIR: "parameterized/portals-ps-metric-agg"

portals_ps_metric_agg_build:
  extends: .build
  variables:
    DDL_DIR: "$PORTALS_PS_METRIC_AGG_DIR/ddl"
    HQL_DIR: "$PORTALS_PS_METRIC_AGG_DIR/hql"
    <<: *portals_ps_metric_agg_variables

#STG
portals_ps_metric_agg_plan_stg:
  extends: .plan_stg
  variables:
    <<: *portals_ps_metric_agg_variables
  dependencies:
    - portals_ps_metric_agg_build

portals_ps_metric_agg_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *portals_ps_metric_agg_variables
  dependencies:
    - portals_ps_metric_agg_build
    - portals_ps_metric_agg_plan_stg

portals_ps_metric_agg_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *portals_ps_metric_agg_variables
  dependencies:
    - portals_ps_metric_agg_build
#PROD
portals_ps_metric_agg_plan_prod:
  extends: .plan_prod
  variables:
    <<: *portals_ps_metric_agg_variables
  dependencies:
    - portals_ps_metric_agg_build

portals_ps_metric_agg_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *portals_ps_metric_agg_variables
  dependencies:
    - portals_ps_metric_agg_build
    - portals_ps_metric_agg_plan_prod

portals_ps_metric_agg_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *portals_ps_metric_agg_variables
  dependencies:
    - portals_ps_metric_agg_build
