# asp counts smb daily
dependencies=00_parameter_init
type=command
command=whoami

command.1=/bin/bash -c 'export START_DATE_TZ="${START_DATE_TZ}"; echo $START_DATE_TZ; export END_DATE_TZ="${END_DATE_TZ}"; echo $END_DATE_TZ;  hive -f ../src/01d_d_prod_asp_v_sbnet_events__devices__prod_asp_counts_daily.hql'
command.2=/bin/bash -c 'export START_DATE_TZ="${START_DATE_TZ}"; echo $START_DATE_TZ; export END_DATE_TZ="${END_DATE_TZ}"; echo $END_DATE_TZ;  hive -f ../src/01d_h_prod_asp_v_sbnet_events__households__prod_asp_counts_daily.hql'
command.3=/bin/bash -c 'export START_DATE_TZ="${START_DATE_TZ}"; echo $START_DATE_TZ; export END_DATE_TZ="${END_DATE_TZ}"; echo $END_DATE_TZ;  hive -f ../src/01d_i_prod_asp_v_sbnet_events__instances__prod_asp_counts_daily.hql'
command.4=/bin/bash -c 'export START_DATE_TZ="${START_DATE_TZ}"; echo $START_DATE_TZ; export END_DATE_TZ="${END_DATE_TZ}"; echo $END_DATE_TZ;  hive -f ../src/01d_v_prod_asp_v_sbnet_events__visits__prod_asp_counts_daily.hql'
