# asp counts consumer fiscal monthly
dependencies=00_parameter_init
type=command
command=whoami

command.1=/bin/bash -c 'export START_DATE="${START_DATE}"; echo $START_DATE; export END_DATE="${END_DATE}"; echo $END_DATE;  hive -f ../src/01fm_d_prod_asp_v_net_events__devices__prod_asp_counts_fiscal_monthly.hql'
command.2=/bin/bash -c 'export START_DATE="${START_DATE}"; echo $START_DATE; export END_DATE="${END_DATE}"; echo $END_DATE;  hive -f .../src/01fm_h_prod_asp_v_net_events__households__prod_asp_counts_fiscal_monthly.hql'
command.3=/bin/bash -c 'export START_DATE="${START_DATE}"; echo $START_DATE; export END_DATE="${END_DATE}"; echo $END_DATE;  hive -f ../src/01fm_i_prod_asp_v_net_events__instances__prod_asp_counts_fiscal_monthly.hql'
command.4=/bin/bash -c 'export START_DATE="${START_DATE}"; echo $START_DATE; export END_DATE="${END_DATE}"; echo $END_DATE;  hive -f ../src/01fm_v_prod_asp_v_net_events__visits__prod_asp_counts_fiscal_monthly.hql'
command.5=/bin/bash -c 'export START_DATE="${START_DATE}"; echo $START_DATE; export END_DATE="${END_DATE}"; echo $END_DATE;  hive -f
../src/01fm_x_prod_asp_v_net_events__manual__prod_asp_counts_fiscal_monthly.hql'
