.d_portals_m2dot0_set_agg_variables: &d_portals_m2dot0_set_agg_variables
  JOB_NAME: "d-portals-m2dot0-set-agg"
  DAILY_PORTALS_M2DOT0_SET_AGG_DIR: "parameterized/daily-portals-m2dot0-set-agg"
  ARTIFACTS_DIR: "parameterized/daily-portals-m2dot0-set-agg/artifacts"
  TERRAFORM_DIR: "parameterized/daily-portals-m2dot0-set-agg/terraform"
  SCRIPTS_DIR: "parameterized/daily-portals-m2dot0-set-agg/scripts"
  S3_ARTIFACTS_DIR: "parameterized/daily-portals-m2dot0-set-agg"

d_portals_m2dot0_set_agg_build:
  extends: .build
  variables:
    DDL_DIR: "$DAILY_PORTALS_M2DOT0_SET_AGG_DIR/ddl"
    HQL_DIR: "$DAILY_PORTALS_M2DOT0_SET_AGG_DIR/hql"
    <<: *d_portals_m2dot0_set_agg_variables

#STG
d_portals_m2dot0_set_agg_plan_stg:
  extends: .plan_stg
  variables:
    <<: *d_portals_m2dot0_set_agg_variables
  dependencies:
    - d_portals_m2dot0_set_agg_build

d_portals_m2dot0_set_agg_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *d_portals_m2dot0_set_agg_variables
  dependencies:
    - d_portals_m2dot0_set_agg_build
    - d_portals_m2dot0_set_agg_plan_stg

d_portals_m2dot0_set_agg_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *d_portals_m2dot0_set_agg_variables
  dependencies:
    - d_portals_m2dot0_set_agg_build


#PROD
d_portals_m2dot0_set_agg_plan_prod:
  extends: .plan_prod
  variables:
    <<: *d_portals_m2dot0_set_agg_variables
  dependencies:
    - d_portals_m2dot0_set_agg_build

d_portals_m2dot0_set_agg_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *d_portals_m2dot0_set_agg_variables
  dependencies:
    - d_portals_m2dot0_set_agg_build
    - d_portals_m2dot0_set_agg_plan_prod

d_portals_m2dot0_set_agg_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *d_portals_m2dot0_set_agg_variables
  dependencies:
    - d_portals_m2dot0_set_agg_build
