.portals_ytd_agg_variables: &portals_ytd_agg_variables
  JOB_NAME: "portals-ytd-agg"
  portals_ytd_agg_DIR: "parameterized/portals-ytd-agg"
  ARTIFACTS_DIR: "parameterized/portals-ytd-agg/artifacts"
  TERRAFORM_DIR: "parameterized/portals-ytd-agg/terraform"
  SCRIPTS_DIR: "parameterized/portals-ytd-agg/scripts"
  S3_ARTIFACTS_DIR: "parameterized/portals-ytd-agg"

portals_ytd_agg_build:
  extends: .build
  variables:
    DDL_DIR: "$portals_ytd_agg_DIR/ddl"
    HQL_DIR: "$portals_ytd_agg_DIR/hql"
    <<: *portals_ytd_agg_variables

#STG
portals_ytd_agg_plan_stg:
  extends: .plan_stg
  variables:
    <<: *portals_ytd_agg_variables
  dependencies:
    - portals_ytd_agg_build

portals_ytd_agg_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *portals_ytd_agg_variables
  dependencies:
    - portals_ytd_agg_build
    - portals_ytd_agg_plan_stg

portals_ytd_agg_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *portals_ytd_agg_variables
  dependencies:
    - portals_ytd_agg_build

#PROD
portals_ytd_agg_plan_prod:
  extends: .plan_prod
  variables:
    <<: *portals_ytd_agg_variables
  dependencies:
    - portals_ytd_agg_build

portals_ytd_agg_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *portals_ytd_agg_variables
  dependencies:
    - portals_ytd_agg_build
    - portals_ytd_agg_plan_prod

portals_ytd_agg_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *portals_ytd_agg_variables
  dependencies:
    - portals_ytd_agg_build
