#  Azkaban job
type=Groovy
dependencies=01_param_init_rfm

groovy.command.1=println 'This job allows the parameter to flow through that decides whether or not to continue reprocessing.  When it is time to stop the metric agg reprocess, the set agg db init kicks off so that all the tables are there, with the current run date, and the view is refreshed.'
groovy.command.2=if ( ${ContinueReprocess} == 0 ) { azkaban.execute("asp_extract_parameterized_portals_set_aggs", "init_00_database") }
