CREATE EXTERNAL TABLE IF NOT EXISTS ${db_name}.atom_fiber_nodes (
  bi_foreign_key_dim_fiber_node_history_sk STRING,
  bi_foreign_key_dim_date_sk STRING,
  bi_foreign_key_dim_employee_history_sk STRING,
  bi_foreign_key_dim_source_system_code_sk STRING,
  key_market_area_description STRING,
  node_health_score_value DOUBLE,
  cable_modem_termination_system_status_code STRING,
  cable_modem_termination_system_name STRING,
  node_health_score_color_bucket STRING,
  node_health_score_color_name STRING,
  total_out_of_spec_device_count INT,
  upstream_uncorrectable_fec_percentage DOUBLE,
  upstream_correctable_fec_percentage DOUBLE,
  downstream_uncorrectable_fec_percentage DOUBLE,
  downstream_correctable_fec_percentage DOUBLE,
  upstream_average_snr DOUBLE,
  upstream_snr_variance DOUBLE,
  downstream_average_snr DOUBLE,
  downstream_snr_variance DOUBLE,
  downstream_snr_out_of_spec_device_count DOUBLE,
  upstream_hybrid_fiber_coax_rf_variance DOUBLE,
  downstream_hybrid_fiber_coax_rf_variance DOUBLE,
  out_of_spec_device_count INT,
  out_of_spec_device_percentage DOUBLE,
  t3_timeout_count INT,
  upstream_inchannel_frequency_response_percentage DOUBLE,
  upstream_ripple_percentage DOUBLE,
  upstream_echo_percentage DOUBLE,
  consecutive_sub_prime_node_health_days INT,
  revenue_generating_units_count INT,
  total_subscriber_count INT,
  video_subscriber_count INT,
  internet_subscriber_count INT,
  voice_subscriber_count INT,
  line_problem_service_repair_order_count INT,
  trouble_call_repeat_count INT,
  trouble_call_repeat_within_seven_days_count INT,
  video_trouble_call_repeat_within_seven_days_count INT,
  internet_trouble_call_repeat_within_seven_days_count INT,
  voice_trouble_call_repeat_within_seven_days_count INT)
PARTITIONED BY (
  partition_date_denver STRING,
  extract_source STRING)
STORED AS ORC
LOCATION '${s3_location}'
TBLPROPERTIES ("orc.compress" = "ZLIB");