USE ${env:DASP_db};

set hive.auto.convert.join=false;
set hive.exec.dynamic.partition.mode=nonstrict;
set hive.optimize.sort.dynamic.partition=false;
set hive.support.concurrency=false;
set hive.tez.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat;
set hive.txn.manager=org.apache.hadoop.hive.ql.lockmgr.DummyTxnManager;
set orc.force.positional.evolution=true;
SET hive.merge.tezfiles=true;
set hive.merge.smallfiles.avgsize=2048000000;
set hive.merge.size.per.task=2048000000;


-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
--
-- instances metrics
--
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

INSERT INTO ${env:TMP_db}.quantum_set_agg_portals_stage_instances_${hiveconf:execid}_${hiveconf:stepid}
SELECT
  CASE WHEN (grouping_id & 32768) = 0 THEN mso ELSE 'All Companies' END AS mso,
  CASE WHEN (grouping_id & 16384) = 0 THEN application_type ELSE 'All Applications' END AS application_type,
  CASE WHEN (grouping_id & 8192) = 0 THEN device_type ELSE 'All Devices' END AS device_type,
  CASE WHEN (grouping_id & 4096) = 0 THEN connection_type ELSE 'All Connections' END AS connection_type,
  CASE WHEN (grouping_id & 2048) = 0 THEN network_status ELSE 'All Network Statuses' END AS network_status,
  CASE WHEN (grouping_id & 1024) = 0 THEN playback_type ELSE 'All Playback Types' END AS playback_type,
  CASE WHEN (grouping_id & 512) = 0 THEN cust_type ELSE 'All Customer Types' END AS cust_type,
  CASE WHEN (grouping_id & 256) = 0 THEN application_group_type ELSE 'All Application Group Types' END AS application_group_type,
  CASE WHEN (grouping_id & 128) = 0 THEN app_version ELSE 'All App Versions' END AS app_version,
  grouping_id,
  metric_name,
  metric_value,
  CASE WHEN (grouping_id & 64) = 0 THEN logged_in_status ELSE 'All Logged In Statuses' END AS logged_in_status,
  CASE WHEN (grouping_id & 32) = 0 THEN application_name ELSE 'All App Versions' END AS application_name,
  CASE WHEN (grouping_id & 16) = 0 THEN os_name ELSE 'All OS Names' END AS os_name,
  CASE WHEN (grouping_id & 8) = 0 THEN os_version ELSE 'All OS Versions' END AS os_version,
  CASE WHEN (grouping_id & 4) = 0 THEN browser_name ELSE 'All Browser Names' END AS browser_name,
  CASE WHEN (grouping_id & 2) = 0 THEN browser_version ELSE 'All Browser Versions' END AS browser_version,
  CASE WHEN (grouping_id & 1) = 0 THEN form_factor ELSE 'All Form Factors' END AS form_factor,
  '${hiveconf:ProcessTimestamp}' as process_date_time_denver,
  '${hiveconf:ProcessUser}' AS process_identity,
  'instances' AS unit_type,
  cast(NULL as STRING) as call_count_24h,
  label_date_denver,
  '${hiveconf:grain}' AS grain
FROM
  (
  SELECT
    '${hiveconf:label_date_denver}' AS label_date_denver,
    mso,
    application_type,
    device_type,
    connection_type,
    network_status,
    playback_type,
    cust_type,
    application_group_type,
    app_version,
    logged_in_status,
    application_name,
    os_name,
    os_version,
    browser_name,
    browser_version,
    form_factor,
    CAST(grouping__id AS INT) AS grouping_id,
      MAP(

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
     'portals_access_voice_platform_via_tile', SUM(portals_access_voice_platform_via_tile),
     'portals_account_billing_support_views', SUM(portals_account_billing_support_views),
     'portals_account_settings_click_install_wifi_profile', SUM(portals_account_settings_click_install_wifi_profile),
     'portals_account_settings_click_manage_people', SUM(portals_account_settings_click_manage_people),
     'portals_account_settings_click_save_contact_info', SUM(portals_account_settings_click_save_contact_info),
     'portals_account_settings_home_page_views', SUM(portals_account_settings_home_page_views),
     'portals_account_settings_manage_contact_info_page_views', SUM(portals_account_settings_manage_contact_info_page_views),
     'portals_account_settings_manage_people_page_views', SUM(portals_account_settings_manage_people_page_views),
     'portals_account_settings_your_info_tab_views', SUM(portals_account_settings_your_info_tab_views),
     'portals_all_equipment_reset_flow_failures', SUM(portals_all_equipment_reset_flow_failures),
     'portals_all_equipment_reset_flow_starts', SUM(portals_all_equipment_reset_flow_starts),
     'portals_all_equipment_reset_flow_successes', SUM(portals_all_equipment_reset_flow_successes),
     'portals_asd_paperless_enroll', SUM(portals_asd_paperless_enroll),
     'portals_auth_homepage_page_views', SUM(portals_auth_homepage_page_views),
     'portals_bill_delivery_pref_exit', SUM(portals_bill_delivery_pref_exit),
     'portals_bill_delivery_pref_keep_paperless', SUM(portals_bill_delivery_pref_keep_paperless),
     'portals_bill_delivery_pref_manage_paperless', SUM(portals_bill_delivery_pref_manage_paperless),
     'portals_bill_delivery_pref_paper', SUM(portals_bill_delivery_pref_paper),
     'portals_bill_delivery_pref_paper_failure', SUM(portals_bill_delivery_pref_paper_failure),
     'portals_bill_delivery_pref_paper_success', SUM(portals_bill_delivery_pref_paper_success),
     'portals_bill_delivery_pref_paperless_enroll_from_homepage', SUM(portals_bill_delivery_pref_paperless_enroll_from_homepage),
     'portals_bill_delivery_pref_paperless_failure', SUM(portals_bill_delivery_pref_paperless_failure),
     'portals_bill_delivery_pref_paperless_submit', SUM(portals_bill_delivery_pref_paperless_submit),
     'portals_bill_delivery_pref_paperless_submit_from_billinghome', SUM(portals_bill_delivery_pref_paperless_submit_from_billinghome),
     'portals_bill_delivery_pref_paperless_submit_from_homepage', SUM(portals_bill_delivery_pref_paperless_submit_from_homepage),
     'portals_bill_delivery_pref_paperless_success', SUM(portals_bill_delivery_pref_paperless_success),
     'portals_billing_feature_interaction', SUM(portals_billing_feature_interaction),
     'portals_billing_feature_page_view', SUM(portals_billing_feature_page_view),
     'portals_biometrics_fingerprint_enroll', SUM(portals_biometrics_fingerprint_enroll),
     'portals_call_support', SUM(portals_call_support),
     'portals_cancel_pause_device', SUM(portals_cancel_pause_device),
     'portals_cancel_tutorial_equip_page_three', SUM(portals_cancel_tutorial_equip_page_three),
     'portals_cancel_tutorial_otp_page_two', SUM(portals_cancel_tutorial_otp_page_two),
     'portals_cancel_tutorial_start_page_one', SUM(portals_cancel_tutorial_start_page_one),
     'portals_cancel_unpause_device', SUM(portals_cancel_unpause_device),
     'portals_cancelled_service_appointment_start', SUM(portals_cancelled_service_appointment_start),
     'portals_cancelled_service_appointments', SUM(portals_cancelled_service_appointments),
     'portals_confirm_remove_device', SUM(portals_confirm_remove_device),
     'portals_contact_us_page_views', SUM(portals_contact_us_page_views),
     'portals_csat_campaign_dismiss', SUM(portals_csat_campaign_dismiss),
     'portals_csat_campaign_interaction', SUM(portals_csat_campaign_interaction),
     'portals_csat_submit_feedback_cancel_written_feedback', SUM(portals_csat_submit_feedback_cancel_written_feedback),
     'portals_csat_submit_rating_1_very_dissatisfied', SUM(portals_csat_submit_rating_1_very_dissatisfied),
     'portals_csat_submit_rating_2_dissatisfied', SUM(portals_csat_submit_rating_2_dissatisfied),
     'portals_csat_submit_rating_3_neutral', SUM(portals_csat_submit_rating_3_neutral),
     'portals_csat_submit_rating_4_satisfied', SUM(portals_csat_submit_rating_4_satisfied),
     'portals_csat_submit_rating_5_very_satisfied', SUM(portals_csat_submit_rating_5_very_satisfied),
     'portals_csat_submit_rating_all', SUM(portals_csat_submit_rating_all),
     'portals_csat_submit_written_feedback', SUM(portals_csat_submit_written_feedback),
     'portals_download_wifi_profile_button_click', SUM(portals_download_wifi_profile_button_click),
     'portals_download_wifi_profile_button_click_android', SUM(portals_download_wifi_profile_button_click_android),
     'portals_download_wifi_profile_button_click_ios', SUM(portals_download_wifi_profile_button_click_ios),
     'portals_download_wifi_profile_success', SUM(portals_download_wifi_profile_success),
     'portals_download_wifi_profile_success_android', SUM(portals_download_wifi_profile_success_android),
     'portals_ed_my_internet_services', SUM(portals_ed_my_internet_services),
     'portals_ed_my_voice_services', SUM(portals_ed_my_voice_services),
     'portals_equipment_cancel_edit_ssid_select_action', SUM(portals_equipment_cancel_edit_ssid_select_action),
     'portals_equipment_confirm_edit_ssid_select_action', SUM(portals_equipment_confirm_edit_ssid_select_action),
     'portals_equipment_detail_views', SUM(portals_equipment_detail_views),
     'portals_equipment_edit_ssid_select_action', SUM(portals_equipment_edit_ssid_select_action),
     'portals_equipment_feature_interaction', SUM(portals_equipment_feature_interaction),
     'portals_equipment_list_view', SUM(portals_equipment_list_view),
     'portals_equipment_reset_flow_submit_all', SUM(portals_equipment_reset_flow_submit_all),
     'portals_footer_getsupport_acct_support', SUM(portals_footer_getsupport_acct_support),
     'portals_footer_getsupport_support_home', SUM(portals_footer_getsupport_support_home),
     'portals_forgot_password_flow_start', SUM(portals_forgot_password_flow_start),
     'portals_forgot_password_success', SUM(portals_forgot_password_success),
     'portals_forgot_username_flow_start', SUM(portals_forgot_username_flow_start),
     'portals_forgot_username_success', SUM(portals_forgot_username_success),
     'portals_guided_tour_click_next', SUM(portals_guided_tour_click_next),
     'portals_guided_tour_exit', SUM(portals_guided_tour_exit),
     'portals_guided_tour_initiated_modal_view', SUM(portals_guided_tour_initiated_modal_view),
     'portals_guided_tour_one_of_three', SUM(portals_guided_tour_one_of_three),
     'portals_guided_tour_show_me_later', SUM(portals_guided_tour_show_me_later),
     'portals_guided_tour_three_of_three', SUM(portals_guided_tour_three_of_three),
     'portals_guided_tour_two_of_three', SUM(portals_guided_tour_two_of_three),
     'portals_install_wifi_profile_start', SUM(portals_install_wifi_profile_start),
     'portals_install_wifi_profile_success', SUM(portals_install_wifi_profile_success),
     'portals_internet_equipment_reset_flow_failures', SUM(portals_internet_equipment_reset_flow_failures),
     'portals_internet_equipment_reset_flow_starts', SUM(portals_internet_equipment_reset_flow_starts),
     'portals_internet_equipment_reset_flow_submit', SUM(portals_internet_equipment_reset_flow_submit),
     'portals_internet_equipment_reset_flow_successes', SUM(portals_internet_equipment_reset_flow_successes),
     'portals_internet_modem_reset_failures', SUM(portals_internet_modem_reset_failures),
     'portals_internet_modem_router_reset_starts', SUM(portals_internet_modem_router_reset_starts),
     'portals_internet_router_reset_failures', SUM(portals_internet_router_reset_failures),
     'portals_internet_router_reset_successes', SUM(portals_internet_router_reset_successes),
     'portals_internet_support_views', SUM(portals_internet_support_views),
     'portals_iva_opens', SUM(portals_iva_opens),
     'portals_localnav_billing', SUM(portals_localnav_billing),
     'portals_login_attempts', SUM(portals_login_attempts),
     'portals_login_failures', SUM(portals_login_failures),
     'portals_logout', SUM(portals_logout),
     'portals_manage_auto_payment_cancel', SUM(portals_manage_auto_payment_cancel),
     'portals_manage_auto_payment_starts', SUM(portals_manage_auto_payment_starts),
     'portals_manage_auto_payment_successes', SUM(portals_manage_auto_payment_successes),
     'portals_manual_reset_failures', SUM(portals_manual_reset_failures),
     'portals_manual_reset_starts', SUM(portals_manual_reset_starts),
     'portals_manual_reset_success', SUM(portals_manual_reset_success),
     'portals_msa_experience_feedback_click_submit_feedback', SUM(portals_msa_experience_feedback_click_submit_feedback),
     'portals_msa_experience_feedback_goal_accomplished', SUM(portals_msa_experience_feedback_goal_accomplished),
     'portals_msa_experience_feedback_goal_not_accomplished', SUM(portals_msa_experience_feedback_goal_not_accomplished),
     'portals_one_time_alert_clicked', SUM(portals_one_time_alert_clicked),
     'portals_one_time_page_alert_displayed', SUM(portals_one_time_page_alert_displayed),
     'portals_one_time_payment_amount', SUM(portals_one_time_payment_amount),
     'portals_one_time_payment_checking', SUM(portals_one_time_payment_checking),
     'portals_one_time_payment_checking_account', SUM(portals_one_time_payment_checking_account),
     'portals_one_time_payment_credit', SUM(portals_one_time_payment_credit),
     'portals_one_time_payment_credit_debit_card', SUM(portals_one_time_payment_credit_debit_card),
     'portals_one_time_payment_date', SUM(portals_one_time_payment_date),
     'portals_one_time_payment_date_other', SUM(portals_one_time_payment_date_other),
     'portals_one_time_payment_date_past_due', SUM(portals_one_time_payment_date_past_due),
     'portals_one_time_payment_date_today', SUM(portals_one_time_payment_date_today),
     'portals_one_time_payment_failures', SUM(portals_one_time_payment_failures),
     'portals_one_time_payment_savings', SUM(portals_one_time_payment_savings),
     'portals_one_time_payment_savings_account', SUM(portals_one_time_payment_savings_account),
     'portals_one_time_payment_select_amount', SUM(portals_one_time_payment_select_amount),
     'portals_one_time_payment_select_date', SUM(portals_one_time_payment_select_date),
     'portals_one_time_payment_select_payment_method', SUM(portals_one_time_payment_select_payment_method),
     'portals_one_time_payment_starts', SUM(portals_one_time_payment_starts),
     'portals_one_time_payment_submission_new_payment_method', SUM(portals_one_time_payment_submission_new_payment_method),
     'portals_one_time_payment_submission_new_payment_method_not_stored', SUM(portals_one_time_payment_submission_new_payment_method_not_stored),
     'portals_one_time_payment_submission_new_payment_method_stored', SUM(portals_one_time_payment_submission_new_payment_method_stored),
     'portals_one_time_payment_submission_previously_stored_payment_method', SUM(portals_one_time_payment_submission_previously_stored_payment_method),
     'portals_one_time_payment_submits', SUM(portals_one_time_payment_submits),
     'portals_one_time_payment_submits_with_ap', SUM(portals_one_time_payment_submits_with_ap),
     'portals_one_time_payment_submits_without_ap', SUM(portals_one_time_payment_submits_without_ap),
     'portals_one_time_payment_successes', SUM(portals_one_time_payment_successes),
     'portals_one_time_payment_successes_with_ap_enroll', SUM(portals_one_time_payment_successes_with_ap_enroll),
     'portals_one_time_payment_successes_without_ap_enroll', SUM(portals_one_time_payment_successes_without_ap_enroll),
     'portals_page_views', SUM(portals_page_views),
     'portals_paperless_radio_toggle', SUM(portals_paperless_radio_toggle),
     'portals_paperless_toggle', SUM(portals_paperless_toggle),
     'portals_rescheduled_service_appointment_start', SUM(portals_rescheduled_service_appointment_start),
     'portals_rescheduled_service_appointments', SUM(portals_rescheduled_service_appointments),
     'portals_router_advanced_settings_click_about_port_forward', SUM(portals_router_advanced_settings_click_about_port_forward),
     'portals_router_advanced_settings_click_add_port_assignment', SUM(portals_router_advanced_settings_click_add_port_assignment),
     'portals_router_advanced_settings_click_cancel_dns_change', SUM(portals_router_advanced_settings_click_cancel_dns_change),
     'portals_router_advanced_settings_click_cancel_port_assignment', SUM(portals_router_advanced_settings_click_cancel_port_assignment),
     'portals_router_advanced_settings_click_create_ip_reservation', SUM(portals_router_advanced_settings_click_create_ip_reservation),
     'portals_router_advanced_settings_click_delete_or_cancel_delete_port', SUM(portals_router_advanced_settings_click_delete_or_cancel_delete_port),
     'portals_router_advanced_settings_click_delete_port', SUM(portals_router_advanced_settings_click_delete_port),
     'portals_router_advanced_settings_click_dns', SUM(portals_router_advanced_settings_click_dns),
     'portals_router_advanced_settings_click_manage_dns', SUM(portals_router_advanced_settings_click_manage_dns),
     'portals_router_advanced_settings_click_manage_ip_reservations', SUM(portals_router_advanced_settings_click_manage_ip_reservations),
     'portals_router_advanced_settings_click_port_forward', SUM(portals_router_advanced_settings_click_port_forward),
     'portals_router_advanced_settings_click_reset_dns_default', SUM(portals_router_advanced_settings_click_reset_dns_default),
     'portals_router_advanced_settings_click_save_confirm_dns', SUM(portals_router_advanced_settings_click_save_confirm_dns),
     'portals_router_advanced_settings_click_spectrum_dns_default', SUM(portals_router_advanced_settings_click_spectrum_dns_default),
     'portals_router_advanced_settings_click_upnp', SUM(portals_router_advanced_settings_click_upnp),
     'portals_router_advanced_settings_click_use_existing_port', SUM(portals_router_advanced_settings_click_use_existing_port),
     'portals_router_advanced_settings_delete_port_assignment_via_swipe', SUM(portals_router_advanced_settings_delete_port_assignment_via_swipe),
     'portals_router_advanced_settings_port_unavailable_modal', SUM(portals_router_advanced_settings_port_unavailable_modal),
     'portals_router_advanced_settings_reserve_ip_toggle_off', SUM(portals_router_advanced_settings_reserve_ip_toggle_off),
     'portals_router_advanced_settings_reserve_ip_toggle_on', SUM(portals_router_advanced_settings_reserve_ip_toggle_on),
     'portals_router_advanced_settings_upnp_toggle_off', SUM(portals_router_advanced_settings_upnp_toggle_off),
     'portals_router_advanced_settings_upnp_toggle_on', SUM(portals_router_advanced_settings_upnp_toggle_on),
     'portals_save_edit_device_nickname', SUM(portals_save_edit_device_nickname),
     'portals_scp_click_cancel_pause_device', SUM(portals_scp_click_cancel_pause_device),
     'portals_scp_click_cancel_unpause_device', SUM(portals_scp_click_cancel_unpause_device),
     'portals_scp_click_not_connected_devices_tab', SUM(portals_scp_click_not_connected_devices_tab),
     'portals_scp_click_pause_device', SUM(portals_scp_click_pause_device),
     'portals_scp_click_paused_tab', SUM(portals_scp_click_paused_tab),
     'portals_scp_click_unpause_device', SUM(portals_scp_click_unpause_device),
     'portals_scp_final_confirm_create_pod_name_failure', SUM(portals_scp_final_confirm_create_pod_name_failure),
     'portals_scp_final_confirm_create_pod_name_success', SUM(portals_scp_final_confirm_create_pod_name_success),
     'portals_scp_final_confirm_device_nickname_change_failure', SUM(portals_scp_final_confirm_device_nickname_change_failure),
     'portals_scp_final_confirm_device_nickname_change_success', SUM(portals_scp_final_confirm_device_nickname_change_success),
     'portals_scp_final_confirm_device_type_and_nickname_change_failure', SUM(portals_scp_final_confirm_device_type_and_nickname_change_failure),
     'portals_scp_final_confirm_device_type_and_nickname_change_success', SUM(portals_scp_final_confirm_device_type_and_nickname_change_success),
     'portals_scp_final_confirm_device_type_icon_update_failure', SUM(portals_scp_final_confirm_device_type_icon_update_failure),
     'portals_scp_final_confirm_device_type_icon_update_success', SUM(portals_scp_final_confirm_device_type_icon_update_success),
     'portals_scp_final_confirm_edit_pod_name_failure', SUM(portals_scp_final_confirm_edit_pod_name_failure),
     'portals_scp_final_confirm_edit_pod_name_success', SUM(portals_scp_final_confirm_edit_pod_name_success),
     'portals_scp_final_confirm_pause_failure', SUM(portals_scp_final_confirm_pause_failure),
     'portals_scp_final_confirm_pause_success', SUM(portals_scp_final_confirm_pause_success),
     'portals_scp_final_confirm_refresh_pod_failure', SUM(portals_scp_final_confirm_refresh_pod_failure),
     'portals_scp_final_confirm_refresh_pod_success', SUM(portals_scp_final_confirm_refresh_pod_success),
     'portals_scp_final_confirm_remove_device_failure', SUM(portals_scp_final_confirm_remove_device_failure),
     'portals_scp_final_confirm_remove_device_success', SUM(portals_scp_final_confirm_remove_device_success),
     'portals_scp_final_confirm_unpause_failure', SUM(portals_scp_final_confirm_unpause_failure),
     'portals_scp_final_confirm_unpause_success', SUM(portals_scp_final_confirm_unpause_success),
     'portals_scp_list_of_pods_pv', SUM(portals_scp_list_of_pods_pv),
     'portals_scp_pod_details_pv', SUM(portals_scp_pod_details_pv),
     'portals_scp_remove_device_cancel', SUM(portals_scp_remove_device_cancel),
     'portals_scp_select_pod_from_list', SUM(portals_scp_select_pod_from_list),
     'portals_security_qa_campaign_interaction', SUM(portals_security_qa_campaign_interaction),
     'portals_security_qa_update_security_page_view', SUM(portals_security_qa_update_security_page_view),
     'portals_select_actions', SUM(portals_select_actions),
     'portals_set_up_auto_payment_failures', SUM(portals_set_up_auto_payment_failures),
     'portals_set_up_auto_payment_starts', SUM(portals_set_up_auto_payment_starts),
     'portals_set_up_auto_payment_submits', SUM(portals_set_up_auto_payment_submits),
     'portals_set_up_auto_payment_submits_plus_otp', SUM(portals_set_up_auto_payment_submits_plus_otp),
     'portals_set_up_auto_payment_successes', SUM(portals_set_up_auto_payment_successes),
     'portals_set_up_auto_payment_successes_with_payment', SUM(portals_set_up_auto_payment_successes_with_payment),
     'portals_set_up_auto_payment_successes_without_payment', SUM(portals_set_up_auto_payment_successes_without_payment),
     'portals_settings_sign_in_security_manage_select_action', SUM(portals_settings_sign_in_security_manage_select_action),
     'portals_settings_sign_in_security_subnav_people_select_action', SUM(portals_settings_sign_in_security_subnav_people_select_action),
     'portals_settings_verify_select_action', SUM(portals_settings_verify_select_action),
     'portals_settings_your_info_changes_success', SUM(portals_settings_your_info_changes_success),
     'portals_settings_your_info_manage_select_action', SUM(portals_settings_your_info_manage_select_action),
     'portals_settings_your_info_save_select_action', SUM(portals_settings_your_info_save_select_action),
     'portals_settings_your_info_verify_identity_modal_view', SUM(portals_settings_your_info_verify_identity_modal_view),
     'portals_settings_your_info_verify_success', SUM(portals_settings_your_info_verify_success),
     'portals_site_unique', SUM(portals_site_unique),
     'portals_site_unique_auth', SUM(portals_site_unique_auth),
     'portals_site_unique_mobile', SUM(portals_site_unique_mobile),
     'portals_site_unique_pc', SUM(portals_site_unique_pc),
     'portals_start_pause_device', SUM(portals_start_pause_device),
     'portals_start_unpause_device', SUM(portals_start_unpause_device),
     'portals_support_article_select', SUM(portals_support_article_select),
     'portals_support_button', SUM(portals_support_button),
     'portals_support_page_views', SUM(portals_support_page_views),
     'portals_tech_tracker_auth_views', SUM(portals_tech_tracker_auth_views),
     'portals_tech_tracker_unauth_views', SUM(portals_tech_tracker_unauth_views),
     'portals_tutorial_account_page_five_page_view', SUM(portals_tutorial_account_page_five_page_view),
     'portals_tutorial_account_page_four_page_view', SUM(portals_tutorial_account_page_four_page_view),
     'portals_tutorial_equip_page_three_page_view', SUM(portals_tutorial_equip_page_three_page_view),
     'portals_tutorial_otp_page_two_page_view', SUM(portals_tutorial_otp_page_two_page_view),
     'portals_tutorial_start_page_one_page_view', SUM(portals_tutorial_start_page_one_page_view),
     'portals_tutorial_views', SUM(portals_tutorial_views),
     'portals_tv_equipment_reset_flow_failures', SUM(portals_tv_equipment_reset_flow_failures),
     'portals_tv_equipment_reset_flow_starts', SUM(portals_tv_equipment_reset_flow_starts),
     'portals_tv_equipment_reset_flow_submit', SUM(portals_tv_equipment_reset_flow_submit),
     'portals_tv_equipment_reset_flow_successes', SUM(portals_tv_equipment_reset_flow_successes),
     'portals_tv_modem_reset_failures', SUM(portals_tv_modem_reset_failures),
     'portals_tv_router_reset_failures', SUM(portals_tv_router_reset_failures),
     'portals_unauth_homepage_page_views', SUM(portals_unauth_homepage_page_views),
     'portals_update_missing_contact_campaign_interaction', SUM(portals_update_missing_contact_campaign_interaction),
     'portals_update_missing_contact_cancel_close_window', SUM(portals_update_missing_contact_cancel_close_window),
     'portals_update_missing_contact_save', SUM(portals_update_missing_contact_save),
     'portals_update_missing_contact_save_all', SUM(portals_update_missing_contact_save_all),
     'portals_update_missing_contact_save_and_continue', SUM(portals_update_missing_contact_save_and_continue),
     'portals_update_missing_contact_skip_this', SUM(portals_update_missing_contact_skip_this),
     'portals_update_missing_contact_update_all', SUM(portals_update_missing_contact_update_all),
     'portals_upgrade_links_overview', SUM(portals_upgrade_links_overview),
     'portals_upgrade_service_internet', SUM(portals_upgrade_service_internet),
     'portals_video_support_views', SUM(portals_video_support_views),
     'portals_view_connected_devices', SUM(portals_view_connected_devices),
     'portals_view_online_statments', SUM(portals_view_online_statments),
     'portals_voice_delete_messages', SUM(portals_voice_delete_messages),
     'portals_voice_equipment_reset_flow_failures', SUM(portals_voice_equipment_reset_flow_failures),
     'portals_voice_equipment_reset_flow_starts', SUM(portals_voice_equipment_reset_flow_starts),
     'portals_voice_equipment_reset_flow_submit', SUM(portals_voice_equipment_reset_flow_submit),
     'portals_voice_equipment_reset_flow_successes', SUM(portals_voice_equipment_reset_flow_successes),
     'portals_voice_modem_reset_failures', SUM(portals_voice_modem_reset_failures),
     'portals_voice_pageviews', SUM(portals_voice_pageviews),
     'portals_voice_play_messages', SUM(portals_voice_play_messages),
     'portals_voice_router_reset_failures', SUM(portals_voice_router_reset_failures),
     'portals_voice_support_views', SUM(portals_voice_support_views),
     'portals_voice_update_call_forward_settings', SUM(portals_voice_update_call_forward_settings),
     'portals_voice_view_messages', SUM(portals_voice_view_messages),
     'portals_voice_voicemail_view_select_action', SUM(portals_voice_voicemail_view_select_action),
     'portals_wifi_password_views', SUM(portals_wifi_password_views),
     'portals_wifi_pw_changes', SUM(portals_wifi_pw_changes)

    --------------------------------------------------------------------------------
    --------------------------------------------------------------------------------
    --------------------------------------------------------------------------------

    ) AS tmp_map
  FROM
    (
    SELECT
      '${hiveconf:label_date_denver}' AS label_date_denver,
      mso,
      application_type,
      application_group_type,
      app_version,
      device_type,
      connection_type,
      network_status,
      playback_type,
      cust_type,
      logged_in AS logged_in_status,
      application_name,
      'All OS Names' AS os_name,
      operating_system AS os_version,
      browser_name,
      browser_version,
      form_factor,

      --------------------------------------------------------------------------------
      --------------------------------------------------------------------------------
      --------------------------------------------------------------------------------
        SUM(portals_access_voice_platform_via_tile) AS portals_access_voice_platform_via_tile,
        SUM(portals_account_billing_support_views) AS portals_account_billing_support_views,
        SUM(portals_account_settings_click_install_wifi_profile) AS portals_account_settings_click_install_wifi_profile,
        SUM(portals_account_settings_click_manage_people) AS portals_account_settings_click_manage_people,
        SUM(portals_account_settings_click_save_contact_info) AS portals_account_settings_click_save_contact_info,
        SUM(portals_account_settings_home_page_views) AS portals_account_settings_home_page_views,
        SUM(portals_account_settings_manage_contact_info_page_views) AS portals_account_settings_manage_contact_info_page_views,
        SUM(portals_account_settings_manage_people_page_views) AS portals_account_settings_manage_people_page_views,
        SUM(portals_account_settings_your_info_tab_views) AS portals_account_settings_your_info_tab_views,
        SUM(portals_all_equipment_reset_flow_failures) AS portals_all_equipment_reset_flow_failures,
        SUM(portals_all_equipment_reset_flow_starts) AS portals_all_equipment_reset_flow_starts,
        SUM(portals_all_equipment_reset_flow_successes) AS portals_all_equipment_reset_flow_successes,
        SUM(portals_asd_paperless_enroll) AS portals_asd_paperless_enroll,
        SUM(portals_auth_homepage_page_views) AS portals_auth_homepage_page_views,
        SUM(portals_bill_delivery_pref_exit) AS portals_bill_delivery_pref_exit,
        SUM(portals_bill_delivery_pref_keep_paperless) AS portals_bill_delivery_pref_keep_paperless,
        SUM(portals_bill_delivery_pref_manage_paperless) AS portals_bill_delivery_pref_manage_paperless,
        SUM(portals_bill_delivery_pref_paper) AS portals_bill_delivery_pref_paper,
        SUM(portals_bill_delivery_pref_paper_failure) AS portals_bill_delivery_pref_paper_failure,
        SUM(portals_bill_delivery_pref_paper_success) AS portals_bill_delivery_pref_paper_success,
        SUM(portals_bill_delivery_pref_paperless_enroll_from_homepage) AS portals_bill_delivery_pref_paperless_enroll_from_homepage,
        SUM(portals_bill_delivery_pref_paperless_failure) AS portals_bill_delivery_pref_paperless_failure,
        SUM(portals_bill_delivery_pref_paperless_submit) AS portals_bill_delivery_pref_paperless_submit,
        SUM(portals_bill_delivery_pref_paperless_submit_from_billinghome) AS portals_bill_delivery_pref_paperless_submit_from_billinghome,
        SUM(portals_bill_delivery_pref_paperless_submit_from_homepage) AS portals_bill_delivery_pref_paperless_submit_from_homepage,
        SUM(portals_bill_delivery_pref_paperless_success) AS portals_bill_delivery_pref_paperless_success,
        SUM(portals_billing_feature_interaction) AS portals_billing_feature_interaction,
        SUM(portals_billing_feature_page_view) AS portals_billing_feature_page_view,
        SUM(portals_biometrics_fingerprint_enroll) AS portals_biometrics_fingerprint_enroll,
        SUM(portals_call_support) AS portals_call_support,
        SUM(portals_cancel_pause_device) AS portals_cancel_pause_device,
        SUM(portals_cancel_tutorial_equip_page_three) AS portals_cancel_tutorial_equip_page_three,
        SUM(portals_cancel_tutorial_otp_page_two) AS portals_cancel_tutorial_otp_page_two,
        SUM(portals_cancel_tutorial_start_page_one) AS portals_cancel_tutorial_start_page_one,
        SUM(portals_cancel_unpause_device) AS portals_cancel_unpause_device,
        SUM(portals_cancelled_service_appointment_start) AS portals_cancelled_service_appointment_start,
        SUM(portals_cancelled_service_appointments) AS portals_cancelled_service_appointments,
        SUM(portals_confirm_remove_device) AS portals_confirm_remove_device,
        SUM(portals_contact_us_page_views) AS portals_contact_us_page_views,
        SUM(portals_csat_campaign_dismiss) AS portals_csat_campaign_dismiss,
        SUM(portals_csat_campaign_interaction) AS portals_csat_campaign_interaction,
        SUM(portals_csat_submit_feedback_cancel_written_feedback) AS portals_csat_submit_feedback_cancel_written_feedback,
        SUM(portals_csat_submit_rating_1_very_dissatisfied) AS portals_csat_submit_rating_1_very_dissatisfied,
        SUM(portals_csat_submit_rating_2_dissatisfied) AS portals_csat_submit_rating_2_dissatisfied,
        SUM(portals_csat_submit_rating_3_neutral) AS portals_csat_submit_rating_3_neutral,
        SUM(portals_csat_submit_rating_4_satisfied) AS portals_csat_submit_rating_4_satisfied,
        SUM(portals_csat_submit_rating_5_very_satisfied) AS portals_csat_submit_rating_5_very_satisfied,
        SUM(portals_csat_submit_rating_all) AS portals_csat_submit_rating_all,
        SUM(portals_csat_submit_written_feedback) AS portals_csat_submit_written_feedback,
        SUM(portals_download_wifi_profile_button_click) AS portals_download_wifi_profile_button_click,
        SUM(portals_download_wifi_profile_button_click_android) AS portals_download_wifi_profile_button_click_android,
        SUM(portals_download_wifi_profile_button_click_ios) AS portals_download_wifi_profile_button_click_ios,
        SUM(portals_download_wifi_profile_success) AS portals_download_wifi_profile_success,
        SUM(portals_download_wifi_profile_success_android) AS portals_download_wifi_profile_success_android,
        SUM(portals_ed_my_internet_services) AS portals_ed_my_internet_services,
        SUM(portals_ed_my_voice_services) AS portals_ed_my_voice_services,
        SUM(portals_equipment_cancel_edit_ssid_select_action) AS portals_equipment_cancel_edit_ssid_select_action,
        SUM(portals_equipment_confirm_edit_ssid_select_action) AS portals_equipment_confirm_edit_ssid_select_action,
        SUM(portals_equipment_detail_views) AS portals_equipment_detail_views,
        SUM(portals_equipment_edit_ssid_select_action) AS portals_equipment_edit_ssid_select_action,
        SUM(portals_equipment_feature_interaction) AS portals_equipment_feature_interaction,
        SUM(portals_equipment_list_view) AS portals_equipment_list_view,
        SUM(portals_equipment_reset_flow_submit_all) AS portals_equipment_reset_flow_submit_all,
        SUM(portals_footer_getsupport_acct_support) AS portals_footer_getsupport_acct_support,
        SUM(portals_footer_getsupport_support_home) AS portals_footer_getsupport_support_home,
        SUM(portals_forgot_password_flow_start) AS portals_forgot_password_flow_start,
        SUM(portals_forgot_password_success) AS portals_forgot_password_success,
        SUM(portals_forgot_username_flow_start) AS portals_forgot_username_flow_start,
        SUM(portals_forgot_username_success) AS portals_forgot_username_success,
        SUM(portals_guided_tour_click_next) AS portals_guided_tour_click_next,
        SUM(portals_guided_tour_exit) AS portals_guided_tour_exit,
        SUM(portals_guided_tour_initiated_modal_view) AS portals_guided_tour_initiated_modal_view,
        SUM(portals_guided_tour_one_of_three) AS portals_guided_tour_one_of_three,
        SUM(portals_guided_tour_show_me_later) AS portals_guided_tour_show_me_later,
        SUM(portals_guided_tour_three_of_three) AS portals_guided_tour_three_of_three,
        SUM(portals_guided_tour_two_of_three) AS portals_guided_tour_two_of_three,
        SUM(portals_install_wifi_profile_start) AS portals_install_wifi_profile_start,
        SUM(portals_install_wifi_profile_success) AS portals_install_wifi_profile_success,
        SUM(portals_internet_equipment_reset_flow_failures) AS portals_internet_equipment_reset_flow_failures,
        SUM(portals_internet_equipment_reset_flow_starts) AS portals_internet_equipment_reset_flow_starts,
        SUM(portals_internet_equipment_reset_flow_submit) AS portals_internet_equipment_reset_flow_submit,
        SUM(portals_internet_equipment_reset_flow_successes) AS portals_internet_equipment_reset_flow_successes,
        SUM(portals_internet_modem_reset_failures) AS portals_internet_modem_reset_failures,
        SUM(portals_internet_modem_router_reset_starts) AS portals_internet_modem_router_reset_starts,
        SUM(portals_internet_router_reset_failures) AS portals_internet_router_reset_failures,
        SUM(portals_internet_router_reset_successes) AS portals_internet_router_reset_successes,
        SUM(portals_internet_support_views) AS portals_internet_support_views,
        SUM(portals_iva_opens) AS portals_iva_opens,
        SUM(portals_localnav_billing) AS portals_localnav_billing,
        SUM(portals_login_attempts) AS portals_login_attempts,
        SUM(portals_login_failures) AS portals_login_failures,
        SUM(portals_logout) AS portals_logout,
        SUM(portals_manage_auto_payment_cancel) AS portals_manage_auto_payment_cancel,
        SUM(portals_manage_auto_payment_starts) AS portals_manage_auto_payment_starts,
        SUM(portals_manage_auto_payment_successes) AS portals_manage_auto_payment_successes,
        SUM(portals_manual_reset_failures) AS portals_manual_reset_failures,
        SUM(portals_manual_reset_starts) AS portals_manual_reset_starts,
        SUM(portals_manual_reset_success) AS portals_manual_reset_success,
        SUM(portals_msa_experience_feedback_click_submit_feedback) AS portals_msa_experience_feedback_click_submit_feedback,
        SUM(portals_msa_experience_feedback_goal_accomplished) AS portals_msa_experience_feedback_goal_accomplished,
        SUM(portals_msa_experience_feedback_goal_not_accomplished) AS portals_msa_experience_feedback_goal_not_accomplished,
        SUM(portals_one_time_alert_clicked) AS portals_one_time_alert_clicked,
        SUM(portals_one_time_page_alert_displayed) AS portals_one_time_page_alert_displayed,
        SUM(portals_one_time_payment_amount) AS portals_one_time_payment_amount,
        SUM(portals_one_time_payment_checking) AS portals_one_time_payment_checking,
        SUM(portals_one_time_payment_checking_account) AS portals_one_time_payment_checking_account,
        SUM(portals_one_time_payment_credit) AS portals_one_time_payment_credit,
        SUM(portals_one_time_payment_credit_debit_card) AS portals_one_time_payment_credit_debit_card,
        SUM(portals_one_time_payment_date) AS portals_one_time_payment_date,
        SUM(portals_one_time_payment_date_other) AS portals_one_time_payment_date_other,
        SUM(portals_one_time_payment_date_past_due) AS portals_one_time_payment_date_past_due,
        SUM(portals_one_time_payment_date_today) AS portals_one_time_payment_date_today,
        SUM(portals_one_time_payment_failures) AS portals_one_time_payment_failures,
        SUM(portals_one_time_payment_savings) AS portals_one_time_payment_savings,
        SUM(portals_one_time_payment_savings_account) AS portals_one_time_payment_savings_account,
        SUM(portals_one_time_payment_select_amount) AS portals_one_time_payment_select_amount,
        SUM(portals_one_time_payment_select_date) AS portals_one_time_payment_select_date,
        SUM(portals_one_time_payment_select_payment_method) AS portals_one_time_payment_select_payment_method,
        SUM(portals_one_time_payment_starts) AS portals_one_time_payment_starts,
        SUM(portals_one_time_payment_submission_new_payment_method) AS portals_one_time_payment_submission_new_payment_method,
        SUM(portals_one_time_payment_submission_new_payment_method_not_stored) AS portals_one_time_payment_submission_new_payment_method_not_stored,
        SUM(portals_one_time_payment_submission_new_payment_method_stored) AS portals_one_time_payment_submission_new_payment_method_stored,
        SUM(portals_one_time_payment_submission_previously_stored_payment_method) AS portals_one_time_payment_submission_previously_stored_payment_method,
        SUM(portals_one_time_payment_submits) AS portals_one_time_payment_submits,
        SUM(portals_one_time_payment_submits_with_ap) AS portals_one_time_payment_submits_with_ap,
        SUM(portals_one_time_payment_submits_without_ap) AS portals_one_time_payment_submits_without_ap,
        SUM(portals_one_time_payment_successes) AS portals_one_time_payment_successes,
        SUM(portals_one_time_payment_successes_with_ap_enroll) AS portals_one_time_payment_successes_with_ap_enroll,
        SUM(portals_one_time_payment_successes_without_ap_enroll) AS portals_one_time_payment_successes_without_ap_enroll,
        SUM(portals_page_views) AS portals_page_views,
        SUM(portals_paperless_radio_toggle) AS portals_paperless_radio_toggle,
        SUM(portals_paperless_toggle) AS portals_paperless_toggle,
        SUM(portals_rescheduled_service_appointment_start) AS portals_rescheduled_service_appointment_start,
        SUM(portals_rescheduled_service_appointments) AS portals_rescheduled_service_appointments,
        SUM(portals_router_advanced_settings_click_about_port_forward) AS portals_router_advanced_settings_click_about_port_forward,
        SUM(portals_router_advanced_settings_click_add_port_assignment) AS portals_router_advanced_settings_click_add_port_assignment,
        SUM(portals_router_advanced_settings_click_cancel_dns_change) AS portals_router_advanced_settings_click_cancel_dns_change,
        SUM(portals_router_advanced_settings_click_cancel_port_assignment) AS portals_router_advanced_settings_click_cancel_port_assignment,
        SUM(portals_router_advanced_settings_click_create_ip_reservation) AS portals_router_advanced_settings_click_create_ip_reservation,
        SUM(portals_router_advanced_settings_click_delete_or_cancel_delete_port) AS portals_router_advanced_settings_click_delete_or_cancel_delete_port,
        SUM(portals_router_advanced_settings_click_delete_port) AS portals_router_advanced_settings_click_delete_port,
        SUM(portals_router_advanced_settings_click_dns) AS portals_router_advanced_settings_click_dns,
        SUM(portals_router_advanced_settings_click_manage_dns) AS portals_router_advanced_settings_click_manage_dns,
        SUM(portals_router_advanced_settings_click_manage_ip_reservations) AS portals_router_advanced_settings_click_manage_ip_reservations,
        SUM(portals_router_advanced_settings_click_port_forward) AS portals_router_advanced_settings_click_port_forward,
        SUM(portals_router_advanced_settings_click_reset_dns_default) AS portals_router_advanced_settings_click_reset_dns_default,
        SUM(portals_router_advanced_settings_click_save_confirm_dns) AS portals_router_advanced_settings_click_save_confirm_dns,
        SUM(portals_router_advanced_settings_click_spectrum_dns_default) AS portals_router_advanced_settings_click_spectrum_dns_default,
        SUM(portals_router_advanced_settings_click_upnp) AS portals_router_advanced_settings_click_upnp,
        SUM(portals_router_advanced_settings_click_use_existing_port) AS portals_router_advanced_settings_click_use_existing_port,
        SUM(portals_router_advanced_settings_delete_port_assignment_via_swipe) AS portals_router_advanced_settings_delete_port_assignment_via_swipe,
        SUM(portals_router_advanced_settings_port_unavailable_modal) AS portals_router_advanced_settings_port_unavailable_modal,
        SUM(portals_router_advanced_settings_reserve_ip_toggle_off) AS portals_router_advanced_settings_reserve_ip_toggle_off,
        SUM(portals_router_advanced_settings_reserve_ip_toggle_on) AS portals_router_advanced_settings_reserve_ip_toggle_on,
        SUM(portals_router_advanced_settings_upnp_toggle_off) AS portals_router_advanced_settings_upnp_toggle_off,
        SUM(portals_router_advanced_settings_upnp_toggle_on) AS portals_router_advanced_settings_upnp_toggle_on,
        SUM(portals_save_edit_device_nickname) AS portals_save_edit_device_nickname,
        SUM(portals_scp_click_cancel_pause_device) AS portals_scp_click_cancel_pause_device,
        SUM(portals_scp_click_cancel_unpause_device) AS portals_scp_click_cancel_unpause_device,
        SUM(portals_scp_click_not_connected_devices_tab) AS portals_scp_click_not_connected_devices_tab,
        SUM(portals_scp_click_pause_device) AS portals_scp_click_pause_device,
        SUM(portals_scp_click_paused_tab) AS portals_scp_click_paused_tab,
        SUM(portals_scp_click_unpause_device) AS portals_scp_click_unpause_device,
        SUM(portals_scp_final_confirm_create_pod_name_failure) AS portals_scp_final_confirm_create_pod_name_failure,
        SUM(portals_scp_final_confirm_create_pod_name_success) AS portals_scp_final_confirm_create_pod_name_success,
        SUM(portals_scp_final_confirm_device_nickname_change_failure) AS portals_scp_final_confirm_device_nickname_change_failure,
        SUM(portals_scp_final_confirm_device_nickname_change_success) AS portals_scp_final_confirm_device_nickname_change_success,
        SUM(portals_scp_final_confirm_device_type_and_nickname_change_failure) AS portals_scp_final_confirm_device_type_and_nickname_change_failure,
        SUM(portals_scp_final_confirm_device_type_and_nickname_change_success) AS portals_scp_final_confirm_device_type_and_nickname_change_success,
        SUM(portals_scp_final_confirm_device_type_icon_update_failure) AS portals_scp_final_confirm_device_type_icon_update_failure,
        SUM(portals_scp_final_confirm_device_type_icon_update_success) AS portals_scp_final_confirm_device_type_icon_update_success,
        SUM(portals_scp_final_confirm_edit_pod_name_failure) AS portals_scp_final_confirm_edit_pod_name_failure,
        SUM(portals_scp_final_confirm_edit_pod_name_success) AS portals_scp_final_confirm_edit_pod_name_success,
        SUM(portals_scp_final_confirm_pause_failure) AS portals_scp_final_confirm_pause_failure,
        SUM(portals_scp_final_confirm_pause_success) AS portals_scp_final_confirm_pause_success,
        SUM(portals_scp_final_confirm_refresh_pod_failure) AS portals_scp_final_confirm_refresh_pod_failure,
        SUM(portals_scp_final_confirm_refresh_pod_success) AS portals_scp_final_confirm_refresh_pod_success,
        SUM(portals_scp_final_confirm_remove_device_failure) AS portals_scp_final_confirm_remove_device_failure,
        SUM(portals_scp_final_confirm_remove_device_success) AS portals_scp_final_confirm_remove_device_success,
        SUM(portals_scp_final_confirm_unpause_failure) AS portals_scp_final_confirm_unpause_failure,
        SUM(portals_scp_final_confirm_unpause_success) AS portals_scp_final_confirm_unpause_success,
        SUM(portals_scp_list_of_pods_pv) AS portals_scp_list_of_pods_pv,
        SUM(portals_scp_pod_details_pv) AS portals_scp_pod_details_pv,
        SUM(portals_scp_remove_device_cancel) AS portals_scp_remove_device_cancel,
        SUM(portals_scp_select_pod_from_list) AS portals_scp_select_pod_from_list,
        SUM(portals_security_qa_campaign_interaction) AS portals_security_qa_campaign_interaction,
        SUM(portals_security_qa_update_security_page_view) AS portals_security_qa_update_security_page_view,
        SUM(portals_select_actions) AS portals_select_actions,
        SUM(portals_set_up_auto_payment_failures) AS portals_set_up_auto_payment_failures,
        SUM(portals_set_up_auto_payment_starts) AS portals_set_up_auto_payment_starts,
        SUM(portals_set_up_auto_payment_submits) AS portals_set_up_auto_payment_submits,
        SUM(portals_set_up_auto_payment_submits_plus_otp) AS portals_set_up_auto_payment_submits_plus_otp,
        SUM(portals_set_up_auto_payment_successes) AS portals_set_up_auto_payment_successes,
        SUM(portals_set_up_auto_payment_successes_with_payment) AS portals_set_up_auto_payment_successes_with_payment,
        SUM(portals_set_up_auto_payment_successes_without_payment) AS portals_set_up_auto_payment_successes_without_payment,
        SUM(portals_settings_sign_in_security_manage_select_action) AS portals_settings_sign_in_security_manage_select_action,
        SUM(portals_settings_sign_in_security_subnav_people_select_action) AS portals_settings_sign_in_security_subnav_people_select_action,
        SUM(portals_settings_verify_select_action) AS portals_settings_verify_select_action,
        SUM(portals_settings_your_info_changes_success) AS portals_settings_your_info_changes_success,
        SUM(portals_settings_your_info_manage_select_action) AS portals_settings_your_info_manage_select_action,
        SUM(portals_settings_your_info_save_select_action) AS portals_settings_your_info_save_select_action,
        SUM(portals_settings_your_info_verify_identity_modal_view) AS portals_settings_your_info_verify_identity_modal_view,
        SUM(portals_settings_your_info_verify_success) AS portals_settings_your_info_verify_success,
        SUM(portals_site_unique) AS portals_site_unique,
        SUM(portals_site_unique_auth) AS portals_site_unique_auth,
        SUM(portals_site_unique_mobile) AS portals_site_unique_mobile,
        SUM(portals_site_unique_pc) AS portals_site_unique_pc,
        SUM(portals_start_pause_device) AS portals_start_pause_device,
        SUM(portals_start_unpause_device) AS portals_start_unpause_device,
        SUM(portals_support_article_select) AS portals_support_article_select,
        SUM(portals_support_button) AS portals_support_button,
        SUM(portals_support_page_views) AS portals_support_page_views,
        SUM(portals_tech_tracker_auth_views) AS portals_tech_tracker_auth_views,
        SUM(portals_tech_tracker_unauth_views) AS portals_tech_tracker_unauth_views,
        SUM(portals_tutorial_account_page_five_page_view) AS portals_tutorial_account_page_five_page_view,
        SUM(portals_tutorial_account_page_four_page_view) AS portals_tutorial_account_page_four_page_view,
        SUM(portals_tutorial_equip_page_three_page_view) AS portals_tutorial_equip_page_three_page_view,
        SUM(portals_tutorial_otp_page_two_page_view) AS portals_tutorial_otp_page_two_page_view,
        SUM(portals_tutorial_start_page_one_page_view) AS portals_tutorial_start_page_one_page_view,
        SUM(portals_tutorial_views) AS portals_tutorial_views,
        SUM(portals_tv_equipment_reset_flow_failures) AS portals_tv_equipment_reset_flow_failures,
        SUM(portals_tv_equipment_reset_flow_starts) AS portals_tv_equipment_reset_flow_starts,
        SUM(portals_tv_equipment_reset_flow_submit) AS portals_tv_equipment_reset_flow_submit,
        SUM(portals_tv_equipment_reset_flow_successes) AS portals_tv_equipment_reset_flow_successes,
        SUM(portals_tv_modem_reset_failures) AS portals_tv_modem_reset_failures,
        SUM(portals_tv_router_reset_failures) AS portals_tv_router_reset_failures,
        SUM(portals_unauth_homepage_page_views) AS portals_unauth_homepage_page_views,
        SUM(portals_update_missing_contact_campaign_interaction) AS portals_update_missing_contact_campaign_interaction,
        SUM(portals_update_missing_contact_cancel_close_window) AS portals_update_missing_contact_cancel_close_window,
        SUM(portals_update_missing_contact_save) AS portals_update_missing_contact_save,
        SUM(portals_update_missing_contact_save_all) AS portals_update_missing_contact_save_all,
        SUM(portals_update_missing_contact_save_and_continue) AS portals_update_missing_contact_save_and_continue,
        SUM(portals_update_missing_contact_skip_this) AS portals_update_missing_contact_skip_this,
        SUM(portals_update_missing_contact_update_all) AS portals_update_missing_contact_update_all,
        SUM(portals_upgrade_links_overview) AS portals_upgrade_links_overview,
        SUM(portals_upgrade_service_internet) AS portals_upgrade_service_internet,
        SUM(portals_video_support_views) AS portals_video_support_views,
        SUM(portals_view_connected_devices) AS portals_view_connected_devices,
        SUM(portals_view_online_statments) AS portals_view_online_statments,
        SUM(portals_voice_delete_messages) AS portals_voice_delete_messages,
        SUM(portals_voice_equipment_reset_flow_failures) AS portals_voice_equipment_reset_flow_failures,
        SUM(portals_voice_equipment_reset_flow_starts) AS portals_voice_equipment_reset_flow_starts,
        SUM(portals_voice_equipment_reset_flow_submit) AS portals_voice_equipment_reset_flow_submit,
        SUM(portals_voice_equipment_reset_flow_successes) AS portals_voice_equipment_reset_flow_successes,
        SUM(portals_voice_modem_reset_failures) AS portals_voice_modem_reset_failures,
        SUM(portals_voice_pageviews) AS portals_voice_pageviews,
        SUM(portals_voice_play_messages) AS portals_voice_play_messages,
        SUM(portals_voice_router_reset_failures) AS portals_voice_router_reset_failures,
        SUM(portals_voice_support_views) AS portals_voice_support_views,
        SUM(portals_voice_update_call_forward_settings) AS portals_voice_update_call_forward_settings,
        SUM(portals_voice_view_messages) AS portals_voice_view_messages,
        SUM(portals_voice_voicemail_view_select_action) AS portals_voice_voicemail_view_select_action,
        SUM(portals_wifi_password_views) AS portals_wifi_password_views,
        SUM(portals_wifi_pw_changes) AS portals_wifi_pw_changes

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


      FROM ${hiveconf:inputmetricaggtable}
      WHERE (denver_date >= ("${hiveconf:START_DATE}") AND denver_date < ("${hiveconf:END_DATE}"))
      GROUP BY
        '${hiveconf:label_date_denver}',
        mso,
        application_type,
        device_type,
        connection_type,
        network_status,
        playback_type,
        cust_type,
        application_group_type,
        app_version,
        logged_in,
        application_name,
        'All OS Names',
        operating_system,
        browser_name,
        browser_version,
        form_factor
      ) sumfirst
    GROUP BY
      label_date_denver,
      mso,
      application_type,
      device_type,
      connection_type,
      network_status,
      playback_type,
      cust_type,
      application_group_type,
      app_version,
      logged_in_status,
      application_name,
      os_name,
      os_version,
      browser_name,
      browser_version,
      form_factor
    GROUPING SETS (
      (label_date_denver),
      (label_date_denver, network_status),
      (label_date_denver, network_status, browser_name),
      (label_date_denver, network_status, browser_name, form_factor),
      (label_date_denver, network_status, form_factor),
      (label_date_denver, os_version),
      (label_date_denver, browser_name),
      (label_date_denver, browser_name, form_factor),
      (label_date_denver, browser_name, browser_version),
      (label_date_denver, form_factor),
      (label_date_denver, mso, application_name),
      (label_date_denver, mso, application_name, network_status),
      (label_date_denver, mso, application_name, network_status, app_version),
      (label_date_denver, mso, application_name, network_status, app_version, browser_name),
      (label_date_denver, mso, application_name, network_status, app_version, form_factor),
      (label_date_denver, mso, application_name, network_status, browser_name),
      (label_date_denver, mso, application_name, network_status, browser_name, form_factor),
      (label_date_denver, mso, application_name, network_status, form_factor),
      (label_date_denver, mso, application_name, app_version),
      (label_date_denver, mso, application_name, app_version, browser_name),
      (label_date_denver, mso, application_name, app_version, browser_name, form_factor),
      (label_date_denver, mso, application_name, app_version, form_factor),
      (label_date_denver, mso, application_name, browser_name),
      (label_date_denver, mso, application_name, browser_name, form_factor),
      (label_date_denver, mso, application_name, form_factor),
      (label_date_denver, application_name),
      (label_date_denver, application_name, network_status),
      (label_date_denver, application_name, network_status, app_version),
      (label_date_denver, application_name, network_status, app_version, browser_name),
      (label_date_denver, application_name, network_status, app_version, form_factor),
      (label_date_denver, application_name, network_status, browser_name),
      (label_date_denver, application_name, network_status, browser_name, form_factor),
      (label_date_denver, application_name, network_status, form_factor),
      (label_date_denver, application_name, app_version),
      (label_date_denver, application_name, app_version, browser_name),
      (label_date_denver, application_name, app_version, browser_name, form_factor),
      (label_date_denver, application_name, app_version, browser_name, browser_version),
      (label_date_denver, application_name, app_version, form_factor),
      (label_date_denver, application_name, os_version),
      (label_date_denver, application_name, browser_name),
      (label_date_denver, application_name, browser_name, form_factor),
      (label_date_denver, application_name, browser_name, browser_version),
      (label_date_denver, application_name, form_factor),
      (label_date_denver, application_name, device_type, mso, app_version),
      (label_date_denver, application_name, device_type, mso),
      (label_date_denver, application_name, device_type, app_version),
      (label_date_denver, application_name, device_type))
      ) sets
LATERAL VIEW EXPLODE(tmp_map) explode_table AS metric_name, metric_value;

--------------------------------------------------------------------------------
--------------------------------***** END *****---------------------------------
-----------------------------------------------------------------------------
