#  Azkaban job
type=command
dependencies=03_cs_techmobile_set_agg_reprocess_daily_instances,03_cs_techmobile_set_agg_reprocess_daily_visits,03_cs_techmobile_set_agg_reprocess_daily_devices,03_cs_techmobile_set_agg_reprocess_daily_accounts
command=whoami

command.1=/bin/bash -c 'export execid=${azkaban.flow.execid}; echo $execid; export ProcessUser="${azkaban.flow.submituser}"; echo $ProcessUser; hive -f ../../../src/cs_techmobile_set_agg_final.hql'
