#!/usr/bin/env groovy
@Library('jenkins-util') _    // don't miss the '_' at the end of the line, this is the magical library that does the, uh, 'magic'
PIDeliveryPipeline {
    azkabanProjectName = "asp_extract_technical_debt_factory_monthly" // required
    azkabanEnv = 'prod' // optional, default to dev
    azkabanProjectDesc = "Product Monthly extract" // required
    azkabanProjectOwner = 'jmccune' // required, put your AD login here
    azkabanPlatform = 'ASP'  // required
    azkabanEscalation = 'Marjorie Truitt' // required, one of ['Andrew Ngeow', 'Yong Liu', 'Ty Prinkki', 'Marjorie Truitt', 'Micheal Baldino', 'Nate Vogel']
    azkabanSLA = 'Optional - Next Day' // required, one of ['Optional - Next Day', 'Important - Within 12 hrs', 'Critical - Immediate Response']
    azkabanFlowRun=[] // not implemented, could have loop here too
    azkabanProdFlowSchedule=[flowName:'04_prod_monthly_end', cronExpression:'0 16 15 22 * *']
    gitDir='extract/technical_debt_factory/monthly'  // the sub dir where your project dir is
}
