.d_summary_agg_variables: &d_summary_agg_variables
  JOB_NAME: "d-summary-agg"
  D_SUMMARY_AGG_DIR: "si-jobs/daily-summary-agg"
  ARTIFACTS_DIR: "si-jobs/daily-summary-agg/artifacts"
  TERRAFORM_DIR: "si-jobs/daily-summary-agg/terraform"
  SCRIPTS_DIR: "si-jobs/daily-summary-agg/scripts"
  S3_ARTIFACTS_DIR: "si-jobs/daily-summary-agg"

d_summary_agg_build:
  extends: .build
  variables:
    POST_PROCESSING_SCRIPTS: >
      $JOB_TEMPLATE_DIR/lambda/cmn-post-processors/pass_additional_params_as_step_arg_post_processor.py
    DDL_DIR: "$D_SUMMARY_AGG_DIR/ddl"
    HQL_DIR: "$D_SUMMARY_AGG_DIR/hql"
    <<: *d_summary_agg_variables

#STG
d_summary_agg_plan_stg:
  extends: .plan_stg
  variables:
    <<: *d_summary_agg_variables
  dependencies:
    - d_summary_agg_build

d_summary_agg_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *d_summary_agg_variables
  dependencies:
    - d_summary_agg_build
    - d_summary_agg_plan_stg

d_summary_agg_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *d_summary_agg_variables
  dependencies:
    - d_summary_agg_build

#PROD
d_summary_agg_plan_prod:
  extends: .plan_prod
  variables:
    <<: *d_summary_agg_variables
  dependencies:
    - d_summary_agg_build

d_summary_agg_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *d_summary_agg_variables
  dependencies:
    - d_summary_agg_build
    - d_summary_agg_plan_prod

d_summary_agg_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *d_summary_agg_variables
  dependencies:
    - d_summary_agg_build
