# asp counts Spectrum.net prod hourly
dependencies=00_parameter_init
type=command
command=whoami

command.1=/bin/bash -c 'export START_DATE_TZ="${START_DATE_TZ}"; echo $START_DATE_TZ; export END_DATE_TZ="${END_DATE_TZ}"; echo $END_DATE_TZ;  hive -f ../../src/consumer/01h_d_prod_asp_v_venona_events_portals_specnet__devices__prod_asp_venona_counts_hourly.hql'
command.2=/bin/bash -c 'export START_DATE_TZ="${START_DATE_TZ}"; echo $START_DATE_TZ; export END_DATE_TZ="${END_DATE_TZ}"; echo $END_DATE_TZ;  hive -f ../../src/consumer/01h_h_prod_asp_v_venona_events_portals_specnet__households__prod_asp_venona_counts_hourly.hql'
command.3=/bin/bash -c 'export START_DATE_TZ="${START_DATE_TZ}"; echo $START_DATE_TZ; export END_DATE_TZ="${END_DATE_TZ}"; echo $END_DATE_TZ;  hive -f ../../src/consumer/01h_i_prod_asp_v_venona_events_portals_specnet__instances__prod_asp_venona_counts_hourly.hql'
command.4=/bin/bash -c 'export START_DATE_TZ="${START_DATE_TZ}"; echo $START_DATE_TZ; export END_DATE_TZ="${END_DATE_TZ}"; echo $END_DATE_TZ;  hive -f ../../src/consumer/01h_v_prod_asp_v_venona_events_portals_specnet__visits__prod_asp_venona_counts_hourly.hql'
