# api responses job
type=command
dependencies=01_parameter_init
command=whoami

# use this one if dates are needed
command.1=/bin/bash -c ' export MigrationStartDate="${MigrationStartDate}"; echo $MigrationStartDate; export REPORT_DATE="${REPORT_DATE}"; echo $REPORT_DATE; export START_DATE_TZ="${START_DATE_TZ}"; echo $START_DATE_TZ; export END_DATE_TZ="${END_DATE_TZ}"; echo $END_DATE_TZ;  hive -f ../src/4_report_all.hql'
