.portals_ss_metric_agg_variables: &portals_ss_metric_agg_variables
  JOB_NAME: "portals-ss-metric-agg"
  PORTALS_SS_METRIC_AGG_DIR: "parameterized/portals-ss-metric-agg"
  ARTIFACTS_DIR: "parameterized/portals-ss-metric-agg/artifacts"
  TERRAFORM_DIR: "parameterized/portals-ss-metric-agg/terraform"
  SCRIPTS_DIR: "parameterized/portals-ss-metric-agg/scripts"
  S3_ARTIFACTS_DIR: "parameterized/portals-ss-metric-agg"

portals_ss_metric_agg_build:
  extends: .build
  variables:
    DDL_DIR: "$PORTALS_SS_METRIC_AGG_DIR/ddl"
    HQL_DIR: "$PORTALS_SS_METRIC_AGG_DIR/hql"
    <<: *portals_ss_metric_agg_variables

# PROD
portals_ss_metric_agg_plan_prod:
  extends: .plan_prod
  variables:
    <<: *portals_ss_metric_agg_variables
  dependencies:
    - portals_ss_metric_agg_build

portals_ss_metric_agg_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *portals_ss_metric_agg_variables
  dependencies:
    - portals_ss_metric_agg_build
    - portals_ss_metric_agg_plan_prod

portals_ss_metric_agg_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *portals_ss_metric_agg_variables
  dependencies:
    - portals_ss_metric_agg_build

# STG
portals_ss_metric_agg_plan_stg:
  extends: .plan_stg
  variables:
    <<: *portals_ss_metric_agg_variables
  dependencies:
    - portals_ss_metric_agg_build

portals_ss_metric_agg_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *portals_ss_metric_agg_variables
  dependencies:
    - portals_ss_metric_agg_build
    - portals_ss_metric_agg_plan_stg

portals_ss_metric_agg_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *portals_ss_metric_agg_variables
  dependencies:
    - portals_ss_metric_agg_build
