.w_portals_selfservice_set_agg_variables: &w_portals_selfservice_set_agg_variables
  JOB_NAME: "weekly-parameterized-portals-selfservice-set-agg"
  WEEKLY_PORTALS_SELFSERVICE_SET_AGG_DIR: "parameterized/weekly-portals-ss-set-agg"
  ARTIFACTS_DIR: "parameterized/weekly-portals-ss-set-agg/artifacts"
  TERRAFORM_DIR: "parameterized/weekly-portals-ss-set-agg/terraform"
  SCRIPTS_DIR: "parameterized/weekly-portals-ss-set-agg/scripts"
  S3_ARTIFACTS_DIR: "parameterized/weekly-portals-ss-set-agg"

w_portals_selfservice_set_agg_build:
  extends: .build
  variables:
    DDL_DIR: "$WEEKLY_PORTALS_SELFSERVICE_SET_AGG_DIR/ddl"
    HQL_DIR: "$WEEKLY_PORTALS_SELFSERVICE_SET_AGG_DIR/hql"
    POST_PROCESSING_SCRIPTS: >
      $JOB_TEMPLATE_DIR/lambda/cmn-post-processors/pass_additional_params_as_step_arg_post_processor.py
    <<: *w_portals_selfservice_set_agg_variables

#PROD
w_portals_selfservice_set_agg_plan_prod:
  extends: .plan_prod
  variables:
    <<: *w_portals_selfservice_set_agg_variables
  dependencies:
    - w_portals_selfservice_set_agg_build

w_portals_selfservice_set_agg_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *w_portals_selfservice_set_agg_variables
  dependencies:
    - w_portals_selfservice_set_agg_build
    - w_portals_selfservice_set_agg_plan_prod

w_portals_selfservice_set_agg_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *w_portals_selfservice_set_agg_variables
  dependencies:
    - w_portals_selfservice_set_agg_build

# STG
w_portals_selfservice_set_agg_plan_stg:
  extends: .plan_stg
  variables:
    <<: *w_portals_selfservice_set_agg_variables
  dependencies:
    - w_portals_selfservice_set_agg_build

w_portals_selfservice_set_agg_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *w_portals_selfservice_set_agg_variables
  dependencies:
    - w_portals_selfservice_set_agg_build
    - w_portals_selfservice_set_agg_plan_stg

w_portals_selfservice_set_agg_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *w_portals_selfservice_set_agg_variables
  dependencies:
    - w_portals_selfservice_set_agg_build
