#!/usr/bin/env groovy
@Library('jenkins-util') _    // don't miss the '_' at the end of the line
PIDeliveryPipeline {
    azkabanProjectName = "asp_daily_performance_email_aws_idm" // required
    azkabanEnv = 'prod' // optional, default to dev
    azkabanProjectDesc = "Downloads daily IDManagement Page Load Dashboard and emails to a distribution list" // required
    azkabanProjectOwner = 'jdutczak' // required, put your AD login here
    azkabanPlatform = 'ASP'  // required
    azkabanEscalation = 'Marjorie Truitt' // required, one of ['Andrew Ngeow', 'Yong Liu', 'Ty Prinkki', 'Marjorie Truitt', 'Micheal Baldino', 'Nate Vogel']
    azkabanSLA = 'Critical - Immediate Response' // required, one of ['Optional - Next Day', 'Important - Within 12 hrs', 'Critical - Immediate Response']
    azkabanFlowRun=[] // not implemented, could have loop here too
    azkabanProdFlowSchedule=[]     // optional, a groovy map, leave it out or empty ([]) if you don't want to override production schedule
    gitDir='util/tableau_email_dist/asp_daily_aws/idm_perf_daily'  // the sub dir where your project dir is
}
