# BHN Residential Events Denormalization and Calculation azkaban job
type=command
dependencies=03_bhn_residential_events_init

command=whoami

command.1=pig -f -useHCatalog src/bhn_residential_denormalize.pig -param TMP_db=${TMP_db} -param LKP_db=${LKP_db} -param ENV=${ENVIRONMENT}
command.2=pig -f -useHCatalog src/bhn_residential_calc.pig -param TMP_db=${TMP_db} -param LKP_db=${LKP_db} -param ENV=${ENVIRONMENT}
