.w_billing_agg_variables: &w_billing_agg_variables
  JOB_NAME: "parameterized-weekly-billing-agg"
  W_BILLING_AGG_DIR: "parameterized/weekly-billing-agg"
  ARTIFACTS_DIR: "parameterized/weekly-billing-agg/artifacts"
  TERRAFORM_DIR: "parameterized/weekly-billing-agg/terraform"
  SCRIPTS_DIR: "parameterized/weekly-billing-agg/scripts"
  S3_ARTIFACTS_DIR: "parameterized/weekly-billing-agg"

w_billing_agg_build:
  extends: .build
  variables:
    DDL_DIR: "$W_BILLING_AGG_DIR/ddl"
    HQL_DIR: "$W_BILLING_AGG_DIR/hql"
    <<: *w_billing_agg_variables

#PROD
w_billing_agg_plan_prod:
  extends: .plan_prod
  variables:
    <<: *w_billing_agg_variables
  dependencies:
    - w_billing_agg_build

w_billing_agg_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *w_billing_agg_variables
  dependencies:
    - w_billing_agg_build
    - w_billing_agg_plan_prod

w_billing_agg_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *w_billing_agg_variables
  dependencies:
    - w_billing_agg_build

#STG
w_billing_agg_plan_stg:
  extends: .plan_stg
  variables:
    <<: *w_billing_agg_variables
  dependencies:
    - w_billing_agg_build

w_billing_agg_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *w_billing_agg_variables
  dependencies:
    - w_billing_agg_build
    - w_billing_agg_plan_stg

w_billing_agg_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *w_billing_agg_variables
  dependencies:
    - w_billing_agg_build
