set hive.vectorized.execution.enabled = false;

USE prod;

DROP TABLE IF EXISTS ${env:TMP_db}.asp_counts_daily_counts_households_columns;
CREATE TEMPORARY TABLE ${env:TMP_db}.asp_counts_daily_counts_households_columns AS
    SELECT
        'L-CHTR' as company,
        SIZE(COLLECT_SET(IF( message__category = 'Page View'  AND state__view__current_page__name = 'home-authenticated' , visit__account__enc_account_number, Null))) AS auth_homepage_page_views_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS set_up_auto_payment_failures_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS set_up_auto_payment_successes_households,
        SIZE(COLLECT_SET(IF( state__content__details__episode_title RLIKE '.*bp:autopay.*', visit__account__enc_account_number, Null))) AS autopay_is_enabled_households,
        SIZE(COLLECT_SET(IF( state__content__details__episode_title RLIKE '.*bp:no-autopay.*', visit__account__enc_account_number, Null))) AS autopay_is_not_enabled_households,
        SIZE(COLLECT_SET(IF( state__content__details__episode_title RLIKE '.*pastDue-no.*', visit__account__enc_account_number, Null))) AS bill_status_past_due_no_households,
        SIZE(COLLECT_SET(IF( state__content__details__episode_title RLIKE '.*pastDue-yes.*', visit__account__enc_account_number, Null))) AS bill_status_past_due_yes_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS cancelled_service_appointments_households,
        SIZE(COLLECT_SET(IF( message__category = 'Page View'  AND LOWER(message__name) = 'support.category.general.contact-us' , visit__account__enc_account_number, Null))) AS contact_us_page_views_households,
        SIZE(COLLECT_SET(IF( visit__settings['post_prop48'] IN ('https://www.spectrum.net/my-account/create/#/account-info?SourceApp=MSA'), visit__account__enc_account_number, Null))) AS create_username_referred_from_msa_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS equipment_page_views_households,
        SIZE(COLLECT_SET(IF( message__category = 'Page View'  AND message__name = 'Reset-Equipment-Internet-Failure' , visit__account__enc_account_number, Null))) AS internet_equipment_reset_flow_failures_households,
        SIZE(COLLECT_SET(IF( message__category = 'Page View'  AND message__name = 'reset-equipment-tv-failure' , visit__account__enc_account_number, Null))) AS tv_equipment_reset_flow_failures_households,
        SIZE(COLLECT_SET(IF( message__category = 'Page View'  AND message__name = 'Reset-Equipment-Voice-Failure' , visit__account__enc_account_number, Null))) AS voice_equipment_reset_flow_failures_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND message__name = 'equip.internet.troubleshoot.reset-equip.start' , visit__account__enc_account_number, Null))) AS internet_equipment_reset_flow_starts_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND message__name = 'equip.tv.troubleshoot.reset-equip.start' , visit__account__enc_account_number, Null))) AS tv_equipment_reset_flow_starts_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND message__name = 'equip.voice.troubleshoot.reset-equip.start' , visit__account__enc_account_number, Null))) AS voice_equipment_reset_flow_starts_households,
        SIZE(COLLECT_SET(IF( message__category = 'Page View'  AND message__name = 'Reset-Equipment-Internet-Success' , visit__account__enc_account_number, Null))) AS internet_equipment_reset_flow_successes_households,
        SIZE(COLLECT_SET(IF( message__category = 'Page View'  AND message__name = 'reset-equipment-tv-success' , visit__account__enc_account_number, Null))) AS tv_equipment_reset_flow_successes_households,
        SIZE(COLLECT_SET(IF( message__category = 'Page View'  AND message__name = 'Reset-Equipment-Voice-Success' , visit__account__enc_account_number, Null))) AS voice_equipment_reset_flow_successes_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-manageaccount-accountsummary') , visit__account__enc_account_number, Null))) AS footer_manageaccount_account_summary_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-getsupport-accountsupport') , visit__account__enc_account_number, Null))) AS footer_getsupport_acct_support_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-manageaccount-billing') , visit__account__enc_account_number, Null))) AS footer_manageaccount_billing_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-legal-californiaprivacyrights') , visit__account__enc_account_number, Null))) AS footer_legal_ca_privacy_rights_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-contact-contactus') , visit__account__enc_account_number, Null))) AS footer_contactus_contact_us_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-disabilityassistance') , visit__account__enc_account_number, Null))) AS footer_disability_assistance_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-social-facebook') , visit__account__enc_account_number, Null))) AS footer_social_facebook_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-contact-findstore') , visit__account__enc_account_number, Null))) AS footer_contactus_find_spectrum_store_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) = LOWER('footer-contact-websiteFeedback') , visit__account__enc_account_number, Null))) AS footer_contactus_give_website_feedback_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-legal-gotoassist') , visit__account__enc_account_number, Null))) AS footer_legal_go_to_assist_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-watchtv-guide') , visit__account__enc_account_number, Null))) AS footer_watchtv_guide_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-social-instagram') , visit__account__enc_account_number, Null))) AS footer_social_instagram_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-getsupport-internet') , visit__account__enc_account_number, Null))) AS footer_getsupport_internet_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-manageaccount-internet') , visit__account__enc_account_number, Null))) AS footer_manageaccount_internet_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-watchtv-livetv') , visit__account__enc_account_number, Null))) AS footer_watchtv_live_tv_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) = LOWER('footer-manageAccount-mobile') , visit__account__enc_account_number, Null))) AS footer_manageaccount_mobile_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-watchtv-mylibrary') , visit__account__enc_account_number, Null))) AS footer_watchtv_my_library_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-watchtv-ondemand') , visit__account__enc_account_number, Null))) AS footer_watchtv_on_demand_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-legal-policies') , visit__account__enc_account_number, Null))) AS footer_legal_policies_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-legal-privacyrights') , visit__account__enc_account_number, Null))) AS footer_legal_privacy_rights_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-manageaccount-settings') , visit__account__enc_account_number, Null))) AS footer_manageaccount_settings_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-getsupport-supporthome') , visit__account__enc_account_number, Null))) AS footer_getsupport_support_home_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-getsupport-tv') , visit__account__enc_account_number, Null))) AS footer_getsupport_tv_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-manageaccount-tv') , visit__account__enc_account_number, Null))) AS footer_manageaccount_tv_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-watchtv-dvr') , visit__account__enc_account_number, Null))) AS footer_watchtv_dvr_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-social-twitter') , visit__account__enc_account_number, Null))) AS footer_social_twitter_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-getsupport-voice') , visit__account__enc_account_number, Null))) AS footer_getsupport_voice_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-manageaccount-voice') , visit__account__enc_account_number, Null))) AS footer_manageaccount_voice_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-contact-weatheroutage') , visit__account__enc_account_number, Null))) AS footer_contactus_weather_outage_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('footer-social-youtube') , visit__account__enc_account_number, Null))) AS footer_social_youtube_households,
        SIZE(COLLECT_SET(IF( visit__settings['post_prop48'] IN ('https://www.spectrum.net/forgot/#/password?SourceApp=MSA'), visit__account__enc_account_number, Null))) AS forgot_password_referred_from_msaID/Auth_households,
        SIZE(COLLECT_SET(IF( visit__settings['post_prop48'] IN ('https://www.spectrum.net/forgot/#/username?SourceApp=MSA'), visit__account__enc_account_number, Null))) AS forgot_username_referred_from_msa_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('hamburger-closesidenav') , visit__account__enc_account_number, Null))) AS hamburger_closesidenav_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('hamburger-createusername') , visit__account__enc_account_number, Null))) AS hamburger_create_username_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('hamburger-email') , visit__account__enc_account_number, Null))) AS hamburger_email_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('hamburger-getsupport') , visit__account__enc_account_number, Null))) AS hamburger_get_support_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('hamburger-manageaccount') , visit__account__enc_account_number, Null))) AS hamburger_manage_account_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('hamburger-signin') , visit__account__enc_account_number, Null))) AS hamburger_signin_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('hamburger-signout') , visit__account__enc_account_number, Null))) AS hamburger_signout_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('hamburger-voice') , visit__account__enc_account_number, Null))) AS hamburger_voice_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('hamburger-watchtv') , visit__account__enc_account_number, Null))) AS hamburger_watch_tv_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS iva_opens_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('localnav-accountsummary') , visit__account__enc_account_number, Null))) AS localnav_acct_summary_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('localnav-billing') , visit__account__enc_account_number, Null))) AS localnav_billing_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('localnav-internet') , visit__account__enc_account_number, Null))) AS localnav_internet_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('localnav-settings') , visit__account__enc_account_number, Null))) AS localnav_settings_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('localnav-tv') , visit__account__enc_account_number, Null))) AS localnav_tv_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('localnav-voice') , visit__account__enc_account_number, Null))) AS localnav_voice_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS login_attempts_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS manual_reset_failures_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS manual_reset_starts_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS manual_reset_success_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS manual_troubleshoot_page_views_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS internet_modem_reset_failures_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS voice_modem_reset_failures_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS internet_modem_reset_successes_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS voice_modem_reset_successes_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS internet_modem_router_reset_starts_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS voice_modem_router_reset_starts_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS one_time_payment_failures_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS one_time_payment_starts_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS one_time_payment_successes_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS otp_with_autopay_failures_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS otp_with_autopay_successes_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS os_all_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS os_android_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS os_ios_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS os_ios_or_android_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS os_not_ios_or_android_households,
        SIZE(COLLECT_SET(IF( state__content__details__episode_title RLIKE '.*pl:pl-yes.*', visit__account__enc_account_number, Null))) AS paperless_billing_is_enabled_households,
        SIZE(COLLECT_SET(IF( state__content__details__episode_title RLIKE '.*pl:pl-no.*', visit__account__enc_account_number, Null))) AS paperless_billing_is_not_enabled_households,
        SIZE(COLLECT_SET(IF( (( message__category = 'Page View'  AND state__view__current_page__name IN('Reset-1.bam','Reset-1.btm')) OR (message__category = 'Page View' AND state__view__current_page__name = 'Reset-1.nbtm')), visit__account__enc_account_number, Null))) AS password_reset_attempts_households,
        SIZE(COLLECT_SET(IF( ((message__category = 'Page View' AND state__view__current_page__name IN ('Reset-final.bam','Reset-final.btm')) Or (message__category = 'Page View' AND state__view__current_page__name = 'Reset-final.nbtm')), visit__account__enc_account_number, Null))) AS password_reset_successes_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS refresh_set_top_box_failures_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS refresh_set_top_box_requests_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS rescheduled_service_appointments_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS internet_router_reset_failures_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS voice_router_reset_failures_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS internet_router_reset_successes_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS voice_router_reset_successes_households,
        SIZE(COLLECT_SET(IF( state__view__current_page__search_text IS NOT NULL, visit__account__enc_account_number, Null))) AS search_action_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS search_results_clicked_households,
        SIZE(COLLECT_SET(IF( TRUE, visit__account__enc_account_number, Null))) AS site_unique_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS site_unique_auth_households,
        SIZE(COLLECT_SET(IF( message__category = 'Page View'  AND LOWER(state__view__current_page__section) = 'support' , visit__account__enc_account_number, Null))) AS support_section_page_views_households,
        SIZE(COLLECT_SET(IF( message__category = 'Page View'  AND state__view__current_page__name = 'home-unauth' , visit__account__enc_account_number, Null))) AS unauth_homepage_page_views_households,
        SIZE(COLLECT_SET(IF( ((message__category = 'Page View' AND state__view__current_page__name IN('Recover-1.btm','Recover-1.bam')) Or (message__category = 'Page View' AND state__view__current_page__name = 'Recover-1.nbtm' AND state__view__current_page__name NOT IN  ('Recover-noID.nbtm'))), visit__account__enc_account_number, Null))) AS username_recovery_attempts_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('utilitynav-email') , visit__account__enc_account_number, Null))) AS utilitynav_email_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('utilitynav-support') , visit__account__enc_account_number, Null))) AS utilitynav_support_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('utilitynav-voice') , visit__account__enc_account_number, Null))) AS utilitynav_voice_households,
        SIZE(COLLECT_SET(IF( ((message__category = 'Custom Link') AND message__name IN('View Current Bill','Statement','View Statement','pay-bill.billing-statement-download') OR (message__category = 'Custom Link' AND message__name IN('pay-bill.view-statements') AND visit__settings['post_prop26'] IS NOT NULL)), visit__account__enc_account_number, Null))) AS view_online_statement_households,
        SIZE(COLLECT_SET(IF( FALSE, visit__account__enc_account_number, Null))) AS webmail_views_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('internet') , visit__account__enc_account_number, Null))) AS yourservicesequip_internet_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('mobile') , visit__account__enc_account_number, Null))) AS yourservicesequip_mobile_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('tv') , visit__account__enc_account_number, Null))) AS yourservicesequip_tv_households,
        SIZE(COLLECT_SET(IF( message__category = 'Custom Link'  AND LOWER(message__name) IN ('voice') , visit__account__enc_account_number, Null))) AS yourservicesequip_voice_households,
        SIZE(COLLECT_SET(IF( message__category = 'Page View'  AND (LOWER(message__name) = LOWER('Wait-15-Error-Modal-TV') OR LOWER(message__name) = LOWER('Wait-15-Error-Modal-Internet') OR LOWER(message__name) = LOWER('Wait-15-Error-Modal-Voice')) , visit__account__enc_account_number, Null))) AS equipment_resets_too_many_resets_modal_all_households,
        SIZE(COLLECT_SET(IF( message__category = 'Page View'  AND LOWER(message__name) = LOWER('Wait-15-Error-Modal-Internet') , visit__account__enc_account_number, Null))) AS equipment_resets_too_many_resets_modal_internet_households,
        SIZE(COLLECT_SET(IF( message__category = 'Page View'  AND LOWER(message__name) = LOWER('Wait-15-Error-Modal-TV') , visit__account__enc_account_number, Null))) AS equipment_resets_too_many_resets_modal_tv_households,
        SIZE(COLLECT_SET(IF( message__category = 'Page View'  AND LOWER(message__name) = LOWER('Wait-15-Error-Modal-Voice') , visit__account__enc_account_number, Null))) AS equipment_resets_too_many_resets_modal_voice_households,
        'asp' AS platform,
        'resi' AS domain,
        
        epoch_converter(cast(message__timestamp * 1000 as bigint),'America/Denver') as date_denver
    FROM asp_v_net_events
         
    WHERE (partition_date >= '${env:START_DATE}'
       AND partition_date <  '${env:END_DATE}')
    GROUP BY
        epoch_converter(cast(message__timestamp * 1000 as bigint),'America/Denver'),
        
        'L-CHTR'
    ;
INSERT OVERWRITE TABLE prod.asp_counts_daily
PARTITION(unit,platform,domain,company,date_denver,source_table)

    SELECT  value,
            metric,
            
            'households',
            'asp',
            'resi',
            company,
            date_denver,
            'asp_v_net_events'
    FROM (SELECT  company,
                  date_denver,
                  
                  MAP(

                      'auth_homepage_page_views|Authenticated Homepage Page Views|Spectrum.net_adobe||', auth_homepage_page_views_households,
                      'set_up_auto_payment_failures|Auto Pay Enrollment Failures|Spectrum.net_adobe||', set_up_auto_payment_failures_households,
                      'set_up_auto_payment_successes|Auto Pay Enrollment Successes|Spectrum.net_adobe||', set_up_auto_payment_successes_households,
                      'autopay_is_enabled|Autopay Is Enabled|Spectrum.net_adobe||', autopay_is_enabled_households,
                      'autopay_is_not_enabled|Autopay Is Not Enabled|Spectrum.net_adobe||', autopay_is_not_enabled_households,
                      'bill_status_past_due_no|Bill Status Past Due No|Spectrum.net_adobe||', bill_status_past_due_no_households,
                      'bill_status_past_due_yes|Bill Status Past Due Yes|Spectrum.net_adobe||', bill_status_past_due_yes_households,
                      'cancelled_service_appointments|Cancelled Service Appointments|Spectrum.net_adobe||', cancelled_service_appointments_households,
                      'contact_us_page_views|Contact Us Page Views|Spectrum.net_adobe||', contact_us_page_views_households,
                      'create_username_referred_from_msa|Create Username Referral From MySpectrum App|Spectrum.net_adobe||', create_username_referred_from_msa_households,
                      'equipment_page_views|Equipment Flow Page Views|Spectrum.net_adobe||', equipment_page_views_households,
                      'internet_equipment_reset_flow_failures|Equipment Reset Flow Failures Internet|Spectrum.net_adobe||', internet_equipment_reset_flow_failures_households,
                      'tv_equipment_reset_flow_failures|Equipment Reset Flow Failures TV|Spectrum.net_adobe||', tv_equipment_reset_flow_failures_households,
                      'voice_equipment_reset_flow_failures|Equipment Reset Flow Failures Voice|Spectrum.net_adobe||', voice_equipment_reset_flow_failures_households,
                      'internet_equipment_reset_flow_starts|Equipment Reset Flow Starts Internet|Spectrum.net_adobe||', internet_equipment_reset_flow_starts_households,
                      'tv_equipment_reset_flow_starts|Equipment Reset Flow Starts TV|Spectrum.net_adobe||', tv_equipment_reset_flow_starts_households,
                      'voice_equipment_reset_flow_starts|Equipment Reset Flow Starts Voice|Spectrum.net_adobe||', voice_equipment_reset_flow_starts_households,
                      'internet_equipment_reset_flow_successes|Equipment Reset Flow Successes Internet|Spectrum.net_adobe||', internet_equipment_reset_flow_successes_households,
                      'tv_equipment_reset_flow_successes|Equipment Reset Flow Successes TV|Spectrum.net_adobe||', tv_equipment_reset_flow_successes_households,
                      'voice_equipment_reset_flow_successes|Equipment Reset Flow Successes Voice|Spectrum.net_adobe||', voice_equipment_reset_flow_successes_households,
                      'footer_manageaccount_account_summary|Footer - Account Summary|Spectrum.net_adobe||', footer_manageaccount_account_summary_households,
                      'footer_getsupport_acct_support|Footer - Acct Support|Spectrum.net_adobe||', footer_getsupport_acct_support_households,
                      'footer_manageaccount_billing|Footer - Billing|Spectrum.net_adobe||', footer_manageaccount_billing_households,
                      'footer_legal_ca_privacy_rights|Footer - CA Privacy Rights|Spectrum.net_adobe||', footer_legal_ca_privacy_rights_households,
                      'footer_contactus_contact_us|Footer - Contact Us|Spectrum.net_adobe||', footer_contactus_contact_us_households,
                      'footer_disability_assistance|Footer - Disability Assistance|Spectrum.net_adobe||', footer_disability_assistance_households,
                      'footer_social_facebook|Footer - Facebook|Spectrum.net_adobe||', footer_social_facebook_households,
                      'footer_contactus_find_spectrum_store|Footer - Find a Spectrum Store|Spectrum.net_adobe||', footer_contactus_find_spectrum_store_households,
                      'footer_contactus_give_website_feedback|Footer - Give Website Feedback |Spectrum.net_adobe||', footer_contactus_give_website_feedback_households,
                      'footer_legal_go_to_assist|Footer - Go to Assist|Spectrum.net_adobe||', footer_legal_go_to_assist_households,
                      'footer_watchtv_guide|Footer - Guide|Spectrum.net_adobe||', footer_watchtv_guide_households,
                      'footer_social_instagram|Footer - Instagram|Spectrum.net_adobe||', footer_social_instagram_households,
                      'footer_getsupport_internet|Footer - Internet|Spectrum.net_adobe||', footer_getsupport_internet_households,
                      'footer_manageaccount_internet|Footer - Internet|Spectrum.net_adobe||', footer_manageaccount_internet_households,
                      'footer_watchtv_live_tv|Footer - Live TV|Spectrum.net_adobe||', footer_watchtv_live_tv_households,
                      'footer_manageaccount_mobile|Footer - Mobile|Spectrum.net_adobe||', footer_manageaccount_mobile_households,
                      'footer_watchtv_my_library|Footer - My Library|Spectrum.net_adobe||', footer_watchtv_my_library_households,
                      'footer_watchtv_on_demand|Footer - On Demand|Spectrum.net_adobe||', footer_watchtv_on_demand_households,
                      'footer_legal_policies|Footer - Policies|Spectrum.net_adobe||', footer_legal_policies_households,
                      'footer_legal_privacy_rights|Footer - Privacy Rights|Spectrum.net_adobe||', footer_legal_privacy_rights_households,
                      'footer_manageaccount_settings|Footer - Settings|Spectrum.net_adobe||', footer_manageaccount_settings_households,
                      'footer_getsupport_support_home|Footer - Support Home|Spectrum.net_adobe||', footer_getsupport_support_home_households,
                      'footer_getsupport_tv|Footer - TV|Spectrum.net_adobe||', footer_getsupport_tv_households,
                      'footer_manageaccount_tv|Footer - TV|Spectrum.net_adobe||', footer_manageaccount_tv_households,
                      'footer_watchtv_dvr|Footer - TV DVR|Spectrum.net_adobe||', footer_watchtv_dvr_households,
                      'footer_social_twitter|Footer - Twitter|Spectrum.net_adobe||', footer_social_twitter_households,
                      'footer_getsupport_voice|Footer - Voice|Spectrum.net_adobe||', footer_getsupport_voice_households,
                      'footer_manageaccount_voice|Footer - Voice|Spectrum.net_adobe||', footer_manageaccount_voice_households,
                      'footer_contactus_weather_outage|Footer - Weather Outage|Spectrum.net_adobe||', footer_contactus_weather_outage_households,
                      'footer_social_youtube|Footer - Youtube|Spectrum.net_adobe||', footer_social_youtube_households,
                      'forgot_password_referred_from_msa|Forgot Password Referral From MySpectrum App|Spectrum.net_adobe|ID/Auth|', forgot_password_referred_from_msaID/Auth_households,
                      'forgot_username_referred_from_msa|Forgot Username Referral From MySpectrum App|Spectrum.net_adobe||', forgot_username_referred_from_msa_households,
                      'hamburger_closesidenav|Hamburger - closeSideNav|Spectrum.net_adobe||', hamburger_closesidenav_households,
                      'hamburger_create_username|Hamburger - Create Username|Spectrum.net_adobe||', hamburger_create_username_households,
                      'hamburger_email|Hamburger - Email|Spectrum.net_adobe||', hamburger_email_households,
                      'hamburger_get_support|Hamburger - Get Support|Spectrum.net_adobe||', hamburger_get_support_households,
                      'hamburger_manage_account|Hamburger - Manage Account|Spectrum.net_adobe||', hamburger_manage_account_households,
                      'hamburger_signin|Hamburger - Sign In|Spectrum.net_adobe||', hamburger_signin_households,
                      'hamburger_signout|Hamburger - Signout|Spectrum.net_adobe||', hamburger_signout_households,
                      'hamburger_voice|Hamburger - Voice|Spectrum.net_adobe||', hamburger_voice_households,
                      'hamburger_watch_tv|Hamburger - Watch TV|Spectrum.net_adobe||', hamburger_watch_tv_households,
                      'iva_opens|IVA Opens|Spectrum.net_adobe||', iva_opens_households,
                      'localnav_acct_summary|LocalNav - Account Summary|Spectrum.net_adobe||', localnav_acct_summary_households,
                      'localnav_billing|LocalNav - Billing|Spectrum.net_adobe||', localnav_billing_households,
                      'localnav_internet|LocalNav - Internet|Spectrum.net_adobe||', localnav_internet_households,
                      'localnav_settings|LocalNav - Settings|Spectrum.net_adobe||', localnav_settings_households,
                      'localnav_tv|LocalNav - TV|Spectrum.net_adobe||', localnav_tv_households,
                      'localnav_voice|LocalNav - Voice|Spectrum.net_adobe||', localnav_voice_households,
                      'login_attempts|Login Attempts|Spectrum.net_adobe||', login_attempts_households,
                      'manual_reset_failures|Manual Reset Failures|Spectrum.net_adobe||', manual_reset_failures_households,
                      'manual_reset_starts|Manual Reset Starts|Spectrum.net_adobe||', manual_reset_starts_households,
                      'manual_reset_success|Manual Reset Success|Spectrum.net_adobe||', manual_reset_success_households,
                      'manual_troubleshoot_page_views|Manual Troubleshooting Page Views|Spectrum.net_adobe||', manual_troubleshoot_page_views_households,
                      'internet_modem_reset_failures|Modem Reset Failures Internet|Spectrum.net_adobe||', internet_modem_reset_failures_households,
                      'voice_modem_reset_failures|Modem Reset Failures Voice|Spectrum.net_adobe||', voice_modem_reset_failures_households,
                      'internet_modem_reset_successes|Modem Reset Successes Internet|Spectrum.net_adobe||', internet_modem_reset_successes_households,
                      'voice_modem_reset_successes|Modem Reset Successes Voice|Spectrum.net_adobe||', voice_modem_reset_successes_households,
                      'internet_modem_router_reset_starts|Modem Router Reset Starts Internet|Spectrum.net_adobe||', internet_modem_router_reset_starts_households,
                      'voice_modem_router_reset_starts|Modem Router Reset Starts Voice|Spectrum.net_adobe||', voice_modem_router_reset_starts_households,
                      'one_time_payment_failures|One Time Payment Failures|Spectrum.net_adobe||', one_time_payment_failures_households,
                      'one_time_payment_starts|One Time Payment Starts|Spectrum.net_adobe||', one_time_payment_starts_households,
                      'one_time_payment_successes|One Time Payment Successes|Spectrum.net_adobe||', one_time_payment_successes_households,
                      'otp_with_autopay_failures|One Time Payment with Auto Pay Enrollment Failures|Spectrum.net_adobe||', otp_with_autopay_failures_households,
                      'otp_with_autopay_successes|One Time Payment with Auto Pay Enrollment Successes|Spectrum.net_adobe||', otp_with_autopay_successes_households,
                      'os_all|Operating System - All |Spectrum.net_adobe||', os_all_households,
                      'os_android|Operating System - Android|Spectrum.net_adobe||', os_android_households,
                      'os_ios|Operating System - iOS|Spectrum.net_adobe||', os_ios_households,
                      'os_ios_or_android|Operating System - iOS or Android|Spectrum.net_adobe||', os_ios_or_android_households,
                      'os_not_ios_or_android|Operating System - Not iOS or Android|Spectrum.net_adobe||', os_not_ios_or_android_households,
                      'paperless_billing_is_enabled|Paperless Billing is Enabled|Spectrum.net_adobe||', paperless_billing_is_enabled_households,
                      'paperless_billing_is_not_enabled|Paperless Billing Is Not Enabled|Spectrum.net_adobe||', paperless_billing_is_not_enabled_households,
                      'password_reset_attempts|Password Reset Attempts|Spectrum.net_adobe||', password_reset_attempts_households,
                      'password_reset_successes|Password Reset Successes|Spectrum.net_adobe||', password_reset_successes_households,
                      'refresh_set_top_box_failures|Refresh Digital Receivers Failures|Spectrum.net_adobe||', refresh_set_top_box_failures_households,
                      'refresh_set_top_box_requests|Refresh Digital Receivers Requests|Spectrum.net_adobe||', refresh_set_top_box_requests_households,
                      'rescheduled_service_appointments|Rescheduled Service Appointments|Spectrum.net_adobe||', rescheduled_service_appointments_households,
                      'internet_router_reset_failures|Router Reset Failures Internet|Spectrum.net_adobe||', internet_router_reset_failures_households,
                      'voice_router_reset_failures|Router Reset Failures Voice|Spectrum.net_adobe||', voice_router_reset_failures_households,
                      'internet_router_reset_successes|Router Reset Successes Internet|Spectrum.net_adobe||', internet_router_reset_successes_households,
                      'voice_router_reset_successes|Router Reset Successes Voice|Spectrum.net_adobe||', voice_router_reset_successes_households,
                      'search_action|Search Action|Spectrum.net_adobe||', search_action_households,
                      'search_results_clicked|Search Results Clicked|Spectrum.net_adobe||', search_results_clicked_households,
                      'site_unique|Site Unique Values|Spectrum.net_adobe||', site_unique_households,
                      'site_unique_auth|Site Unique Values Authenticated|Spectrum.net_adobe||', site_unique_auth_households,
                      'support_section_page_views|Support Section Page Views|Spectrum.net_adobe||', support_section_page_views_households,
                      'unauth_homepage_page_views|Unauthenticated Homepage Page Views|Spectrum.net_adobe||', unauth_homepage_page_views_households,
                      'username_recovery_attempts|Username Recovery Attempts|Spectrum.net_adobe||', username_recovery_attempts_households,
                      'utilitynav_email|Utility Navigation - Email|Spectrum.net_adobe||', utilitynav_email_households,
                      'utilitynav_support|Utility Navigation - Support|Spectrum.net_adobe||', utilitynav_support_households,
                      'utilitynav_voice|Utility Navigation - Voice|Spectrum.net_adobe||', utilitynav_voice_households,
                      'view_online_statement|View Online Statement|Spectrum.net_adobe||', view_online_statement_households,
                      'webmail_views|Webmail Views|Spectrum.net_adobe||', webmail_views_households,
                      'yourservicesequip_internet|Your Services Equipment - Internet|Spectrum.net_adobe||', yourservicesequip_internet_households,
                      'yourservicesequip_mobile|Your Services Equipment - Mobile|Spectrum.net_adobe||', yourservicesequip_mobile_households,
                      'yourservicesequip_tv|Your Services Equipment - TV|Spectrum.net_adobe||', yourservicesequip_tv_households,
                      'yourservicesequip_voice|Your Services Equipment - Voice|Spectrum.net_adobe||', yourservicesequip_voice_households,
                      'equipment_resets_too_many_resets_modal_all|Equipment Resets Too Many Resets Modal All|Spectrum.net_adobe||', equipment_resets_too_many_resets_modal_all_households,
                      'equipment_resets_too_many_resets_modal_internet|Equipment Resets Too Many Resets Modal Internet|Spectrum.net_adobe||', equipment_resets_too_many_resets_modal_internet_households,
                      'equipment_resets_too_many_resets_modal_tv|Equipment Resets Too Many Resets Modal TV|Spectrum.net_adobe||', equipment_resets_too_many_resets_modal_tv_households,
                      'equipment_resets_too_many_resets_modal_voice|Equipment Resets Too Many Resets Modal Voice|Spectrum.net_adobe||', equipment_resets_too_many_resets_modal_voice_households
                  ) as map_column
          FROM ${env:TMP_db}.asp_counts_daily_counts_households_columns
        ) as derived_table
    LATERAL VIEW EXPLODE (map_column) exploded_table AS metric, value
;
