.d_billing_agg_variables: &d_billing_agg_variables
  JOB_NAME: "parameterized-daily-billing-agg"
  DAILY_BILLING_AGG_DIR: "parameterized/daily-billing-agg"
  ARTIFACTS_DIR: "parameterized/daily-billing-agg/artifacts"
  TERRAFORM_DIR: "parameterized/daily-billing-agg/terraform"
  SCRIPTS_DIR: "parameterized/daily-billing-agg/scripts"
  S3_ARTIFACTS_DIR: "parameterized/daily-billing-agg"

d_billing_agg_build:
  extends: .build
  variables:
    DDL_DIR: "$DAILY_BILLING_AGG_DIR/ddl"
    HQL_DIR: "$DAILY_BILLING_AGG_DIR/hql"
    <<: *d_billing_agg_variables

#PROD
d_billing_agg_plan_prod:
  extends: .plan_prod
  variables:
    <<: *d_billing_agg_variables
  dependencies:
    - d_billing_agg_build

d_billing_agg_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *d_billing_agg_variables
  dependencies:
    - d_billing_agg_build
    - d_billing_agg_plan_prod

d_billing_agg_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *d_billing_agg_variables
  dependencies:
    - d_billing_agg_build

#STG
d_billing_agg_plan_stg:
  extends: .plan_stg
  variables:
    <<: *d_billing_agg_variables
  dependencies:
    - d_billing_agg_build

d_billing_agg_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *d_billing_agg_variables
  dependencies:
    - d_billing_agg_build
    - d_billing_agg_plan_stg

d_billing_agg_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *d_billing_agg_variables
  dependencies:
    - d_billing_agg_build
