# Daily Metric Agg Portals - kick off subsequent aggs with Groovy
# this allows the set aggs to be as fresh as possible
type=Groovy
dependencies=02_portals_selfservice_metric_agg_process_daily
groovy.command.1=println '#### This job starts the set of Portals set agg jobs (daily, fiscal monthly, monthly, and weekly) ####'
groovy.command.2=import azkaban.executor.*
groovy.command.3=def paramsToPass = ["env.RUN_DATE": "${env.RUN_DATE}", "env.job_started_by_exec": "${azkaban.link.execution.url}", "env.job_started_by_project_flow": "${azkaban.link.workflow.url}" ]
groovy.command.4=if ( '${ENVIRONMENT}' == 'prod' || '${isReprocessing}' == '1') { println 'Processing the set aggs for today.'; sleep(54321); azkaban.execute("asp_extract_parameterized_portals_ss_set_aggs", "process_all_portals_selfservice_set_aggs", paramsToPass) } else { println 'Not in the production ENVIRONMENT and not Reprocessing, so exiting without starting set agg jobs.' }
groovy.command.5=if ( '${ENVIRONMENT}' == 'prod' ) { println 'Processing the billing and quality agg for today.'; sleep(54321); azkaban.execute("asp_extract_parameterized_billing_agg","process_all_portals_billing_aggs", paramsToPass); azkaban.execute("asp_extract_dasp_quality","asp_extract_dasp_quality_end", paramsToPass); } else { println 'Not in the production ENVIRONMENT and not Reprocessing, so exiting without starting billing and quality agg jobs.' }
