#  Azkaban job
type=command
dependencies=02_cs_techmobile_set_agg_process_daily_tableset,01_param_init_pd
type=command
command=whoami

command.1=/bin/bash -c 'export execid=${azkaban.flow.execid}; echo $execid; export START_DATE="${START_DATE}"; echo $START_DATE; export END_DATE="${END_DATE}"; echo $END_DATE;  export label_date_denver="${LABEL_DATE_DENVER}"; echo $label_date_denver; export grain="${GRAIN}"; echo $grain; export ProcessTimestamp="${ProcessTimestamp}"; echo $ProcessTimestamp; export ProcessUser="${azkaban.flow.submituser}"; echo $ProcessUser; hive -f ../../../src/cs_techmobile_set_agg_instances.hql'
