#  Azkaban job
type=command
dependencies=03_cs_techmobile_set_agg_process_daily_instances,03_cs_techmobile_set_agg_process_daily_devices,03_cs_techmobile_set_agg_process_daily_accounts,03_cs_techmobile_set_agg_process_daily_visits
type=command
command=whoami

command.1=/bin/bash -c 'export execid=${azkaban.flow.execid}; echo $execid; export ProcessUser="${azkaban.flow.submituser}"; echo $ProcessUser; hive -f ../../../src/cs_techmobile_set_agg_final.hql'
