.portals_page_agg_variables: &portals_page_agg_variables
  JOB_NAME: "parameterized-portals-page-agg"
  PORTALS_PAGE_AGG_DIR: "parameterized/portals-page-agg"
  ARTIFACTS_DIR: "parameterized/portals-page-agg/artifacts"
  TERRAFORM_DIR: "parameterized/portals-page-agg/terraform"
  SCRIPTS_DIR: "parameterized/portals-page-agg/scripts"
  S3_ARTIFACTS_DIR: "parameterized/portals-page-agg"

portals_page_agg_build:
  extends: .build
  variables:
    DDL_DIR: "$PORTALS_PAGE_AGG_DIR/ddl"
    HQL_DIR: "$PORTALS_PAGE_AGG_DIR/hql"
    <<: *portals_page_agg_variables

#PROD
portals_page_agg_plan_prod:
  extends: .plan_prod
  variables:
    <<: *portals_page_agg_variables
  dependencies:
    - portals_page_agg_build

portals_page_agg_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *portals_page_agg_variables
  dependencies:
    - portals_page_agg_build
    - portals_page_agg_plan_prod

portals_page_agg_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *portals_page_agg_variables
  dependencies:
    - portals_page_agg_build

#STG
portals_page_agg_plan_stg:
  extends: .plan_stg
  variables:
    <<: *portals_page_agg_variables
  dependencies:
    - portals_page_agg_build

portals_page_agg_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *portals_page_agg_variables
  dependencies:
    - portals_page_agg_build
    - portals_page_agg_plan_stg

portals_page_agg_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *portals_page_agg_variables
  dependencies:
    - portals_page_agg_build
