#!/usr/bin/env groovy
@Library('jenkins-util') _    // don't miss the '_' at the end of the line, this is the magical library that does the, uh, 'magic'
PIDeliveryPipeline {
    azkabanProjectName = "cs_ingest_asapp_from_nifidb" // required
    azkabanEnv = 'prod' // optional, default to dev
    azkabanProjectDesc = "Ingests ASAPP data From NIFI database" // required
    azkabanProjectOwner = 'azheng' // required, put your AD login here
    azkabanPlatform = 'ASP'  // required, one of ['ASP', 'Authentication', 'Core', 'DAI', 'DynExp', 'HSD', 'Mobile', 'MVNO', 'ODN', 'Platform Ops', 'SGR', 'SpecGuide', 'Venona', 'VOD', 'Voice', 'WIFI']
    azkabanEscalation = 'Marjorie Truitt' // required, one of ['Andrew Ngeow', 'Yong Liu', 'Ty Prinkki', 'Marjorie Truitt', 'Micheal Baldino', 'Nate Vogel']
    azkabanSLA = 'Critical - Immediate Response' // required, one of ['Optional - Next Day', 'Important - Within 12 hrs', 'Critical - Immediate Response']
    azkabanFlowRun=[] // not implemented, could have loop here too
    azkabanProdFlowSchedule=[flowName:'3_asp_asapp_tables_daily_load_end', cronExpression:'0 0 18 ? * *']
    gitDir='ingest/asapp'  // the sub dir where your project dir is
}
