.w_portals_m2dot0_set_agg_variables: &w_portals_m2dot0_set_agg_variables
  JOB_NAME: "w-portals-m2dot0-set-agg"
  WEEKLY_PORTALS_M2DOT0_SET_AGG_DIR: "parameterized/weekly-portals-m2dot0-set-agg"
  ARTIFACTS_DIR: "parameterized/weekly-portals-m2dot0-set-agg/artifacts"
  TERRAFORM_DIR: "parameterized/weekly-portals-m2dot0-set-agg/terraform"
  SCRIPTS_DIR: "parameterized/weekly-portals-m2dot0-set-agg/scripts"
  S3_ARTIFACTS_DIR: "parameterized/weekly-portals-m2dot0-set-agg"

w_portals_m2dot0_set_agg_build:
  extends: .build
  variables:
    DDL_DIR: "$WEEKLY_PORTALS_M2DOT0_SET_AGG_DIR/ddl"
    HQL_DIR: "$WEEKLY_PORTALS_M2DOT0_SET_AGG_DIR/hql"
    <<: *w_portals_m2dot0_set_agg_variables

#STG
w_portals_m2dot0_set_agg_plan_stg:
  extends: .plan_stg
  variables:
    <<: *w_portals_m2dot0_set_agg_variables
  dependencies:
    - w_portals_m2dot0_set_agg_build

w_portals_m2dot0_set_agg_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *w_portals_m2dot0_set_agg_variables
  dependencies:
    - w_portals_m2dot0_set_agg_build
    - w_portals_m2dot0_set_agg_plan_stg

w_portals_m2dot0_set_agg_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *w_portals_m2dot0_set_agg_variables
  dependencies:
    - w_portals_m2dot0_set_agg_build


#PROD
w_portals_m2dot0_set_agg_plan_prod:
  extends: .plan_prod
  variables:
    <<: *w_portals_m2dot0_set_agg_variables
  dependencies:
    - w_portals_m2dot0_set_agg_build

w_portals_m2dot0_set_agg_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *w_portals_m2dot0_set_agg_variables
  dependencies:
    - w_portals_m2dot0_set_agg_build
    - w_portals_m2dot0_set_agg_plan_prod

w_portals_m2dot0_set_agg_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *w_portals_m2dot0_set_agg_variables
  dependencies:
    - w_portals_m2dot0_set_agg_build
