SET hive.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat;
SET hive.tez.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat;
set mapreduce.input.fileinputformat.split.minsize=5368709120;
set mapreduce.input.fileinputformat.split.maxsize=5368709120;


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Search Results
-- A listing of all searches that are fight related and the count of the occurences of each. 
-- Excludes a list of search texts and selected results that do not necessarily apply to the fight. 
--   19,205 Total Search Attempts

--drop table dev.brian_ppv_searches
create table dev.brian_ppv_searches as
SELECT UPPER(state__search__text) as state__search__text,--state__search__number_of_search_results,
state__search__results,
state__view__next_page__page_name,
UPPER(state__search__selected_result_name) as state__search__selected_result_name,
count(*) as occurrence_count
FROM (select message__name,
             state__view__current_page__page_name,
             message__sequence_number,
             CASE WHEN operation__operation_type = 'searchResultSelected' and state__search__text is null then LAST_VALUE(state__search__text, TRUE) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) ELSE state__search__text END as state__search__text,
             CASE WHEN operation__operation_type = 'searchResultSelected' and state__search__results is null then LAST_VALUE(state__search__results, TRUE) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) ELSE state__search__results END as state__search__results,
             state__search__selected_result_name,
             operation__operation_type,
             state__view__next_page__page_name
      from (select visit__visit_id,
                   message__name,
                   state__view__current_page__page_name,
                   message__sequence_number,
                   lag(state__search__text,1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as state__search__text,
                   lag(state__search__results,1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as state__search__results,
                   lag(state__search__selected_result_name,1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as state__search__selected_result_name,
                   lag(operation__operation_type,1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as operation__operation_type,
                   lead(state__view__current_page__page_name,1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as state__view__next_page__page_name
              from dev.brian_venona_events_view
             where visit__application_details__application_name = 'Spectrum Guide'
                   -- SG Filter
               AND partition_date_utc between '2017-08-01' and '2017-09-01'
--               AND visit__visit_id = 'fbfed499-bfc1-4e65-7d44-9930a813f503'
            ) b ) a
    where message__name = 'close'
    and state__view__current_page__page_name = 'search'
    and (upper(state__search__text) rlike ('MAY') or
         upper(state__search__text) rlike ('FLO') or
         upper(state__search__text) rlike ('MC') or
         upper(state__search__text) rlike ('CON') or
         upper(state__search__text) rlike ('BOX') or
         upper(state__search__text) rlike ('FIG') or
         upper(state__search__text) rlike ('PPV'))
    and (upper(state__search__text) not in ('1991 BOXING JE',
                                                    '2007 FLOOD',
                                                    '8 SECONDS',
                                                    'A GIRL IN A BOX',
                                                    'A MC',
                                                    'A MOTHERS FIGHT',
                                                    'ABHIOPRRRQPPVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV288',
                                                    'ABHOPPVU',
                                                    'ABOX',
                                                    'ALABAMA FLORIDA',
                                                    'ALMC',
                                                    'AMAY',
                                                    'AMC',
                                                    'AMC C',
                                                    'AMC FESTA',
                                                    'AMCC',
                                                    'AMCCCDD',
                                                    'AMCDAE',
                                                    'AMERICAN MC',
                                                    'AMMC',
                                                    'AN INCONVENIENT TRUTH',
                                                    'AN INCONVENIENT TRUTHHGGG',
                                                    'ANAACONDA',
                                                    'ANACONDA',
                                                    'ANACONDA2',
                                                    'ANDACONDA',
                                                    'ANICONDA',
                                                    'ANIMAL FIGHT',
                                                    'BBOX',
                                                    'BEFORE THE FLOOD',
                                                    'BETBOX',
                                                    'BOT FIGHTI',
                                                    'BOX A',
                                                    'BOX AZ',
                                                    'BOX T',
                                                    'BOX TR',
                                                    'BOX TRO',
                                                    'BOX TROLL',
                                                    'BOX TROLLS',
                                                    'BOXCAR',
                                                    'BOXT',
                                                    'BOXTR',
                                                    'BOXTRO',
                                                    'BOXTROLL',
                                                    'BRIAN  MCK',
                                                    'BTN FOOTBALL IN 60 WISCONSIN',
                                                    'CAKE FLO RIDA',
                                                    'CAT FIG',
                                                    'CHARTER  SPECTRUM PAY PER VIEW MAYWEATHERRRRRR',
                                                    'CHINA  MC',
                                                    'CHINESE CONN',
                                                    'CHRIS MCKENNA',
                                                    'CMC',
                                                    'COED CON',
                                                    'COED CONFIDENTIALFF',
                                                    'COMC',
                                                    'COMCA',
                                                    'CON AI',
                                                    'CON AIR',
                                                    'CON0',
                                                    'CONAN',
                                                    'CONAN G',
                                                    'CONAN OBRIEN L',
                                                    'CONANU',
                                                    'CONAR',
                                                    'CONC',
                                                    'CONCBU',
                                                    'CONCE',
                                                    'CONCER',
                                                    'CONCERT',
                                                    'CONCERTT',
                                                    'COND',
                                                    'CONDEMN',
                                                    'CONDEMNED',
                                                    'CONDO',
                                                    'CONE',
                                                    'CONE H',
                                                    'CONE HE',
                                                    'CONEF',
                                                    'CONEH',
                                                    'CONEHEA',
                                                    'CONEHEADS',
                                                    'CONEHEAE',
                                                    'CONF',
                                                    'CONFED',
                                                    'CONFEDE',
                                                    'CONFEDERATION',
                                                    'CONFESSIO',
                                                    'CONFESSION OF',
                                                    'CONFESSIONS OF',
                                                    'CONFESSIONS OF A TEENAGE',
                                                    'CONFI',
                                                    'CONFU',
                                                    'CONFUE',
                                                    'CONG',
                                                    'CONGO',
                                                    'CONGR',
                                                    'CONGRA',
                                                    'CONJ',
                                                    'CONJURI',
                                                    'CONJURING',
                                                    'CONL',
                                                    'CONNA',
                                                    'CONNECT',
                                                    'CONNELLEY',
                                                    'CONSE',
                                                    'CONSENT',
                                                    'CONSENTIN',
                                                    'CONSP',
                                                    'CONSPI',
                                                    'CRASHBOX',
                                                    'CONSPIRACY',
                                                    'CONSPIRACY T',
                                                    'CONSPIRACY TH',
                                                    'CONSPIRACY0',
                                                    'CONSPIRATORS',
                                                    'CONSPRITO',
                                                    'CONSPRITOR',
                                                    'CONSTA',
                                                    'CONSTAN',
                                                    'CONSTANTII',
                                                    'CONSTINTINE',
                                                    'CONT',
                                                    'CONTA',
                                                    'CONTACTT',
                                                    'CONTAI',
                                                    'CONTAIN',
                                                    'CONTAINTINE',
                                                    'CONTENDE',
                                                    'CONTIGON',
                                                    'CONTING CARS',
                                                    'CONTINGC',
                                                    'CONTORTION',
                                                    'CONTRAB',
                                                    'CONTRABAND',
                                                    'CONTRACTED 2',
                                                    'CONTRBA',
                                                    'CONTRY FEST',
                                                    'CONUT ME IN',
                                                    'CONVEM',
                                                    'CONVICTIO',
                                                    'CONVILEN  GIRLS  WO',
                                                    'CONVO',
                                                    'CONVOY',
                                                    'COOK VS CON',
                                                    'CRASH BOX',
                                                    'DA VINCI CONSPIRACY',
                                                    'DANCE FLOOR',
                                                    'DEF CON',
                                                    'DOC MCM',
                                                    'DOCMCSTUFFINS  V',
                                                    'DOCTOR MC',
                                                    'DOCTOR MCSTUFFIN',
                                                    'DR MC',
                                                    'DREAMC',
                                                    'DREAMCATHER',
                                                    'FALCON R',
                                                    'FAMBOY AND CHUMC',
                                                    'FANBOY  CHUMCHUM',
                                                    'CONSE',
                                                    'CONSENT',
                                                    'CONSENTIN',
                                                    'CONSP',
                                                    'CONSPIRACY',
                                                    'CONSPIRACY T',
                                                    'CONSPIRACY TH',
                                                    'CONSPIRACY0',
                                                    'CONSPIRATORS',
                                                    'CONSPRITO',
                                                    'CONSPRITOR',
                                                    'CONSTA',
                                                    'CONSTAN',
                                                    'CONSTANTII',
                                                    'CONSTINTINE',
                                                    'CONT',
                                                    'CONTA',
                                                    'CONTACTT',
                                                    'CONTAI',
                                                    'CONTAIN',
                                                    'CONTAINTINE',
                                                    'CONTENDE',
                                                    'CONTIGON',
                                                    'CONTING CARS',
                                                    'CONTINGC',
                                                    'CONTORTION',
                                                    'CONTRAB',
                                                    'CONTRABAND',
                                                    'CONTRACTED 2',
                                                    'CONTRBA',
                                                    'CONTRY FEST',
                                                    'CONUT ME IN',
                                                    'CONVEM',
                                                    'CONVICTIO',
                                                    'CONVILEN  GIRLS  WO',
                                                    'CONVO',
                                                    'CONVOY',
                                                    'COOK VS CON',
                                                    'CRASH BOX',
                                                    'DA VINCI CONSPIRACY',
                                                    'DANCE FLOOR',
                                                    'DEF CON',
                                                    'DOC MCM',
                                                    'DOCMCSTUFFINS  V',
                                                    'DOCTOR MC',
                                                    'DOCTOR MCSTUFFIN',
                                                    'DR MC',
                                                    'DREAMC',
                                                    'DREAMCATHER',
                                                    'FALCON R',
                                                    'FAMBOY AND CHUMC',
                                                    'FANBOY  CHUMCHUM',
                                                    'FIGHT    S',
                                                    'FIGHT  TONIGHTT',
                                                    'FIGHT C',
                                                    'FIGHT S',
                                                    'FIGHT SO',
                                                    'FIGHT T',
                                                    'FIGHT TO',
                                                    'FIGHT V',
                                                    'FIGHT VALLEY',
                                                    'FIGHTING MOVIES',
                                                    'FIGHTING SU',
                                                    'FIGHTING TE',
                                                    'FIGHTING TE',
                                                    'FIGIT',
                                                    'FIGIT  SPINERS',
                                                    'FIGU',
                                                    'FIGUR',
                                                    'FIGURE',
                                                    'FIRE FIGHTER',
                                                    'FIRST CONT',
                                                    'FLIP OR FLOP TEXAS',
                                                    'FLO RIDA',
                                                    'FLO RIDA A',
                                                    'FLO RIDA L',
                                                    'FLO RIDA M',
                                                    'FLOOD',
                                                    'FLOODCEN',
                                                    'FLOOL',
                                                    'FLORIDA',
                                                    'FLOU',
                                                    'FLOW',
                                                    'FLOWE',
                                                    'FLOWER',
                                                    'FLOWER  I',
                                                    'FLOWER IN THE ATTIC',
                                                    'FLOWERS',
                                                    'FLOWERS I',
                                                    'FLOWERS IN ATT',
                                                    'FLOWERS IN ATTIC',
                                                    'FLOWERS IN THE ATC',
                                                    'FLOWERS IN THE ATTIC',
                                                    'GGG BOXING',
                                                    'GIRL FIGHT',
                                                    'GIRL IN A BOX',
                                                    'GIRL IN THE BOX',
                                                    'GIRLINTHEBOX',
                                                    'GMC',
                                                    'GOOD FIGHT',
                                                    'GUN FIGHT A',
                                                    'HBO TAXI CAB CON',
                                                    'HDPPV',
                                                    'HEROWS AND ICONS',
                                                    'HIDDEN FIGUR',
                                                    'HIDDEN FIGURES',
                                                    'HINDEN FIG',
                                                    'HIT THE FLOO',
                                                    'HIT THE FLOOR',
                                                    'HIT THE FLORE',
                                                    'ICE AGE CONT',
                                                    'ICEAGECONTI',
                                                    'ICEAGECONTI0',
                                                    'IEPERCONE',
                                                    'IF ONLY MC',
                                                    'INCONVENIENT TRUTH S',
                                                    'IT THE CONL',
                                                    'JIMCAREY',
                                                    'JIMCIMMEY',
                                                    'JOHN MCCAIN',
                                                    'KEVIN BACON',
                                                    'KEVIN MCKIDD',
                                                    'KICKBOX',
                                                    'KICKBOXE',
                                                    'KICKBOXER',
                                                    'KICKBOXER 2',
                                                    'KICKBOXING',
                                                    'KIMCA',
                                                    'LEPERCON',
                                                    'LEPPERCON',
                                                    'LEPRACON',
                                                    'LEPRAUCON',
                                                    'LICON',
                                                    'LIGHTING MCQ',
                                                    'LIGHTNING MCQU',
                                                    'LIINCON  LAWYERM',
                                                    'LONE WOLF MCQUADE',
                                                    'MADAM SECONTA',
                                                    'MAGNIFIG',
                                                    'MARRIED SECOND CHANCEE',
                                                    'MATCHBOX',
                                                    'GGG BOXING',
                                                    'GIRL FIGHT',
                                                    'GIRL IN A BOX',
                                                    'GIRL IN THE BOX',
                                                    'GIRLINTHEBOX',
                                                    'GMC',
                                                    'GOOD FIGHT',
                                                    'GUN FIGHT A',
                                                    'HBO TAXI CAB CON',
                                                    'HDPPV',
                                                    'HEROWS AND ICONS',
                                                    'HIDDEN FIGUR',
                                                    'HIDDEN FIGURES',
                                                    'HINDEN FIG',
                                                    'HIT THE FLOO',
                                                    'HIT THE FLOOR',
                                                    'HIT THE FLORE',
                                                    'ICE AGE CONT',
                                                    'ICEAGECONTI',
                                                    'ICEAGECONTI0',
                                                    'IEPERCONE',
                                                    'IF ONLY MC',
                                                    'INCONVENIENT TRUTH S',
                                                    'IT THE CONL',
                                                    'JIMCAREY',
                                                    'JIMCIMMEY',
                                                    'JOHN MCCAIN',
                                                    'KEVIN BACON',
                                                    'KEVIN MCKIDD',
                                                    'KICKBOX',
                                                    'KICKBOXE',
                                                    'KICKBOXER',
                                                    'KICKBOXER 2',
                                                    'KICKBOXING',
                                                    'KIMCA',
                                                    'LEPERCON',
                                                    'LEPPERCON',
                                                    'LEPRACON',
                                                    'LEPRAUCON',
                                                    'LICON',
                                                    'LIGHTING MCQ',
                                                    'LIGHTNING MCQU',
                                                    'LIINCON  LAWYERM',
                                                    'LONE WOLF MCQUADE',
                                                    'MADAM SECONTA',
                                                    'MAGNIFIG',
                                                    'MARRIED SECOND CHANCEE',
                                                    'MATCHBOX',
                                                    'MC CARTHY',
                                                    'MC CH',
                                                    'MC CHOICE',
                                                    'MC HAMMER',
                                                    'MC HI',
                                                    'MC M',
                                                    'MC MU',
                                                    'MC MUSI',
                                                    'MC MUSIC',
                                                    'MC P',
                                                    'MC3',
                                                    'MCA',
                                                    'MCD',
                                                    'MCDONA',
                                                    'MCF',
                                                    'MCFA',
                                                    'MCFARLAND',
                                                    'MCFARLAND  HIGH',
                                                    'GGG BOXING',
                                                    'GIRL FIGHT',
                                                    'GIRL IN A BOX',
                                                    'GIRL IN THE BOX',
                                                    'GIRLINTHEBOX',
                                                    'GMC',
                                                    'GOOD FIGHT',
                                                    'GUN FIGHT A',
                                                    'HBO TAXI CAB CON',
                                                    'HDPPV',
                                                    'HEROWS AND ICONS',
                                                    'HIDDEN FIGUR',
                                                    'HIDDEN FIGURES',
                                                    'HINDEN FIG',
                                                    'HIT THE FLOO',
                                                    'HIT THE FLOOR',
                                                    'HIT THE FLORE',
                                                    'ICE AGE CONT',
                                                    'ICEAGECONTI',
                                                    'ICEAGECONTI0',
                                                    'IEPERCONE',
                                                    'IF ONLY MC',
                                                    'INCONVENIENT TRUTH S',
                                                    'IT THE CONL',
                                                    'JIMCAREY',
                                                    'JIMCIMMEY',
                                                    'JOHN MCCAIN',
                                                    'KEVIN BACON',
                                                    'KEVIN MCKIDD',
                                                    'KICKBOX',
                                                    'KICKBOXE',
                                                    'KICKBOXER',
                                                    'KICKBOXER 2',
                                                    'KICKBOXING',
                                                    'KIMCA',
                                                    'LEPERCON',
                                                    'LEPPERCON',
                                                    'LEPRACON',
                                                    'LEPRAUCON',
                                                    'LICON',
                                                    'LIGHTING MCQ',
                                                    'LIGHTNING MCQU',
                                                    'LIINCON  LAWYERM',
                                                    'LONE WOLF MCQUADE',
                                                    'MADAM SECONTA',
                                                    'MAGNIFIG',
                                                    'MARRIED SECOND CHANCEE',
                                                    'MATCHBOX',
                                                    'MC CARTHY',
                                                    'MC CH',
                                                    'MC CHOICE',
                                                    'MC HAMMER',
                                                    'MC HI',
                                                    'MC M',
                                                    'MC MU',
                                                    'MC MUSI',
                                                    'MC MUSIC',
                                                    'MC P',
                                                    'MC3',
                                                    'MCA',
                                                    'MCD',
                                                    'MCDONA',
                                                    'MCF',
                                                    'MCFA',
                                                    'MCFARLAND',
                                                    'MCFARLAND  HIGH',
                                                    'MCI',
                                                    'MCK',
                                                    'MCMU',
                                                    'MCT',
                                                    'MELISSA MC',
                                                    'MELISSA MCARTHY',
                                                    'MELISSA MCCARTHYY',
                                                    'MELLISA MCARTHY',
                                                    'MICHAEL MCCONELL',
                                                    'MIK 1YSON FIGHTS',
                                                    'MIKE MC',
                                                    'MINT CONDISHION MU',
                                                    'MISCONDUCT',
                                                    'MISS CONG',
                                                    'MISTACOND',
                                                    'MISTICONS',
                                                    'MISTIK CONS',
                                                    'MOTHER MAY I',
                                                    'MS CONGENIALITY',
                                                    'MY CHEMC',
                                                    'NANNIE MCPHEE',
                                                    'NANNY MC',
                                                    'NANNY MCPHEE2',
                                                    'PARENTAL CONTROL',
                                                    'PARENTAL CONTROL T',
                                                    'PARENTAL CONTROLS',
                                                    'PIRANHACONDA',
                                                    'PPPPVX4R',
                                                    'PPV TRIPLE',
                                                    'PPV UNDERWORLD',
                                                    'PRIZE FIGHT',
                                                    'PROJECT MC',
                                                    'RALPHIE MAY',
                                                    'ROCK CONC',
                                                    'SAMCAT',
                                                    'SANDBOX',
                                                    'SCHOOL FIGHT',
                                                    'SECON',
                                                    'SECOND',
                                                    'SECOND C',
                                                    'SECOND CH',
                                                    'SECOND CHACE',
                                                    'SECOND CHANCE LIONS',
                                                    'SECOND COM',
                                                    'SECOND H',
                                                    'SECOND HAN',
                                                    'SECOND HAND L',
                                                    'SECONDHAN',
                                                    'SECONDHAND',
                                                    'SECONDHAND LIONS',
                                                    'SHIRLY  MCLAINNNNN',
                                                    'SIRCHARLESCONT',
                                                    'SLAM DUNK CONTEST',
                                                    'STEVE  MCQUEEN',
                                                    'STREET FIGHT',
                                                    'STREET FIGHTER',
                                                    'STREETTVFIGHTER',
                                                    'SUPER MC',
                                                    'T HE CONJUR',
                                                    'TAXI CAB CON',
                                                    'TEEN TITIANS JUDAS CONTRACT',
                                                    'THAI  BOXING DOCUMENTA',
                                                    'THE  GOOD FIGHT',
                                                    'THE  SECOND WI',
                                                    'THE  TOY   BOX',
                                                    'THE BLACK BOX',
                                                    'THE BOX',
                                                    'THE BOX C',
                                                    'THE BOX T',
                                                    'THE BOX TRO',
                                                    'THE BOX TROLLS',
                                                    'THE BOXT',
                                                    'THE BOXTROLLS',
                                                    'THE CON',
                                                    'THE CONS',
                                                    'THE CONSOLE',
                                                    'THE CONSTANTINE',
                                                    'THE CONSTATIEN',
                                                    'THE FIG',
                                                    'THE FIGH',
                                                    'THE FIGHT',
                                                    'THE FIGHTE',
                                                    'THE FINAL CON',
                                                    'THE FLOC',
                                                    'THE FLOU',
                                                    'THE FLOW',
                                                    'THE GIRL TRAPPED IN THE BOX',
                                                    'THE GOOD FIGH',
                                                    'THE GOOD FIGHT',
                                                    'THE GOODFIG',
                                                    'THE INCONV',
                                                    'THE JUDAS CONTRACT',
                                                    'THE LEPERCON',
                                                    'THE MAY',
                                                    'THE MAYO',
                                                    'THE MAYOR',
                                                    'THE MCCA',
                                                    'THE REAL MC',
                                                    'THEBOX',
                                                    'TIM CONW',
                                                    'TMC',
                                                    'TREVONMCCAW',
                                                    'GGG BOXING',
                                                    'GIRL FIGHT',
                                                    'GIRL IN A BOX',
                                                    'GIRL IN THE BOX',
                                                    'GIRLINTHEBOX',
                                                    'GMC',
                                                    'GOOD FIGHT',
                                                    'GUN FIGHT A',
                                                    'HBO TAXI CAB CON',
                                                    'HDPPV',
                                                    'HEROWS AND ICONS',
                                                    'HIDDEN FIGUR',
                                                    'HIDDEN FIGURES',
                                                    'HINDEN FIG',
                                                    'HIT THE FLOO',
                                                    'HIT THE FLOOR',
                                                    'HIT THE FLORE',
                                                    'ICE AGE CONT',
                                                    'ICEAGECONTI',
                                                    'ICEAGECONTI0',
                                                    'IEPERCONE',
                                                    'IF ONLY MC',
                                                    'INCONVENIENT TRUTH S',
                                                    'IT THE CONL',
                                                    'JIMCAREY',
                                                    'JIMCIMMEY',
                                                    'JOHN MCCAIN',
                                                    'KEVIN BACON',
                                                    'KEVIN MCKIDD',
                                                    'KICKBOX',
                                                    'KICKBOXE',
                                                    'KICKBOXER',
                                                    'KICKBOXER 2',
                                                    'KICKBOXING',
                                                    'KIMCA',
                                                    'LEPERCON',
                                                    'LEPPERCON',
                                                    'LEPRACON',
                                                    'LEPRAUCON',
                                                    'LICON',
                                                    'LIGHTING MCQ',
                                                    'LIGHTNING MCQU',
                                                    'LIINCON  LAWYERM',
                                                    'LONE WOLF MCQUADE',
                                                    'MADAM SECONTA',
                                                    'MAGNIFIG',
                                                    'MARRIED SECOND CHANCEE',
                                                    'MATCHBOX',
                                                    'MC CARTHY',
                                                    'MC CH',
                                                    'MC CHOICE',
                                                    'MC HAMMER',
                                                    'MC HI',
                                                    'MC M',
                                                    'MC MU',
                                                    'MC MUSI',
                                                    'MC MUSIC',
                                                    'MC P',
                                                    'MC3',
                                                    'MCA',
                                                    'MCD',
                                                    'MCDONA',
                                                    'MCF',
                                                    'MCFA',
                                                    'MCFARLAND',
                                                    'MCFARLAND  HIGH',
                                                    'MCI',
                                                    'MCK',
                                                    'MCMU',
                                                    'MCT',
                                                    'MELISSA MC',
                                                    'MELISSA MCARTHY',
                                                    'MELISSA MCCARTHYY',
                                                    'MELLISA MCARTHY',
                                                    'MICHAEL MCCONELL',
                                                    'MIK 1YSON FIGHTS',
                                                    'MIKE MC',
                                                    'MINT CONDISHION MU',
                                                    'MISCONDUCT',
                                                    'MISS CONG',
                                                    'MISTACOND',
                                                    'MISTICONS',
                                                    'MISTIK CONS',
                                                    'MOTHER MAY I',
                                                    'MS CONGENIALITY',
                                                    'MY CHEMC',
                                                    'NANNIE MCPHEE',
                                                    'NANNY MC',
                                                    'NANNY MCPHEE2',
                                                    'PARENTAL CONTROL',
                                                    'PARENTAL CONTROL T',
                                                    'PARENTAL CONTROLS',
                                                    'PIRANHACONDA',
                                                    'PPPPVX4R',
                                                    'PPV TRIPLE',
                                                    'PPV UNDERWORLD',
                                                    'PRIZE FIGHT',
                                                    'PROJECT MC',
                                                    'RALPHIE MAY',
                                                    'ROCK CONC',
                                                    'SAMCAT',
                                                    'SANDBOX',
                                                    'SCHOOL FIGHT',
                                                    'SECON',
                                                    'SECOND',
                                                    'SECOND C',
                                                    'SECOND CH',
                                                    'SECOND CHACE',
                                                    'SECOND CHANCE LIONS',
                                                    'SECOND COM',
                                                    'SECOND H',
                                                    'SECOND HAN',
                                                    'SECOND HAND L',
                                                    'SECONDHAN',
                                                    'SECONDHAND',
                                                    'SECONDHAND LIONS',
                                                    'SHIRLY  MCLAINNNNN',
                                                    'SIRCHARLESCONT',
                                                    'SLAM DUNK CONTEST',
                                                    'STEVE  MCQUEEN',
                                                    'STREET FIGHT',
                                                    'STREET FIGHTER',
                                                    'STREETTVFIGHTER',
                                                    'SUPER MC',
                                                    'T HE CONJUR',
                                                    'TAXI CAB CON',
                                                    'TEEN TITIANS JUDAS CONTRACT',
                                                    'THAI  BOXING DOCUMENTA',
                                                    'THE  GOOD FIGHT',
                                                    'THE  SECOND WI',
                                                    'THE  TOY   BOX',
                                                    'THE BLACK BOX',
                                                    'THE BOX',
                                                    'THE BOX C',
                                                    'THE BOX T',
                                                    'THE BOX TRO',
                                                    'THE BOX TROLLS',
                                                    'THE BOXT',
                                                    'THE BOXTROLLS',
                                                    'THE CON',
                                                    'THE CONS',
                                                    'THE CONSOLE',
                                                    'THE CONSTANTINE',
                                                    'THE CONSTATIEN',
                                                    'THE FIG',
                                                    'THE FIGH',
                                                    'THE FIGHT',
                                                    'THE FIGHTE',
                                                    'THE FINAL CON',
                                                    'THE FLOC',
                                                    'THE FLOU',
                                                    'THE FLOW',
                                                    'THE GIRL TRAPPED IN THE BOX',
                                                    'THE GOOD FIGH',
                                                    'THE GOOD FIGHT',
                                                    'THE GOODFIG',
                                                    'THE INCONV',
                                                    'THE JUDAS CONTRACT',
                                                    'THE LEPERCON',
                                                    'THE MAY',
                                                    'THE MAYO',
                                                    'THE MAYOR',
                                                    'THE MCCA',
                                                    'THE REAL MC',
                                                    'THEBOX',
                                                    'TIM CONW',
                                                    'TMC',
                                                    'TREVONMCCAW',
                                                    'ULTIMATE  FIGHTE',
                                                    'ULTIMATE FIG',
                                                    'ULTIMATE FIGHTE',
                                                    'ULTIMATE FIGHTER',
                                                    'VASYL LOMACHENKO BOXER',
                                                    'WICONSIN FOOTBALL',
                                                    'WISCONSIN',
                                                    'WISCONSINB',
                                                    'WISCONSIN B',
                                                    'WISCONSIN BADG',
                                                    'WISCONSIN BADGERS',
                                                    'WISCONSIN BADGERS FN',
                                                    'WISCONSIN BADGF',
                                                    'WISCONSIN BAG',
                                                    'WISCONSIN BDD',
                                                    'WISCONSIN FOOT',
                                                    'WISCONSIN FOOTBA',
                                                    'WISCONSIN FOOTBALL',
                                                    'WISCONSIN FOOTBALL CLASSIC',
                                                    'WISCONSINB',
                                                    'WISCONSIN BADGERS FOOTBALLL',
                                                    'ZAY HILFIGERR',
                                                    'YMCA',
                                                    'TMCC',
                                                    'THE  BOX',
                                                    'PROJECTMC',
                                                    'PPVWRESTLING SUMMERSLAM',
                                                    'FLOWER I',
                                                    'FLORENCE F',
                                                    'FLOREN',
                                                    'FLOR',
                                                    'BOXING 24 7 GGG VS ALVAREZ'))
    and ((state__search__selected_result_name is null and state__search__text is not null) OR
        (state__search__selected_result_name not in ('1790 Congressional Debate on Slavery and Race',
                                                    '2017 Florida Football Preview',
                                                    'A Season With Florida State Football',
                                                    'AMCHD',
                                                    'Alexis & Fido: Contestame El Telefono',
                                                    'All Girl Sexfest: Raunchy & Out of Control',
                                                    'American Movie Classics (East)',
                                                    'American Movie Classics (West)',
                                                    'American Movie Classics HDTV (East)',
                                                    'American Movie Classics HDTV (West)',
                                                    'An Inconvenient Sequel',
                                                    'Anaconda',
                                                    'Anacondas: The Hunt for the Blood Orchid',
                                                    'Barefoot Contessa',
                                                    'Brand: A Second Coming',
                                                    'Broken Flowers',
                                                    'CMT Concert of the Summer: Jason Aldean & Friends Live at Lake Shake',
                                                    'Chasing Conspiracies',
                                                    'College Football',
                                                    'Comcast SportsNet Chicago (Chicago DMA)',
                                                    'Con Air',
                                                    'Con Gladys',
                                                    'Conan',
                                                    'Conan the Barbarian',
                                                    'Conan the Destroyer',
                                                    'Concrete Evidence: A Fixer Upper Mystery',
                                                    'Concussion',
                                                    'Coneheads',
                                                    'Confessions of a Shopaholic',
                                                    'Confirmation',
                                                    'Congo',
                                                    'Conjuring Up S4',
                                                    'Connie the Cow',
                                                    'Consenting Adults',
                                                    'Conspiracy',
                                                    'Conspiracy Theory',
                                                    'Constantine',
                                                    'Consuelo Mack WealthTrack',
                                                    'Contact',
                                                    'Contagion',
                                                    'Contracorriente',
                                                    'Contracted',
                                                    'Conviction',
                                                    'Cooks vs. Cons',
                                                    'Disconnected',
                                                    'Discover Wisconsin',
                                                    'Doc McStuffins',
                                                    'Doc McStuffins: Toy Hospital',
                                                    'Empire',
                                                    'Flip or Flop',
                                                    'Flood',
                                                    'Florence & The Machine: Live at Glastonbury Festival 2015',
                                                    'Florence Foster Jenkins',
                                                    'Florida Georgia Line on \'Dig Your Roots\' Inspiration',
                                                    'Florida Georgia Line: Cruise',
                                                    'Florida Georgia Line: God, Your Mama, And Me',
                                                    'Florida Georgia Line: H.O.L.Y.',
                                                    'Florida Georgia Line: May We All',
                                                    'Florida Georgia Line: Smooth',
                                                    'Florida Georgia Line: This Is How We Roll',
                                                    'Flower Shop Mystery: Mum\'s the Word',
                                                    'Flowers',
                                                    'Genesis: The Creation and the Flood',
                                                    'Grab Your Catechism with Fr. Connor',
                                                    'Hustle & Flow',
                                                    'IMCA Racing Rewind',
                                                    'Icons of the Centennial',
                                                    'If Loving You Is Wrong',
                                                    'In Concert',
                                                    'Insecure',
                                                    'Inside Mayweather vs. Pacquiao',
                                                    'Jon Pardi: Heartache On The Dance Floor',
                                                    'Laura McKenzie\'s Traveler',
                                                    'Love Connection',
                                                    'MC - Solid Gold Oldies',
                                                    'MC - Today\'s Country',
                                                    'MCMILLAN',
                                                    'MacGyver',
                                                    'Maya the Bee',
                                                    'Maybe It\'s You With Lauren Handel Zander',
                                                    'Mayberry R.F.D.',
                                                    'McFarland, USA',
                                                    'McLintock!',
                                                    'McLintock! -- Producer\'s Cut',
                                                    'Miss Congeniality',
                                                    'Music Choice Contemporary Christian',
                                                    'NFL Preseason Football',
                                                    'Nanny McPhee',
                                                    'Nicki Minaj: Anaconda',
                                                    'Operación Cóndor',
                                                    'Post Malone: Congratulations',
                                                    'Respuestas con Bayless Conley',
                                                    'Revolt Concert Series Presents: Trey Songz',
                                                    'Rock and Roll Hall of Fame Concerts - Live!',
                                                    'SH027514950000',
                                                    'Second Wives Club',
                                                    'Secondhand Lions',
                                                    'Sing for the Day! Tommy Shaw and Contemporary Youth Orchestra',
                                                    'Small Town, Big Mayor',
                                                    'Smerconish',
                                                    'Song Concert',
                                                    'Spectrum Guide - Parental Controls',
                                                    'TMC',
                                                    'TMC - Movie Channel (The)  On Demand HD',
                                                    'TMC - Movie Channel (The) (East)',
                                                    'TMC - Movie Channel (The) On Demand',
                                                    'TMC - Movie Channel (The)  On Demand HD',
                                                    'The Concert for Valor',
                                                    'The Condemned 2',
                                                    'The Confession',
                                                    'The Conjuring',
                                                    'The Conjuring 2',
                                                    'The Conspirator',
                                                    'The Contender',
                                                    'The Conversation',
                                                    'The Final Conflict',
                                                    'The Floogals',
                                                    'The French Connection',
                                                    'The Lizzie McGuire Movie',
                                                    'The Mayor 08-26',
                                                    'The Mayor 08-26 HD',
                                                    'The Mayor 08-29 HD',
                                                    'The Mayor of Hell',
                                                    'The Second Arrival',
                                                    'The Second Best Exotic Marigold Hotel',
                                                    'The Simpsons',
                                                    'Three Days of the Condor',
                                                    'Tim McGraw & Faith Hill: Speak to Girl',
                                                    'Tim McGraw: Humble And Kind',
                                                    'UFC 196: McGregor vs. Diaz',
                                                    'Walker McGuire: Til Tomorrow',
                                                    'Wisconsin Football Classic',
                                                    'Íconos',
                                                    'McMillan and Wife',
                                                    'Real Time Florida Sportsman',
                                                    'Son of the Congo',
                                                    'TMC - Movie Channel (The)  On Demand HD',
                                                    'TMC - Movie Channel (The)  On Demand HD ',
                                                    'TMC - Movie Channel (The) HDTV (East)',
                                                    'The Beach Boys 50: Live in Concert',
                                                    'The Conjuring: The Shocking Truth',
                                                    'The Constant Gardener',
                                                    'The Lady Consents',
                                                    'The Tim McCarver Show',
                                                    'Tim McGraw: Live Like You Were Dying',
                                                    'UFC 189: Mendes vs. McGregor',
                                                    'World War II: Confidential',
                                                    'A Second Chance',
                                                    'Anaconda: Asesina Silenciosa',
                                                    'Anacondas: Trail of Blood',
                                                    'Angela Anaconda',
                                                    'CONCACAF Copa Oro_S2017E0',
                                                    'CONCACAF Liga de Campeones en 60',
                                                    'Codes and Conspiracies',
                                                    'Con Man',
                                                    'Conagher',
                                                    'Conal Flood: Follow Me',
                                                    'Confessions of a Nazi Spy',
                                                    'Conjoined Twins: Miracle Separation',
                                                    'Conjoined Twins: Separation Anxiety',
                                                    'Conquest of the Planet of the Apes',
                                                    'Conrack',
                                                    'Contacto Salva',
                                                    'Continental Divide',
                                                    'Contraband',
                                                    'Criminal Minds',
                                                    'David McCullough: Painting With Words',
                                                    'Dazed and Confused',
                                                    'Flip or Flop Atlanta',
                                                    'Flophouse',
                                                    'Florida in 60',
                                                    'Flower Shop Mystery: Snipped in the Bud',
                                                    'Flowers in the Attic',
                                                    'Fútbol Liga CONCACAF',
                                                    'Girls',
                                                    'Hannah Montana and Miley Cyrus: Best of Both Worlds Concert',
                                                    'Hustlers Convention',
                                                    'Insecure: Convo HD',
                                                    'Journey in Concert: Houston 1981',
                                                    'Lone Wolf McQuade',
                                                    'Married at First Sight: Second Chances',
                                                    'Martina McBride: Everlasting Tour: Live From the Ryman Auditorium',
                                                    'TMC - Movie Channel (The)  On Demand HD',
                                                    'McGraw Milhaven Show')) --'
         )
         group by UPPER(state__search__text),
                  state__search__results,
                  state__view__next_page__page_name,
                  UPPER(state__search__selected_result_name);

select * from dev.brian_ppv_searches;

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Purchase Results
-- A listing of all purchase attempts for program id 'SH027309320000' fight related.
--   PPV Purchase attempts 6477

--drop table dev.brian_ppv_purchases;
create table dev.brian_ppv_purchases as
select * from (
    select prod.epoch_converter (received__timestamp, 'America/Denver') partition_date_denver,
    received__timestamp,
    visit__visit_id,
    visit__device__uuid,
    visit__account__account_number_aes_256,
    application__api__api_name,
    application__api__path,
    state__view__previous_page__page_name,
    lag(a.application__api__path, 3) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as tms_id,
    lag(a.application__api__path, 4) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as tms_id2,
    lead(a.message__name, 1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as message__name,
    lead(a.application__error__error_code, 1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as application__error__error_code
    FROM dev.brian_venona_events_view a
    WHERE visit__application_details__application_name = 'Spectrum Guide'
                AND partition_date_utc between '2017-08-01' and '2017-09-01' 
                --and visit__visit_id = 'a3acd699-0fc2-4c63-7864-f318e653754d'
                ) events
    LEFT JOIN 
    (SELECT run_date,
         account__mac_id_aes256,
         account__number_aes256,
         system__kma_desc,
         system__nielsen_dma,
         account__category,
         sg_deployed_type,
         account__type,
         customer__type,
         CASE
           WHEN (sg_account_deployed_timestamp < 0) THEN FLOOR((datediff(run_date, NVL(customer__install_date, last__customer_connect_date))) / 30)
           ELSE FLOOR((datediff(run_date,prod.epoch_converter (sg_account_deployed_timestamp*1000, 'America/Denver'))) / 30)
         END AS subscriber_account_age_months
  FROM prod_lkp.SG_PHASEII_DEPLOYED_MACS_ALL_HISTORY
  WHERE --run_date = '2017-10-28'
    run_date between '2017-08-01' and '2017-09-01'
    --AND account__category = 'DVR'
    --AND account__type = 'SUBSCRIBER'
    --AND sg_deployed_type = 'NEW_CONNECT'
    --AND run_date >= NVL(customer__install_date, last__customer_connect_date)
    ) AS b
  ON events.visit__device__uuid = prod.aes_encrypt (prod.aes_decrypt256 (b.account__mac_id_aes256))
  AND events.partition_date_denver = b.run_date
where (application__api__api_name = 'ppvEdgePpvPurchases' and application__api__path rlike '/eid/')
and (tms_id rlike 'SH027309320000' or tms_id2 rlike 'SH027309320000');

select * from dev.brian_ppv_purchases;

~~~~~~~~~~~~~~~~~~~
-- Determine how many households tried to purchase, 
-- vs how many households that never were succesful at purchasing.

select count(distinct visit__account__account_number_aes_256) unique_hh_purch_attempts
from dev.brian_ppv_purchases a;
--4558 unique households attempting to purchase (excludes attempts without account numbers 
-- out of a total of 4692 attempts.)

-- Purchase attempts by KMA
select system__kma_desc, count(distinct visit__account__account_number_aes_256) unique_hh_purch_attempts
from dev.brian_ppv_purchases a
where system__kma_desc is not null
group by system__kma_desc;

-- Purchase attempts by DMA
select system__nielsen_dma, count(distinct visit__account__account_number_aes_256) unique_hh_purch_attempts
from dev.brian_ppv_purchases a
where system__nielsen_dma is not null
group by system__nielsen_dma;

-- Build a table of all spec guide activity for PPV purchase attempt visits
-- to determine how many times a households attempted a purchase and whether
-- the attempts eventually succeeded or the subscriber stopped trying.
--drop table dev.brian_ppv_purch_attempts;
create table dev.brian_ppv_purch_attempts as
select distinct a.received__timestamp,
a.visit__visit_id,
a.visit__device__uuid,
a.visit__device__uuid_aes_256, 
a.visit__account__account_number,
a.visit__account__account_number_aes_256,
a.visit__application_details__application_name,
a.visit__application_details__application_type,
a.visit__application_details__app_version,
a.visit__application_details__venona_version,
a.application__api__path,
a.application__api__api_name,
a.application__api__api_category,
a.application__api__http_verb,
a.application__api__query_parameters,
a.application__error__error_code,
a.message__category,
a.message__name,
a.message__sequence_number,
a.message__timestamp,
a.message__triggered_by,
a.state__content__content_class,
a.state__content__identifiers__dvr_recording_id,
a.state__content__identifiers__tms_program_id,
a.state__name,
a.state__view__current_page__page_name,
a.state__view__current_page__app_section,
a.state__view__current_page__page_section__name,
a.state__view__current_page__elements__standardized_name,
a.state__view__current_page__elements__ui_name,
a.state__view__current_page__sort_and_filter__applied_filters,
a.state__view__current_page__sort_and_filter__applied_sorts,
a.state__view__previous_page__page_name,
a.state__view__previous_page__app_section,
a.state__view__previous_page__page_section__name,
a.state__view__modal__name,
a.state__view__modal__text,
a.state__search__text,
a.state__search__results,
a.state__search__selected_result_name,
a.operation__operation_type,
a.operation__success,
a.partition_date_utc,
a.partition_date_hour_utc,
b.system__kma_desc,
b.system__nielsen_dma
from dev.brian_venona_events_view a
join dev.brian_ppv_purchases b
on a.visit__visit_id = b.visit__visit_id
where a.partition_date_utc between '2017-08-01' and '2017-09-01'
      and a.visit__application_details__application_name = 'Spectrum Guide'
order by a.visit__account__account_number_aes_256, 
         a.received__timestamp, message__sequence_number;
         
select * from dev.brian_ppv_purch_attempts;         

-- Distinct households that recieved errors during purchase = 777 unique households (778 minus 1 null account number)
create table dev.brian_ppv_purchase_attempt_errors as
select a.visit__account__account_number_aes_256,
       a.system__kma_desc,
       a.system__nielsen_dma
from (
select visit__account__account_number_aes_256, 
       system__kma_desc,
       system__nielsen_dma,
       message__name, 
       count(message__name) count_message_name 
from (
    select prod.epoch_converter (received__timestamp, 'America/Denver') recvd_date,
    received__timestamp,
    visit__visit_id,
    visit__account__account_number_aes_256,
    system__kma_desc,
    system__nielsen_dma,
    application__api__api_name,
    application__api__path,
    state__view__previous_page__page_name,
    message__sequence_number,
    lag(a.application__api__path, 3) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as tms_id,
    lag(a.application__api__path, 4) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as tms_id2,
    nvl(case lead(a.message__name, 1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) 
      when 'apiCall' THEN 'modalView'
      else lead(a.message__name, 1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number)
    end, 'modalView') as message__name,
    lead(a.application__error__error_code, 1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as application__error__error_code
    FROM dev.brian_ppv_purch_attempts a
    WHERE visit__application_details__application_name = 'Spectrum Guide'
                AND partition_date_utc between '2017-08-01' and '2017-09-01' 
                ) b
where (application__api__api_name = 'ppvEdgePpvPurchases' and application__api__path rlike '/eid/')
and message__name = 'error'
group by visit__account__account_number_aes_256, 
         message__name,
         system__kma_desc,
         system__nielsen_dma
order by visit__account__account_number_aes_256, 
         message__name) a
where a.visit__account__account_number_aes_256 IS NOT NULL
group by a.visit__account__account_number_aes_256,
         a.system__kma_desc,
         a.system__nielsen_dma;

select * from dev.brian_ppv_purchase_attempt_errors;         

-- Households that had errors, but eventually succeeded = 194 Unique Households.
-- If a household has both error and success (modalView) results, we assume that after one or 
-- more error attempts, the PPV purchase was actually successful (194 of these scenarios)        
create table dev.brian_ppv_purchase_attempts_eventual_success as
select a.visit__account__account_number_aes_256,
       a.system__kma_desc,
       a.system__nielsen_dma
from (
select visit__account__account_number_aes_256, 
       message__name, 
       system__kma_desc,
       system__nielsen_dma,
       count(message__name) count_message_name 
from (
    select prod.epoch_converter (received__timestamp, 'America/Denver') recvd_date,
    received__timestamp,
    visit__visit_id,
    visit__account__account_number_aes_256,
    system__kma_desc,
    system__nielsen_dma,
    application__api__api_name,
    application__api__path,
    state__view__previous_page__page_name,
    message__sequence_number,
    lag(a.application__api__path, 3) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as tms_id,
    lag(a.application__api__path, 4) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as tms_id2,
    nvl(case lead(a.message__name, 1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) 
      when 'apiCall' THEN 'modalView'
      else lead(a.message__name, 1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number)
    end, 'modalView') as message__name,   -- Roll up any apiCall or null message names to modalView as these both are also successful PPV purchases --
    lead(a.application__error__error_code, 1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as application__error__error_code
    FROM dev.brian_ppv_purch_attempts a
    WHERE visit__application_details__application_name = 'Spectrum Guide'
                AND partition_date_utc between '2017-08-01' and '2017-09-01' 
                ) b
where (application__api__api_name = 'ppvEdgePpvPurchases' and application__api__path rlike '/eid/')
group by visit__account__account_number_aes_256, 
         message__name,
         system__kma_desc,
         system__nielsen_dma
order by visit__account__account_number_aes_256, 
         message__name) a
group by a.visit__account__account_number_aes_256,
         a.system__kma_desc,
         a.system__nielsen_dma
having count(a.visit__account__account_number_aes_256) >= 2;

-- Since 777 households received errors, and 194 of those eventually succeeded in ordering PPV,
-- the difference between 777 and 194 reveals that 583 households never succeeded at ordering PPV
-- through Spectrum Guide. 
select a.visit__account__account_number_aes_256,
       a.system__kma_desc,
       a.system__nielsen_dma
from dev.brian_ppv_purchase_attempt_errors a
left join dev.brian_ppv_purchase_attempts_eventual_success b
on a.visit__account__account_number_aes_256 = b.visit__account__account_number_aes_256
where b.visit__account__account_number_aes_256 is null;

-- Never succeeded breakdown by KMA
select system__kma_desc, 
       count(a.visit__account__account_number_aes_256) as count_by_kma
from (select a.visit__account__account_number_aes_256,
             a.system__kma_desc,
             a.system__nielsen_dma
      from dev.brian_ppv_purchase_attempt_errors a
      left join dev.brian_ppv_purchase_attempts_eventual_success b
             on a.visit__account__account_number_aes_256 = b.visit__account__account_number_aes_256
          where b.visit__account__account_number_aes_256 is null
          and a.system__kma_desc is not null) a
group by system__kma_desc;

-- Never succeeded breakdown by DMA
select system__nielsen_dma, 
       count(a.visit__account__account_number_aes_256) as count_by_kma
from (select a.visit__account__account_number_aes_256,
             a.system__kma_desc,
             a.system__nielsen_dma
      from dev.brian_ppv_purchase_attempt_errors a
      left join dev.brian_ppv_purchase_attempts_eventual_success b
             on a.visit__account__account_number_aes_256 = b.visit__account__account_number_aes_256
          where b.visit__account__account_number_aes_256 is null
          and a.system__kma_desc is not null) a
group by system__nielsen_dma;


-- Frequency Breakdown of the Purchase Attempts, specifically the 777 Errored attempts.
select message__name, 
count_message_name as count_of_purchase_attempts, 
count(visit__account__account_number_aes_256) as number_of_accounts
from (select visit__account__account_number_aes_256, 
       message__name, 
       count(message__name) count_message_name 
from (
    select prod.epoch_converter (received__timestamp, 'America/Denver') recvd_date,
    received__timestamp,
    visit__visit_id,
    visit__account__account_number_aes_256,
    application__api__api_name,
    application__api__path,
    state__view__previous_page__page_name,
    message__sequence_number,
    lag(a.application__api__path, 3) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as tms_id,
    lag(a.application__api__path, 4) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as tms_id2,
    nvl(case lead(a.message__name, 1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) 
      when 'apiCall' THEN 'modalView'
      else lead(a.message__name, 1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number)
    end, 'modalView') as message__name,
    lead(a.application__error__error_code, 1) OVER (PARTITION BY visit__visit_id ORDER BY message__sequence_number) as application__error__error_code
    FROM dev.brian_ppv_purch_attempts a
    WHERE visit__application_details__application_name = 'Spectrum Guide'
                AND partition_date_utc between '2017-08-01' and '2017-09-01' 
                ) b
where (application__api__api_name = 'ppvEdgePpvPurchases' and application__api__path rlike '/eid/')
--and message__name = 'error'
group by visit__account__account_number_aes_256, message__name
order by visit__account__account_number_aes_256, message__name) c
where visit__account__account_number_aes_256 is not null
group by message__name, count_message_name
