.alerts_app_figures_variables: &alerts_app_figures_variables
  JOB_NAME: "alert-app-figures"
  ARTIFACTS_DIR: "alerts/alerts-app-figures/artifacts"
  TERRAFORM_DIR: "alerts/alerts-app-figures/terraform"
  ALERT_LAMBDA_DIR: "alerts/alerts-app-figures/lambda"
  S3_ARTIFACTS_DIR: "alerts/alerts-app-figures"

alerts_app_figures_build:
  extends: .build_alerts
  variables:
    <<: *alerts_app_figures_variables

#STG
alerts_app_figures_plan_stg:
  extends: .plan_stg
  variables:
    <<: *alerts_app_figures_variables
  dependencies:
    - alerts_app_figures_build

alerts_app_figures_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *alerts_app_figures_variables
  dependencies:
    - alerts_app_figures_build
    - alerts_app_figures_plan_stg

alerts_app_figures_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *alerts_app_figures_variables
  dependencies:
    - alerts_app_figures_build

#PROD
alerts_app_figures_plan_prod:
  extends: .plan_prod
  variables:
    <<: *alerts_app_figures_variables
  dependencies:
    - alerts_app_figures_build

alerts_app_figures_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *alerts_app_figures_variables
  dependencies:
    - alerts_app_figures_build
    - alerts_app_figures_plan_prod

alerts_app_figures_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *alerts_app_figures_variables
  dependencies:
    - alerts_app_figures_build
