use ${env:LKP_db};
drop table if exists cs_dispositions_issue_groups;
drop table if exists cs_dispositions_cause_groups;
drop table if exists cs_dispositions_resolution_groups;

--creates table of issues and their groupings. tracks grouping versions. "current" is the most up to date version.

create table cs_dispositions_issue_groups as
select
distinct
issue_description
,id_form
,case
when issue_description is null
or issue_description like ''
then 'No Disposition'
when issue_description like '%Billing%'
or issue_description like '%Payment%'
or issue_description like '%Credit%'
then 'Billing'
when issue_description like '%Account%'
or issue_description like '%ID Management%'
or issue_description like '%Hierarchy%'
or issue_description like '%New Customer%'
or issue_description like '%CBPP%'
or issue_description like '%Modify Order%'
then 'Account Management'
when issue_description like '%Box%'
or issue_description like '%Device%'
then 'Equipment'
when issue_description like '%Feature%'
or issue_description like '%Hotelworks%'
or issue_description like '%CB Backup%'
or issue_description like '%F-Secure%'
or issue_description like '%Guide%'
then 'Feature Issues'
when issue_description like '%Quality%'
then 'Quality Issues'
when issue_description like '%Appointment%'
or issue_description like '%Completion%'
then 'Appointments'
when issue_description like '%Service T%'
or issue_description like '%No Service%'
or issue_description like '%Services%'
or issue_description like '%Service Issues%'
or issue_description like '%PPV Issues%'
or issue_description like '%Video - Channel%'
or issue_description like '%Video - Music%'
or issue_description like '%Tech Call%'
or issue_description like '%Self Install%'
or issue_description like '%Activation%'
or issue_description like '%IP Info%'
then 'Service Issues'
when issue_description like '%Incomplete%'
then 'Incomplete Call'
when issue_description like '%Scope%'
then 'Out of Scope'
when (issue_description like '%App%'
and not issue_description like '%Appointment%')
then 'App Issues'
when issue_description like '%General%'
then 'General Question'
when issue_description like '%Change of Service%'
then 'Change of Service'
when issue_description like '%Connectivity%'
then 'Connectivity'
when issue_description like '%Repair%'
then 'Repair'
else 'Other'
end as issue_group
,'retired on 2019-10-19' as version
from cs_dispositions
union
select
distinct
issue_description
,id_form
,case
when issue_description is null
or issue_description like ''
then 'No Disposition'
when issue_description like '%Incomplete%'
then 'Incomplete Call'
when issue_description like '%Billing%'
or issue_description like '%Payment%'
or issue_description like '%Credit%'
then 'Billing'
when issue_description like '%Equipment%'
or issue_description like '%Box%'
or issue_description like '%Device%'
or issue_description like '%Modem%'
or (issue_description like 'Modify Existing%'
and issue_description like '%Wi%')
then 'Equipment'
when issue_description like '%Appointment%'
then 'Appointments'
when issue_description like '%Account%'
or issue_description like '%Management%'
or issue_description like '%New Customer%'
or issue_description like '%Hierarchy%'
or issue_description like '%Portal%'
then 'Account Management'
when issue_description like '%Quality%'
then 'Quality Issues'
when issue_description like '%Change%'
and issue_description like '%Service%'
then 'Change of Service'
when issue_description like '%Feature%'
or issue_description like '%Hotelworks%'
or issue_description like '%CB Backup%'
or issue_description like '%F-Secure%'
or issue_description like '%Guide%'
then 'Feature Issues'
when issue_description like '%General%'
or issue_description like 'Order Status'
then 'General Question'
when issue_description like '%Connectivity%'
then 'Connectivity'
when issue_description like '%Service%'
or issue_description like '%Activation%'
or issue_description like '%Install%'
or issue_description like '%Disconnect%'
or issue_description like '%PPV Issues%'
or issue_description like '%Video - Channel%'
or issue_description like '%Video - Music%'
or issue_description like '%Tech Call%'
or issue_description like '%IP Info%'
or issue_description like 'Internet'
or issue_description like 'Video'
or (issue_description like 'Video%'
and issue_description like '%Hits%')
then 'Service Issues'
when issue_description like '%Scope%'
then 'Out of Scope'
when issue_description like '%Repair%'
then 'Repair'
when issue_description like '%App%'
then 'App Issues'
else 'Other'
end as issue_group
,'current' as version
from cs_dispositions;

--creates table of causes and their groupings. tracks grouping versions. "current" is the most up to date version.

create table cs_dispositions_cause_groups as
select
distinct
cause_description
,cd_form
,case
when cause_description is null
or cause_description like ''
then 'No Disposition'
when (cause_description like '%Bill%'
or cause_description like '%Payment%'
or cause_description like '%Credit%'
or cause_description like '%Charge%'
or cause_description like '%Discount%'
or cause_description like '%Transactions%'
or cause_description like '%Coupon%'
or cause_description like '%Rate%'
or cause_description like '%Prorate%'
or cause_description like '%money%'
or cause_description like '%Money%'
or cause_description like '%Offer%'
or cause_description like '%Promotion%')
and not cause_description like '%Migrate%'
then 'Billing'
when (cause_description like '%Account%'
or ((cause_description like '%ID%'
or cause_description like '%Id%')
and (cause_description like '%Convert%'
or cause_description like '%Create%'))
or cause_description like '%User%'
or cause_description like '%Owner%'
or cause_description like '%Modify Existing%'
or cause_description like '%Login%'
or cause_description like '%Customer Contact%')
and not cause_description like '%Bill%'
and not cause_description like '%DSR%'
then 'Account Management'
when cause_description like '%Email%'
and not cause_description like '%Voicemail%'
and not cause_description like '%Response%'
then 'Email'
when cause_description like '%Connectivity%'
then 'Connectivity'
when (cause_description like '%equipment%'
or cause_description like '%Equipment%'
or cause_description like '%Router%'
or cause_description like '%Computer%'
or cause_description like '%Box Activation%'
or cause_description like '%DVR%'
or cause_description like '%Remote%'
or cause_description like '%Accessories%'
or cause_description like '%Cable%'
or (cause_description like '%Device%'
and not cause_description like '%Bill%'))
and not cause_description like '%Feature%'
then 'Equipment'
when cause_description like '%Video%'
and not cause_description like '%Guide%'
and not cause_description like '%Box%'
and not cause_description like '%Channels%'
and not cause_description like '%service%'
and not cause_description like '%Service%'
and not cause_description like '%Repair%'
and not cause_description like '%Device%'
then 'Video'
when (cause_description like '%Feature%'
or cause_description like '%Caller ID%'
or cause_description like '%VOD%'
or cause_description like '%PPV%'
or cause_description like '%Fax%'
or cause_description like '%On Demand%'
or cause_description like '%Hotspot%'
or cause_description like '%HotSpot%'
or cause_description like '%Guide%')
and not cause_description like '%Pricing%'
and not cause_description like '%General%'
and not cause_description like '%Quality%'
then 'Feature Issues'
when cause_description like '%Appointment%'
or cause_description like '%Work Order%'
or cause_description like '%ETA On%'
then 'Appointments'
when cause_description like '%Sales%'
or cause_description like '%New Customer%'
or cause_description like '%Pricing%'
then 'Sales'
when (cause_description like '%service%'
or cause_description like '%Service%'
or cause_description like '%Dial%'
or cause_description like '%Channels Out%'
or cause_description like '%Calling Issue%'
or cause_description like '%Streaming Issue%'
or (cause_description like '%Missing%'
and cause_description like '%Channel%'))
and not cause_description like '%Device%'
and not cause_description like '%General%'
and not cause_description like '%Settings%'
and not cause_description like '%Feature%'
and not cause_description like '%Charge%'
then 'Service Issues'
when cause_description like '%Incomplete%'
or cause_description like '%Dead%'
or cause_description like '%Dropped%'
or cause_description like '%CSR%'
then 'Incomplete Call'
when (cause_description like 'Existing%'
and cause_description like '%Customer%')
or cause_description like '%Non-Charter%'
or cause_description like '%Non-English%'
or cause_description like '%Consult%'
then 'Out of Scope'
when cause_description like '%Pixelation%'
or cause_description like '%Aspect%'
OR cause_description like '%Speed%'
or cause_description like '%Quality%'
then 'Quality Issues'
when cause_description like '%App%'
and not cause_description like '%applied%'
and not cause_description like '%appear%'
and not cause_description like '%Appear%'
and not cause_description like '%Login%'
and not cause_description like '%Appointment%'
then 'App Issues'
when (cause_description like '%General%'
or cause_description like '%Company Information%'
or cause_description like '%Charter Business%'
or cause_description like '%Spectrum Business%'
or cause_description like '%Charter Store%')
and not cause_description like '%Bill%'
and not cause_description like '%Charge%'
then 'General Question'
when cause_description like '%Retention%'
then 'Retention Issue'
WHEN (cause_description like '%Provisioning%'
or cause_description like '%Failed%'
or cause_description like '%Error During%')
and not cause_description like '%Swap%'
then 'Provisioning Issue'
when cause_description like '%Repair%'
then 'Repair'
when cause_description = '?'
then 'No Disposition'
else 'Other'
end as cause_group
,'retired on 2019-10-19' as version
from cs_dispositions
union
select
distinct
cause_description
,cd_form
,case
when cause_description is null
or cause_description like ''
then 'No Disposition'
when cause_description like '%Repair%'
then 'Repair'
when cause_description like '%Consult%'
or cause_description like '%English%'
or cause_description like '%Wrong%'
or cause_description like '%Residential%'
or cause_description like '%CSI%'
or (cause_description like '%Existing%'
and cause_description like '%Customer%'
and (cause_description like '%BHN%'
or cause_description like '%CHTR%'
or cause_description like '%TWC%'))
then 'Out of Scope'
when cause_description like '%Dead%'
or cause_description like '%Dropped%'
or cause_description like '%Dropping%'
or cause_description like '%Incomplete%'
or (cause_description like '%Caller%'
and cause_description like '%CSR%')
then 'Incomplete Call'
when cause_description like '%Sales%'
or cause_description like '%Pricing%'
or (cause_description like '%New%'
and cause_description like '%Customer%')
then 'Sales'
when cause_description like '%Aspect%'
or cause_description like '%Pixel%'
or cause_description like '%Quality%'
or cause_description like '%Speed%'
then 'Quality Issues'
when cause_description like '%Bill%'
or cause_description like '%Payment%'
or cause_description like '%AutoPay%'
or cause_description like '%Autopay%'
or cause_description like '%Credit%'
or cause_description like '%Charge%'
or cause_description like '%Discount%'
or cause_description like '%Transact%'
or cause_description like '%Bank%'
or cause_description like '%Balance%'
or cause_description like '%Coupon%'
or ((cause_description like '%Rate%'
or cause_description like '%rate%')
and cause_description not like '%Migrate%')
or (cause_description like '%Money%'
and cause_description like '%Back%')
or cause_description like '%Offer%'
or cause_description like '%Promo%'
or cause_description like '%Adjustment%'
or cause_description like '%Buyout%'
or ((cause_description like '%Due%'
and cause_description like '%Date%')
and cause_description not like '%BGS%')
then 'Billing'
when ((cause_description like '%Channel%'
and cause_description not like '%Box%')
or cause_description like '%Limited%'
or (cause_description like '%Portal%'
and cause_description like '%Activation%')
or cause_description like '%Service%'
or cause_description like '%service%'
or cause_description like '%Live TV%'
or (cause_description like '%Error%'
and (cause_description like '%Authorized%'
or cause_description like '%Subscribe%'))
or (cause_description like '%Activate%'
and cause_description like '%Message%'))
and not (cause_description like '%Feature%'
and cause_description not like '%Change%')
and cause_description not like '%Ownership%'
and cause_description not like '%VOD%'
then 'Service Issues'
when (cause_description like '%Accessories%'
or cause_description like '%Cable%'
or cause_description like '%Computer%'
or cause_description like '%Modem%'
or cause_description like '%Clock%'
or cause_description like '%Remote%'
or cause_description like '%Router%'
or cause_description like '%Equip%'
or cause_description like '%equip%'
or cause_description like '%Device%'
or cause_description like '%Outlet%'
or cause_description like '%DVR%'
or (cause_description like '%Drop%'
and (cause_description like '%Bury%'
or cause_description like '%SRO%'))
or (cause_description like '%Box%'
and cause_description not like '%World%'
and cause_description not like '%Caller%'))
and cause_description not like '%Connectivity%'
and cause_description not like '%Feature%'
then 'Equipment'
when cause_description like '%Dial%'
or cause_description like '%Phone%'
or cause_description like '%phone%'
or cause_description like '%Number%'
or cause_description like '%Inbound%'
or cause_description like '%Outbound%'
or cause_description like '%Porting%'
or cause_description like '%Forwarding%'
or cause_description like '%Voice%'
or cause_description like '%Cellular%'
or (cause_description like '%Mobile%'
and cause_description like '%Spectrum%')
or cause_description like '%Calling Issue%'
or cause_description like '%Dial Tone%'
or cause_description like 'Agent Assisted Activation%'
then 'Voice / Mobile'
when (cause_description like '%Email%'
or cause_description like '%Webmail%'
or cause_description like '%Mailbox%')
and cause_description not like '%Response%'
then 'Email'
when (cause_description like '%Connect%'
and cause_description like '%Wi%')
or cause_description like '%Connected%'
or cause_description like '%Connection%'
or cause_description like '%Connectivity%'
then 'Connectivity'
when cause_description like '%Appointment%'
or (cause_description like '%Work%'
and cause_description like '%Order%')
or cause_description like '%Technician%'
or cause_description like '%ETD%'
then 'Appointments'
when cause_description like '%Caller ID%'
or cause_description like '%Demand%'
or cause_description like '%Fax%'
or cause_description like '%Feature%'
or cause_description like '%feature%'
or cause_description like '%Guide%'
or cause_description like '%HotSpot%'
or cause_description like '%Hotspot%'
or cause_description like '%PPV%'
or cause_description like '%VOD%'
or cause_description like '%PIN%'
then 'Feature Issues'
when (cause_description like '%Account%'
or cause_description like '%Contact%'
or cause_description like '%contact%'
or cause_description like '%Convert%'
or cause_description like '%Portal%'
or cause_description like '%Create%'
or cause_description like '%Login%'
or cause_description like '%Modify%'
or cause_description like '%Ownership%'
or cause_description like '%Profile%'
or cause_description like '%User%')
and (cause_description not like '%DSR%'
and cause_description not like '%Sales%')
then 'Account Management'
when cause_description like '%Retention%'
then 'Retention Issue'
when cause_description like '%App %'
or cause_description like '%TV App%'
then 'App Issues'
when cause_description like '%Business%'
or cause_description like '%Charter%'
or cause_description like '%Company%'
or cause_description like '%General%'
or cause_description like '%Information%'
or cause_description like '%Spectrum%'
or cause_description like '%Store%'
then 'General Question'
when cause_description like '%Failed%'
or cause_description like '%Install%'
or cause_description like '%install%'
or cause_description like '%Provisioning%'
then 'Provisioning Issue'
else 'Other'
end as cause_group
,'current' as version
from cs_dispositions;

--creates table of resolutions and their groupings. tracks grouping versions. "current" is the most up to date version.

create table cs_dispositions_resolution_groups as
select
distinct
resolution_description
,rd_form
,case
when resolution_description is null
or resolution_description like ''
then 'No Disposition'
when resolution_description = 'Restore Services'
then 'Directed to Local Office'
when resolution_description = 'Updated Contact Preferences'
then 'Referral'
when (resolution_description = 'Customer Ed'
and issue_description = 'Account Management')
or (resolution_description like '%Customer Ed%'
and not resolution_description = 'Customer Ed'
and (resolution_description like '%Password%'
or resolution_description like '%Identit%'
or resolution_description like '%Head of House%'
or resolution_description like '%Admin%'
or resolution_description like '%Accept%'
or resolution_description like '%User%'
or resolution_description like '%Account%'))
then 'Customer Education - Account'
when resolution_description like '%Customer Ed%'
and issue_description like '%Bill%'
or issue_description like '%Credit%'
or issue_description like '%Payment%'
or resolution_description like '%Bill%'
or resolution_description like '%Coupon%'
or resolution_description like '%Transactions%'
or resolution_description like '%Payments%'
or resolution_description like '%AutoPay%'
or resolution_description like '%Autopay%'
or resolution_description like '%Pricing%'
or resolution_description like '%Balance%'
or resolution_description like '%Charges%'
or resolution_description like '%Credit%'
or resolution_description like '%Rewards%'
then 'Customer Education - Billing'
when resolution_description like '%Customer Ed%'
and (resolution_description like '%Equipment%'
or resolution_description like '%Service%'
or resolution_description like '%Device%'
or resolution_description like '%Product%')
then 'Customer Education - Equipment'
when resolution_description like '%Customer Ed%'
and resolution_description like '%App%'
then 'Customer Education - App'
when resolution_description like '%Customer Ed%'
then 'Customer Education - Other'
when resolution_description like '%Escalated%'
and not resolution_description like '%Username%'
then 'Escalated'
when resolution_description like '%Transfer%'
then 'Transferred Call'
when resolution_description like '%Truck%'
then 'Truck Roll'
when resolution_description like '%troubleshoot%'
or resolution_description like '%Troubleshoot%'
then 'Resolved via Troubleshooting'
when resolution_description like '%resolve%'
or resolution_description like '%Resolve%'
then 'Resolved'
when resolution_description like '%Outage%'
then 'Outage'
when resolution_description like '%Auto Pay%'
or resolution_description like '%Payment%'
or resolution_description like '%Promise to Pay%'
then 'Paid Via Phone'
when resolution_description like '%Downgrade%'
then 'Downgraded Services/ Equipment'
when resolution_description like '%Remove%'
then 'Removed Services/ Equipment'
when resolution_description like '%Upgrade%'
or resolution_description like '%Added Services%'
then 'Upgraded Services/ Equipment'
when resolution_description like '%Provisioning%'
then 'Provisioning Change'
when resolution_description like '%Refer%'
then 'Referral'
when resolution_description like '%Time of Arrival%'
or resolution_description like '%Appointment%'
then 'Appointment Related Resolutions'
when resolution_description like '%Office%'
or resolution_description like '%Store%'
then 'Directed to Local Office'
else 'Other'
end as resolution_group
,'retired on 2019-10-19' as version
from cs_dispositions
union
select
distinct
resolution_description
,rd_form
,case
when resolution_description is null
or resolution_description like ''
then 'No Disposition'
when resolution_description like '%Outage%'
then 'Outage'
when resolution_description like '%Investigation%'
or resolution_description like '%Escalat%'
then 'Escalated'
when resolution_description like '%Truck%'
then 'Truck Roll'
when resolution_description like '%troubleshoot%'
or resolution_description like '%Troubleshoot%'
then 'Resolved via Troubleshooting'
when resolution_description like '%Transferred%'
or (resolution_description like '%Transfer%'
and resolution_description not like '%Pay%'
and resolution_description not like '%Customer Ed%'
and resolution_description not like '%Resolved%'
and resolution_description not like '%Complete%'
and resolution_description not like '%Equip%'
and resolution_description not like '%Email%'
and resolution_description not like '%Correctly%')
then 'Transferred Call'
when resolution_description like '%Upgraded%'
or resolution_description like '%Added%'
or resolution_description like '%added%'
then 'Upgraded Services/ Equipment'
when resolution_description like '%Remove%'
and resolution_description not like '%Unable%'
then 'Removed Services/ Equipment'
when (resolution_description like '%resolve%'
or resolution_description like '%Resolve%'
or resolution_description like '%Complete%')
and resolution_description not like '%Not%'
then 'Resolved'
when (resolution_description like '%Store%'
and (resolution_description like '%Refer%'
or resolution_description like '%Pickup%'))
or resolution_description like '%Office%'
then 'Directed to Local Office'
when resolution_description like '%Refer%'
then 'Referral'
when resolution_description like '%Appointment%'
or resolution_description like '%Arrival%'
then 'Appointment Related Resolutions'
when resolution_description like '%Downgrade%'
then 'Downgraded Services/ Equipment'
when resolution_description like '%Provisioning%'
then 'Provisioning Change'
when (resolution_description like '%Customer Ed%'
or resolution_description like '%Explanation%')
and (resolution_description like '%Password%'
or resolution_description like '%Identit%'
or resolution_description like '%Admin%'
or resolution_description like '%Accept%'
or resolution_description like '%User%'
or resolution_description like '%Account%'
or resolution_description like '%House%')
then 'Customer Education - Account'
when (resolution_description like '%Customer Ed%'
or resolution_description like '%Explanation%')
and (resolution_description like '%Bill%'
or resolution_description like '%Pay%'
or resolution_description like '%pay%'
or resolution_description like '%Pricing%'
or resolution_description like '%Charges%'
or resolution_description like '%Credit%'
or resolution_description like '%Balance%'
or resolution_description like '%Rate%')
then 'Customer Education - Billing'
when (resolution_description like '%Customer Ed%'
or resolution_description like '%Explanation%')
and (resolution_description like '%Equipment%'
or resolution_description like '%Compatability%'
or resolution_description like '%Device%'
or resolution_description like '%Router%'
or resolution_description like '%odem%')
then 'Customer Education - Equipment'
when (resolution_description like '%Customer Ed%'
or resolution_description like '%Explanation%')
and resolution_description like '%App%'
then 'Customer Education - App'
when (resolution_description like '%Customer Ed%'
or resolution_description like '%Explanation%')
and (resolution_description like '%Service%'
or resolution_description like '%Product%')
then 'Customer Education - Services'
when resolution_description like '%Customer Ed%'
or resolution_description like '%Explanation%'
then 'Customer Education - Other'
when resolution_description like '%Pay%'
or resolution_description like '%pay%'
or resolution_description like '%Adjust%'
or resolution_description like '%Credit%'
then 'Payments/Adjustments/Credits'
when resolution_description like '%Dropped%'
or resolution_description like '%Released%'
then 'Out of Scope'
else 'Other'
end as resolution_group
,'current' as version
from cs_dispositions;
