.w_msa_onboarding_variables: &w_msa_onboarding_variables
  JOB_NAME: "portals-events-weekly-msa-onboarding"
  W_MSA_ONBOARDING_DIR: "portals-events/weekly-msa-onboarding"
  ARTIFACTS_DIR: "portals-events/weekly-msa-onboarding/artifacts"
  TERRAFORM_DIR: "portals-events/weekly-msa-onboarding/terraform"
  SCRIPTS_DIR: "portals-events/weekly-msa-onboarding/scripts"
  S3_ARTIFACTS_DIR: "portals-events/weekly-msa-onboarding"

w_msa_onboarding_build:
  extends: .build
  variables:
    DDL_DIR: "$W_MSA_ONBOARDING_DIR/ddl"
    HQL_DIR: "$W_MSA_ONBOARDING_DIR/hql"
    <<: *w_msa_onboarding_variables

#STG
w_msa_onboarding_plan_stg:
  extends: .plan_stg
  variables:
    <<: *w_msa_onboarding_variables
  dependencies:
    - w_msa_onboarding_build

w_msa_onboarding_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *w_msa_onboarding_variables
  dependencies:
    - w_msa_onboarding_build
    - w_msa_onboarding_plan_stg

w_msa_onboarding_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *w_msa_onboarding_variables
  dependencies:
    - w_msa_onboarding_build

#PROD
w_msa_onboarding_plan_prod:
  extends: .plan_prod
  variables:
    <<: *w_msa_onboarding_variables
  dependencies:
    - w_msa_onboarding_build

w_msa_onboarding_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *w_msa_onboarding_variables
  dependencies:
    - w_msa_onboarding_build
    - w_msa_onboarding_plan_prod

w_msa_onboarding_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *w_msa_onboarding_variables
  dependencies:
    - w_msa_onboarding_build
