# 02_prod_weekly_resi_quantum job
type=command
dependencies=01_metric_lookup
command=whoami
command.1=/bin/bash -c 'export START_DATE="${START_DATE}"; echo $START_DATE; export PART_DATE="${PART_DATE}"; echo $PART_DATE; export END_DATE="${END_DATE}"; echo $END_DATE; export START_DATE_TZ="${START_DATE_TZ}"; echo $START_DATE_TZ; export PART_DATE_TZ="${PART_DATE_TZ}"; echo $PART_DATE_TZ; export END_DATE_TZ="${END_DATE_TZ}"; echo $END_DATE_TZ; hive -f ../src/02_prod_weekly_resi_quantum.hql'
