# App Aggregation Azkaban Job for My BHN App
type=command
dependencies=01_param_init

command=whoami

#command.1=/bin/bash -c 'export ymd=${YMD}; export ap="${AP}"; export ape="${APE}"; export CADENCE=${CADENCE}; export fm_lkp=${fm_lkp};  export TZ="${TZ}"; export END_DATE_TZ=${END_DATE_TZ}; export START_DATE_TZ=${START_DATE_TZ}; echo $START_DATE_TZ; echo $END_DATE_TZ;  echo $ymd; echo "$ap"; echo "$ape"; echo $CADENCE; echo $fm_lkp;  hive -f src/asp_app_agg_02b_my_bhn.hql'
