# net_agg_calculations job
type=command
dependencies=05_net_agg_calcs
command=whoami
command.1=/bin/bash -c 'export letter=q ; echo $letter; export percentage_metric_name=exit_rate_resi_auth ; echo $percentage_metric_name; export numerator_1=exits_exit_home-authenticated ; echo $numerator_1; export numerator_2='' ; echo $numerator_2; export denominator_1=entries_exit_home-authenticated ; echo $denominator_1; export denominator_2='' ; echo $denominator_2; export CADENCE=${CADENCE} ; echo $CADENCE; export pf=${PF} ; echo $pf; hive -f ../../src/05x_net_agg_calc_param_div.hql '
