USE ${env:ENVIRONMENT};

INSERT INTO TABLE sbnet_exec_monthly_agg_instances PARTITION (year_month='${hiveconf:YEAR_MONTH}')
SELECT
  'Total Combined' as company,
  MAX(hhs_logged_in) as hhs_logged_in,
  MAX(total_hhs) as total_hhs,
  MAX(percent_hhs_logged_in) as percent_hhs_logged_in,
  MAX(unique_hhs_mom_change) as unique_hhs_mom_change,
  MAX(unique_hhs_3month_change) as unique_hhs_3month_change,
  MAX(my_account_page_views) as my_account_page_views,
  MAX(total_login_attempts) as total_login_attempts,
  MAX(total_login_successes) as total_login_successes,
  MAX(percent_login_success) as percent_login_success,
  MAX(rescheduled_service_appointments) as rescheduled_service_appointments,
  MAX(cancelled_service_appointments) as cancelled_service_appointments,
  MAX(support_page_views) as support_page_views,
  MAX(online_statement_views) as online_statement_views,
  MAX(one_time_payment_attempts) as one_time_payment_attempts,
  MAX(one_time_payments) as one_time_payments,
  MAX(percent_one_time_payment_success) as percent_one_time_payment_success,
  MAX(auto_pay_setup_attempts) as auto_pay_setup_attempts,
  MAX(auto_pay_setup_successes) as auto_pay_setup_successes,
  MAX(percent_auto_pay_success) as percent_auto_pay_success,
  MAX(total_account_creation_attempts) as total_account_creation_attempts,
  MAX(total_new_accounts_created) as total_new_accounts_created,
  MAX(percent_total_account_creation_success) as percent_total_account_creation_success,
  MAX(new_account_creation_attempts_on_chtr_network) as new_account_creation_attempts_on_chtr_network,
  MAX(new_accounts_created_on_chtr_network) as new_accounts_created_on_chtr_network,
  MAX(percent_account_creation_success_on_chtr_network) as percent_account_creation_success_on_chtr_network,
  MAX(new_account_creation_attempts_off_chtr_network) as new_account_creation_attempts_off_chtr_network,
  MAX(new_accounts_created_off_chtr_network) as new_accounts_created_off_chtr_network,
  MAX(percent_account_creation_success_off_chtr_network) as percent_account_creation_success_off_chtr_network,
  MAX(total_sub_user_creation_attempts) as total_sub_user_creation_attempts,
  MAX(total_new_sub_users_created) as total_new_sub_users_created,
  MAX(percent_total_sub_user_creation_success) as percent_total_sub_user_creation_success,
  MAX(sub_user_creation_attempts_on_chtr_network) as sub_user_creation_attempts_on_chtr_network,
  MAX(sub_users_created_on_chtr_network) as sub_users_created_on_chtr_network,
  MAX(percent_sub_user_creation_success_on_chtr_network) as percent_sub_user_creation_success_on_chtr_network,
  MAX(sub_user_creation_attempts_off_chtr_network) as sub_user_creation_attempts_off_chtr_network,
  MAX(sub_users_created_off_chtr_network) as sub_users_created_off_chtr_network,
  MAX(percent_sub_user_creation_success_off_chtr_network) as percent_sub_user_creation_success_off_chtr_network,
  MAX(total_username_recovery_attempts) as total_username_recovery_attempts,
  MAX(total_username_recovery_successes) as total_username_recovery_successes,
  MAX(percent_total_username_recovery_success) as percent_total_username_recovery_success,
  MAX(username_recovery_attempts_on_chtr_network) as username_recovery_attempts_on_chtr_network,
  MAX(username_recovery_successes_on_chtr_network) as username_recovery_successes_on_chtr_network,
  MAX(percent_username_recovery_success_on_chtr_network) as percent_username_recovery_success_on_chtr_network,
  MAX(username_recovery_attempts_off_chtr_network) as username_recovery_attempts_off_chtr_network,
  MAX(username_recovery_successes_off_chtr_network) as username_recovery_successes_off_chtr_network,
  MAX(percent_username_recovery_success_off_chtr_network) as percent_username_recovery_success_off_chtr_network,
  MAX(total_attempts_to_reset_password) as total_attempts_to_reset_password,
  MAX(total_successful_password_resets) as total_successful_password_resets,
  MAX(percent_total_password_reset_success) as percent_total_password_reset_success,
  MAX(attempts_to_reset_password_on_chtr_network) as attempts_to_reset_password_on_chtr_network,
  MAX(successful_password_resets_on_chtr_network) as successful_password_resets_on_chtr_network,
  MAX(percent_password_reset_success_on_chtr_network) as percent_password_reset_success_on_chtr_network,
  MAX(attempts_to_reset_password_off_chtr_network) as attempts_to_reset_password_off_chtr_network,
  MAX(successful_password_resets_off_chtr_network) as successful_password_resets_off_chtr_network,
  MAX(percent_password_reset_success_off_chtr_network) as percent_password_reset_success_off_chtr_network
FROM ${env:TMP_db}.sbnet_exec_monthly_agg_totals_instances
;

INSERT INTO TABLE sbnet_exec_monthly_agg_visits PARTITION (year_month='${hiveconf:YEAR_MONTH}')
SELECT
  'Total Combined' as company,
  MAX(hhs_logged_in) as hhs_logged_in,
  MAX(total_hhs) as total_hhs,
  MAX(percent_hhs_logged_in) as percent_hhs_logged_in,
  MAX(unique_hhs_mom_change) as unique_hhs_mom_change,
  MAX(unique_hhs_3month_change) as unique_hhs_3month_change,
  MAX(my_account_page_views) as my_account_page_views,
  MAX(total_login_attempts) as total_login_attempts,
  MAX(total_login_successes) as total_login_successes,
  MAX(percent_login_success) as percent_login_success,
  MAX(rescheduled_service_appointments) as rescheduled_service_appointments,
  MAX(cancelled_service_appointments) as cancelled_service_appointments,
  MAX(support_page_views) as support_page_views,
  MAX(online_statement_views) as online_statement_views,
  MAX(one_time_payment_attempts) as one_time_payment_attempts,
  MAX(one_time_payments) as one_time_payments,
  MAX(percent_one_time_payment_success) as percent_one_time_payment_success,
  MAX(auto_pay_setup_attempts) as auto_pay_setup_attempts,
  MAX(auto_pay_setup_successes) as auto_pay_setup_successes,
  MAX(percent_auto_pay_success) as percent_auto_pay_success,
  MAX(total_account_creation_attempts) as total_account_creation_attempts,
  MAX(total_new_accounts_created) as total_new_accounts_created,
  MAX(percent_total_account_creation_success) as percent_total_account_creation_success,
  MAX(new_account_creation_attempts_on_chtr_network) as new_account_creation_attempts_on_chtr_network,
  MAX(new_accounts_created_on_chtr_network) as new_accounts_created_on_chtr_network,
  MAX(percent_account_creation_success_on_chtr_network) as percent_account_creation_success_on_chtr_network,
  MAX(new_account_creation_attempts_off_chtr_network) as new_account_creation_attempts_off_chtr_network,
  MAX(new_accounts_created_off_chtr_network) as new_accounts_created_off_chtr_network,
  MAX(percent_account_creation_success_off_chtr_network) as percent_account_creation_success_off_chtr_network,
  MAX(total_sub_user_creation_attempts) as total_sub_user_creation_attempts,
  MAX(total_new_sub_users_created) as total_new_sub_users_created,
  MAX(percent_total_sub_user_creation_success) as percent_total_sub_user_creation_success,
  MAX(sub_user_creation_attempts_on_chtr_network) as sub_user_creation_attempts_on_chtr_network,
  MAX(sub_users_created_on_chtr_network) as sub_users_created_on_chtr_network,
  MAX(percent_sub_user_creation_success_on_chtr_network) as percent_sub_user_creation_success_on_chtr_network,
  MAX(sub_user_creation_attempts_off_chtr_network) as sub_user_creation_attempts_off_chtr_network,
  MAX(sub_users_created_off_chtr_network) as sub_users_created_off_chtr_network,
  MAX(percent_sub_user_creation_success_off_chtr_network) as percent_sub_user_creation_success_off_chtr_network,
  MAX(total_username_recovery_attempts) as total_username_recovery_attempts,
  MAX(total_username_recovery_successes) as total_username_recovery_successes,
  MAX(percent_total_username_recovery_success) as percent_total_username_recovery_success,
  MAX(username_recovery_attempts_on_chtr_network) as username_recovery_attempts_on_chtr_network,
  MAX(username_recovery_successes_on_chtr_network) as username_recovery_successes_on_chtr_network,
  MAX(percent_username_recovery_success_on_chtr_network) as percent_username_recovery_success_on_chtr_network,
  MAX(username_recovery_attempts_off_chtr_network) as username_recovery_attempts_off_chtr_network,
  MAX(username_recovery_successes_off_chtr_network) as username_recovery_successes_off_chtr_network,
  MAX(percent_username_recovery_success_off_chtr_network) as percent_username_recovery_success_off_chtr_network,
  MAX(total_attempts_to_reset_password) as total_attempts_to_reset_password,
  MAX(total_successful_password_resets) as total_successful_password_resets,
  MAX(percent_total_password_reset_success) as percent_total_password_reset_success,
  MAX(attempts_to_reset_password_on_chtr_network) as attempts_to_reset_password_on_chtr_network,
  MAX(successful_password_resets_on_chtr_network) as successful_password_resets_on_chtr_network,
  MAX(percent_password_reset_success_on_chtr_network) as percent_password_reset_success_on_chtr_network,
  MAX(attempts_to_reset_password_off_chtr_network) as attempts_to_reset_password_off_chtr_network,
  MAX(successful_password_resets_off_chtr_network) as successful_password_resets_off_chtr_network,
  MAX(percent_password_reset_success_off_chtr_network) as percent_password_reset_success_off_chtr_network
FROM ${env:TMP_db}.sbnet_exec_monthly_agg_totals_visits
;