# Groovy test job
type=Groovy

groovy.command.1=println 'This job runs each Tableau Email jobs for daily asp reporting'
groovy.command.2=import azkaban.executor.*
groovy.command.3=azkaban.execute("asp_daily_operational_email_specnet", "tableau_email_dist_end")
groovy.command.4=azkaban.execute("asp_daily_operational_email_smb", "tableau_email_dist_end")
groovy.command.5=azkaban.execute("asp_daily_operational_email_msa", "tableau_email_dist_end")
