type=command

command=/bin/bash -c '/data/opt/spark/spark-2.3.1-bin-Spectrum-Spark/bin/spark-shell --executor-memory=28G --num-executors=64 --driver-memory=16G --jars ../jars/hadoop-libs-hive-1.0.5_scala-2.11.8.jar --queue azkaban_backfill -i ../src/ani/legacy_backfill_script.scala'

failure.emails=steven.naumann@charter.com, Sarah.Fields@charter.com, C-Amanda.Ramsay@charter.com
success.emails=steven.naumann@charter.com, Sarah.Fields@charter.com, C-Amanda.Ramsay@charter.com