type=command

command=/bin/bash -c '/data/opt/spark/spark-2.3.1-bin-Spectrum-Spark/bin/spark-shell --executor-memory=28G --num-executors=64 --driver-memory=8G --jars ../jars/hadoop-libs-hive-1.0.5_scala-2.11.8.jar -i ../src/ani/pageview_call_in_rate_daily.scala'

failure.emails=c_amayak.urumyan@charter.com, steven.naumann@charter.com, Sarah.Fields@charter.com, C-Amanda.Ramsay@charter.com
success.emails=c_amayak.urumyan@charter.com, steven.naumann@charter.com, Sarah.Fields@charter.com, C-Amanda.Ramsay@charter.com