#  Azkaban job
type=command
command=whoami

command.1=/bin/bash -c 'export execid=${azkaban.flow.execid}; echo $execid; export domain=${domain}; echo $domain; export project=${project}; echo $project;  echo $execid; export domain=${domain}; echo $domain; export project=${project}; echo $project; echo $ProcessUser;  export FLOW_BACKFILL=backfill; echo $FLOW_BACKFILL; hive -f ../../../src/portals_privacysite_set_agg_tableset.hql '
