#!/usr/bin/env groovy
@Library('jenkins-util') _      // don't miss the '_' at the end of the line
PIDeliveryPipeline {
    azkabanProjectName = "asp_extract_parameterized_billing_agg" // required
    azkabanEnv = 'dev'          // optional, default to dev
    azkabanProjectDesc = "Portals billing agg" // required
    azkabanProjectOwner = 'jdutczak' // required, put your AD login here
    azkabanPlatform = 'ASP'     // required
    azkabanEscalation = 'Marjorie Truitt' // required, one of ['Andrew Ngeow', 'Yong Liu', 'Ty Prinkki', 'Marjorie Truitt', 'Micheal Baldino', 'Nate Vogel']
    azkabanSLA = 'Optional - Next Day' // required, one of ['Optional - Next Day', 'Important - Within 12 hrs', 'Critical - Immediate Response']
    azkabanFlowRun=[]           // not implemented, could have loop here too
    azkabanProdFlowSchedule=[]
    gitDir='extract/parameterized/portals_billing_agg'  // the sub dir where your project dir is
}
