.si_initiate_metric_agg_variables: &si_initiate_metric_agg_variables
  JOB_NAME: "si-initiate-metric-agg"
  SI_INITIATE_METRIC_AGG_DIR: "cs-jobs/si-initiate-metric-agg"
  ARTIFACTS_DIR: "cs-jobs/si-initiate-metric-agg/artifacts"
  TERRAFORM_DIR: "cs-jobs/si-initiate-metric-agg/terraform"
  SCRIPTS_DIR: "cs-jobs/si-initiate-metric-agg/scripts"
  S3_ARTIFACTS_DIR: "cs-jobs/si-initiate-metric-agg"

si_initiate_metric_agg_build:
  extends: .build
  variables:
    DDL_DIR: "$SI_INITIATE_METRIC_AGG_DIR/ddl"
    HQL_DIR: "$SI_INITIATE_METRIC_AGG_DIR/hql"
    <<: *si_initiate_metric_agg_variables

#STG
si_initiate_metric_agg_plan_stg:
  extends: .plan_stg
  variables:
    <<: *si_initiate_metric_agg_variables
  dependencies:
    - si_initiate_metric_agg_build

si_initiate_metric_agg_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *si_initiate_metric_agg_variables
  dependencies:
    - si_initiate_metric_agg_build
    - si_initiate_metric_agg_plan_stg

si_initiate_metric_agg_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *si_initiate_metric_agg_variables
  dependencies:
    - si_initiate_metric_agg_build

#PROD
si_initiate_metric_agg_plan_prod:
  extends: .plan_prod
  variables:
    <<: *si_initiate_metric_agg_variables
  dependencies:
    - si_initiate_metric_agg_build

si_initiate_metric_agg_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *si_initiate_metric_agg_variables
  dependencies:
    - si_initiate_metric_agg_build
    - si_initiate_metric_agg_plan_prod

si_initiate_metric_agg_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *si_initiate_metric_agg_variables
  dependencies:
    - si_initiate_metric_agg_build
