#!/usr/bin/env groovy
@Library('jenkins-util') _    // don't miss the '_' at the end of the line, this is the magical library that does the, uh, 'magic'
PIDeliveryPipeline {
    azkabanProjectName = "asp_ingest_app_my_twc" // required
    azkabanEnv = 'prod' // optional, default to dev
    azkabanProjectDesc = "Ingests Adobe Omniture data for My TWC App Production Suite" // required
    azkabanProjectOwner = 'eeasterly' // required, put your AD login here
    azkabanPlatform = 'ASP'  // required
    azkabanEscalation = 'Andrew Ngeow' // required, one of ['Andrew Ngeow', 'Yong Liu', 'Ty Prinkki', 'Marjorie Truitt', 'Micheal Baldino', 'Nate Vogel']
    azkabanSLA = 'Critical - Immediate Response' // required, one of ['Optional - Next Day', 'Important - Within 12 hrs', 'Critical - Immediate Response']
    azkabanFlowRun=[] // not implemented, could have loop here too
    azkabanProdFlowSchedule=[flowName:'asp_ingest_app_my_twc_end', cronExpression:'0 03 09 ? * *']
    gitDir='ingest/apps/my_twc'  // the sub dir where your project dir is
}
