#  Azkaban job
type=command
dependencies=01_param_init_rw
type=command
command=whoami

command.1=/bin/bash -c 'export START_DATE="${START_DATE}"; echo $START_DATE; export END_DATE="${END_DATE}"; echo $END_DATE;  export label_date_denver="${LABEL_DATE_DENVER}"; echo $label_date_denver; export grain="${GRAIN}"; echo $grain; export FLOW_BACKFILL="${FLOW_BACKFILL}"; echo $FLOW_BACKFILL; export ProcessTimestamp="${ProcessTimestamp}"; echo $ProcessTimestamp; export ProcessUser="${azkaban.flow.submituser}"; echo $ProcessUser;  hive -f ../../../src/portals_billing_agg.hql'
