CREATE EXTERNAL TABLE IF NOT EXISTS ${db_name}.asp_m2dot0_metric_agg
(
  visit__application_details__application_name STRING,
  visit__application_details__application_type STRING,
  visit__application_details__app_version STRING,
  agg_CUSTOM_visit__account__details__service_subscriptions STRING,
  agg_visit__account__configuration_factors STRING,
  agg_custom_customer_group STRING,
  agg_visit__account__details__mso string,
  portals_unique_acct_key string,
  visit__account__enc_mobile_account_number STRING,
  visit_id STRING,
  visit__visit_start_timestamp bigint,
  device_id string,

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
  AP_enroll_abandon_core INT,
  AP_enroll_failure_core INT,
  AP_enroll_start_core INT,
  AP_enroll_submit_core INT,
  AP_enroll_success_core INT,
  AP_manage_failure INT,
  AP_manage_start INT,
  AP_manage_success INT,
  CPNI_cancel INT,
  CPNI_failure INT,
  CPNI_failure_IMEI INT,
  CPNI_failure_email INT,
  CPNI_failure_mac_address INT,
  CPNI_failure_security_code INT,
  CPNI_start INT,
  CPNI_start_modalView INT,
  CPNI_start_pageView INT,
  CPNI_submit INT,
  CPNI_submit_IMEI INT,
  CPNI_submit_email INT,
  CPNI_submit_mac_address INT,
  CPNI_submit_security_code INT,
  CPNI_success INT,
  CPNI_success_IMEI INT,
  CPNI_success_email INT,
  CPNI_success_mac_address INT,
  CPNI_success_security_code INT,
  OTP_failure_core INT,
  OTP_failure_core_full INT,
  OTP_failure_core_quickPay INT,
  OTP_failure_legacy INT,
  OTP_failure_mobile INT,
  OTP_failure_mobile_full INT,
  OTP_failure_mobile_quickPay INT,
  OTP_start_core INT,
  OTP_start_core_full INT,
  OTP_start_core_quickPay INT,
  OTP_start_legacy INT,
  OTP_start_mobile INT,
  OTP_start_mobile_full INT,
  OTP_start_mobile_quickPay INT,
  OTP_start_modal INT,
  OTP_submit_core INT,
  OTP_submit_core_full INT,
  OTP_submit_core_quickPay INT,
  OTP_submit_legacy INT,
  OTP_submit_mobile INT,
  OTP_submit_mobile_full INT,
  OTP_submit_mobile_quickPay INT,
  OTP_success_core INT,
  OTP_success_core_full INT,
  OTP_success_core_quickPay INT,
  OTP_success_legacy INT,
  OTP_success_mobile INT,
  OTP_success_mobile_full INT,
  OTP_success_mobile_quickPay INT,
  device_make_payment_failure INT,
  device_make_payment_start INT,
  device_make_payment_submit INT,
  device_make_payment_success INT,
  login_attempt INT,
  login_failure INT,
  login_success INT,
  mobile_activation_activation_complete INT,
  mobile_activation_activation_in_progress INT,
  mobile_activation_transfer_complete INT,
  mobile_activation_transfer_in_progress INT,
  mobile_activation_unable_to_activate INT,
  mobile_activation_unable_to_transfer INT,
  mobile_change_plan_start INT,
  mobile_confirm_change_plan INT,
  mobile_device_upgrade INT,
  mobile_success_change_plan INT,
  mobile_tier_upgrade_review INT,
  mobile_tier_upgrade_start INT,
  mobile_tier_upgrade_submit INT,
  mobile_tier_upgrade_success INT,
  page_load_billing INT,
  page_load_billing_hot_2000 INT,
  page_load_billing_hot_3000 INT,
  page_load_home INT,
  page_load_home_hot_2000 INT,
  page_load_home_hot_3000 INT,
  payment_method_add_failure_mobile INT,
  payment_method_add_success_mobile INT,
  payment_method_delete_failure_mobile INT,
  payment_method_delete_success_mobile INT,
  payment_method_edit_failure_mobile INT,
  payment_method_edit_success_mobile INT,
  portals_csat_submit_rating_1_very_dissatisfied INT,
  portals_csat_submit_rating_2_dissatisfied INT,
  portals_csat_submit_rating_3_neutral INT,
  portals_csat_submit_rating_4_satisfied INT,
  portals_csat_submit_rating_5_very_satisfied INT,
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
calls_within_24_hrs INT
)

PARTITIONED BY (partition_date_utc STRING)
STORED AS ORC
LOCATION '${s3_location}'
TBLPROPERTIES ('orc.compress'='SNAPPY',
               'retention_policy'='Aggregate - With PII (3 Years)');
