set hive.vectorized.execution.enabled = false;

USE prod;

DROP TABLE IF EXISTS ${env:TMP_db}.asp_venona_counts_daily_counts_instances_columns;
CREATE TEMPORARY TABLE ${env:TMP_db}.asp_venona_counts_daily_counts_instances_columns AS
    SELECT
        COALESCE (visit__account__details__mso,'Unknown') as company,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__page_name) = LOWER('billing-and-transactions')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('ask-spectrum') , 1, 0)) AS ask_spectrum_from_billing_post,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('ask-spectrum')   AND LOWER(state__view__current_page__page_name) = LOWER('my-internet-services') , 1, 0)) AS ask_spectrum_from_my_internet_services,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('ask-spectrum')   AND LOWER(state__view__current_page__page_name) = LOWER('my-tv-services') , 1, 0)) AS ask_spectrum_from_my_tv_services,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('ask-spectrum')   AND LOWER(state__view__current_page__page_name) = LOWER('my-voice-services') , 1, 0)) AS ask_spectrum_from_my_voice_services,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) = LOWER('home-authenticated') , 1, 0)) AS auth_homepage_page_views,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('featureStop')   AND LOWER(message__feature__feature_name) IN (LOWER('autoPayEnrollment'),LOWER('manageAutoPay'))   AND operation__success IS NULL   AND LOWER(message__event_case_id) NOT RLIKE LOWER('.*Cancelled.*') , 1, 0)) AS set_up_auto_payment_failures,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND (message__event_case_id IN ('SPECNET_billPay_billPayStop_autopayEnrolled_triggeredByApplicationSuccess', 'SPECNET_billPay_billPayStop_autopayEnrollmentWithPayment_triggeredByApplicationSuccess')) , 1, 0)) AS set_up_auto_payment_successes,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('pay-bill.enroll-in-autopay-no-balance-checking'),LOWER('pay-bill.enroll-in-autopay-no-balance-savings'),LOWER('pay-bill.enroll-in-autopay-no-balance-credit'),LOWER('pay-bill.enroll-in-autopay-with-balance-credit'),LOWER('pay-bill.enroll-in-autopay-with-balance-checking'),LOWER('pay-bill.enroll-in-autopay-with-balance-savings')) , 1, 0)) AS autopay_confirmation_post,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) = LOWER('home-authenticated')   AND visit__account__details__billing_status RLIKE '.*bp:autopay.*' , 1, 0)) AS autopay_is_enabled,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) = LOWER('home-authenticated')   AND visit__account__details__billing_status RLIKE '.*bp:no-autopay.*' , 1, 0)) AS autopay_is_not_enabled,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('featureStart')   AND LOWER(message__feature__feature_name) = LOWER('autoPayEnrollment') , 1, 0)) AS autopay_step1_post,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('pay-bill.view-bill-details-hp'),LOWER('pay-bill.enroll-in-autopay-hp'),LOWER('pay-bill.make-a-payment-hp')) , 1, 0)) AS bill_pay_clicks_from_bill_pay_card_on_hp,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__page_name) = LOWER('home-authenticated')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('localNav-billing') , 1, 0)) AS bill_pay_clicks_from_local_nav,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('pay-bill.enroll-in-autopay-no-balance-checking'),LOWER('pay-bill.enroll-in-autopay-no-balance-savings'),LOWER('pay-bill.enroll-in-autopay-no-balance-credit'),LOWER('pay-bill.enroll-in-autopay-with-balance-credit'),LOWER('pay-bill.enroll-in-autopay-with-balance-checking'),LOWER('pay-bill.enroll-in-autopay-with-balance-savings')) , 1, 0)) AS bill_flow_ap_step1,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('featureStop')   AND LOWER(message__feature__feature_name) IN (LOWER('autoPayEnrollment'),LOWER('manageAutoPay'))   AND LOWER(operation__success) = LOWER('True')   AND LOWER(message__feature__feature_step_name) <> LOWER('autopayChangesConfirmation') , 1, 0)) AS bill_flow_ap_step2_confirm,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) RLIKE LOWER('pay-bill.onetime.payment-amount.*') , 1, 0)) AS bill_flow_otp_step1,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) RLIKE LOWER('pay-bill.onetime.payment-date.continue.*') , 1, 0)) AS bill_flow_otp_step2,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('pay-bill.onetime.payment-method.credit'),LOWER('pay-bill.onetime.payment-method.checking'),LOWER('pay-bill.onetime.payment-method.savings')) , 1, 0)) AS bill_flow_otp_step3,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('pay-bill.onetime.payment-review.make-payment'),LOWER('pay-bill.onetime.payment-review.pay-and-enroll')) , 1, 0)) AS bill_flow_otp_step4,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('featureStop')   AND LOWER(message__feature__feature_name) = LOWER('oneTimeBillPayFlow')   AND LOWER(operation__success) = LOWER('True') , 1, 0)) AS bill_flow_otp_step5_confirm,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) = LOWER('home-authenticated')   AND visit__account__details__billing_status RLIKE '.*pastDue-no.*' , 1, 0)) AS bill_status_past_due_no,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) = LOWER('home-authenticated')   AND visit__account__details__billing_status RLIKE '.*pastDue-yes.*' , 1, 0)) AS bill_status_past_due_yes,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('apiCall')   AND LOWER(application__api__api_name) = LOWER('serviceapptedgeV1AppointmentsCancel') , 1, 0)) AS cancelled_service_appointments,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('featureStop')   AND LOWER(message__feature__feature_name) = LOWER('oneTimeBillPayFlow')   AND LOWER(operation__success) = LOWER('True') , 1, 0)) AS combined_payment_successes,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) = LOWER('contactUs') , 1, 0)) AS contact_us_page_views,
        SUM(IF( FALSE, 1, 0)) AS create_username_referred_from_msa,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND visit__device__operating_system RLIKE '.*iOS|Android.*' , 1, 0)) AS site_unique_mobile,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND visit__device__operating_system NOT RLIKE '.*iOS|Android.*' , 1, 0)) AS site_unique_pc,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN ('equip.internet.troubleshoot.reset-equip.cancel') , 1, 0)) AS ed_equip_internet_troubleshoot_reset_equip_cancel,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('equip.internet.troubleshoot.reset-equip.reset-failure-modal-continues')) , 1, 0)) AS ed_equip_internet_troubleshoot_reset_equip_reset_failure_modal_continue,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN ('equip.internet.troubleshoot.reset-equip.start') , 1, 0)) AS ed_equip_internet_troubleshoot_reset_equip_start,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN ('equip.internet.troubleshoot.reset-equip.success-modal-continue') , 1, 0)) AS ed_equip_internet_troubleshoot_reset_equip_success_modal_continue,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('support-category.internet.reset-modem.issue-resolved')) , 1, 0)) AS ed_equip_internet_troubleshoot_reset_equip_success_modal_issue_resolved,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN ('equip.tv.troubleshoot.reset-equip.cancel') , 1, 0)) AS ed_equip_tv_troubleshoot_reset_equip_cancel,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('equip.tv.troubleshoot.reset-equip.reset-failure-modal-continue')) , 1, 0)) AS ed_equip_tv_troubleshoot_reset_equip_reset_failure_modal_continue,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN ('equip.tv.troubleshoot.reset-equip.start') , 1, 0)) AS ed_equip_tv_troubleshoot_reset_equip_start,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN ('equip.tv.troubleshoot.reset-equip.success-modal-continue') , 1, 0)) AS ed_equip_tv_troubleshoot_reset_equip_success_modal_continue,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('support-category.tv.reset-equip.issue-resolved')) , 1, 0)) AS ed_equip_tv_troubleshoot_reset_equip_success_modal_issue_resolved,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN ('equip.voice.troubleshoot.reset-equip.cancel') , 1, 0)) AS ed_equip_voice_troubleshoot_reset_equip_cancel,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('equip.voice.troubleshoot.reset-equip.reset-failure-modal-continue')) , 1, 0)) AS ed_equip_voice_troubleshoot_reset_equip_reset_failure_modal_continue,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN ('equip.voice.troubleshoot.reset-equip.start') , 1, 0)) AS ed_equip_voice_troubleshoot_reset_equip_start,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN ('equip.voice.troubleshoot.reset-equip.success-modal-continue') , 1, 0)) AS ed_equip_voice_troubleshoot_reset_equip_success_modal_continue,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('support-category.voice.reset-equip.issue-resolved')) , 1, 0)) AS ed_equip_voice_troubleshoot_reset_equip_success_modal_issue_resolved,
        SUM(IF( LOWER(state__view__current_page__app_section) IN (LOWER('tv'),LOWER('voice'),LOWER('internet'))  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__app_section) = LOWER('support') , 1, 0)) AS equipment_page_views,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) IN ('reset-equipment-tv-failure', 'reset-equipment-voice-failure', 'reset-equipment-internet-failure') , 1, 0)) AS all_equipment_reset_flow_failures,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) =  'reset-equipment-internet-failure' , 1, 0)) AS internet_equipment_reset_flow_failures,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) =  'reset-equipment-tv-failure' , 1, 0)) AS tv_equipment_reset_flow_failures,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) =  'reset-equipment-voice-failure' , 1, 0)) AS voice_equipment_reset_flow_failures,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN ('equipment.internet.troubleshoot', 'equipment.tv.troubleshoot', 'equipment.voice.troubleshoot') , 1, 0)) AS all_equipment_reset_flow_starts,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = 'equipment.internet.troubleshoot' , 1, 0)) AS internet_equipment_reset_flow_starts,
        SUM(IF( LOWER(visit__application_details__application_name) = 'specnet'  AND message__name = 'modalView'   AND message__feature__feature_name = 'tvTroubleshoot'   AND message__feature__feature_step_name = 'resetSuccessModal'   AND state__view__modal__name = 'Reset-Equipment-Success' , 1, 0)) AS tv_equipment_reset_flow_starts,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) =  'equipment.voice.troubleshoot' , 1, 0)) AS voice_equipment_reset_flow_starts,
        SUM(IF( LOWER(visit__application_details__application_name) = 'specnet'  AND message__name = 'modalView'   AND message__feature__feature_name IN( 'internetTroubleshoot', 'tvTroubleshoot', 'voiceTroubleshoot')   AND message__feature__feature_step_name = 'resetSuccessModal'   AND state__view__modal__name = 'Reset-Equipment-Success' , 1, 0)) AS all_equipment_reset_flow_successes,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) =  'reset-equipment-internet-success' , 1, 0)) AS internet_equipment_reset_flow_successes,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) =  'reset-equipment-tv-success' , 1, 0)) AS tv_equipment_reset_flow_successes,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) =  'reset-equipment-voice-success' , 1, 0)) AS voice_equipment_reset_flow_successes,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-manageAccount-accountSummary') , 1, 0)) AS footer_manageaccount_account_summary,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-getSupport-accountSupport') , 1, 0)) AS footer_getsupport_acct_support,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-manageAccount-billing') , 1, 0)) AS footer_manageaccount_billing,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-legal-californiaPrivacyRights') , 1, 0)) AS footer_legal_ca_privacy_rights,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-contact-contactUs') , 1, 0)) AS footer_contactus_contact_us,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-disabilityAssistance') , 1, 0)) AS footer_disability_assistance,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-social-facebook') , 1, 0)) AS footer_social_facebook,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-contact-findStore') , 1, 0)) AS footer_contactus_find_spectrum_store,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-contact-websiteFeedback') , 1, 0)) AS footer_contactus_give_website_feedback,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-legal-goToAssist') , 1, 0)) AS footer_legal_go_to_assist,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-watchTV-guide') , 1, 0)) AS footer_watchtv_guide,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-social-instagram') , 1, 0)) AS footer_social_instagram,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-manageAccount-internet') , 1, 0)) AS footer_getsupport_internet,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-manageAccount-internet') , 1, 0)) AS footer_manageaccount_internet,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-watchTV-liveTV') , 1, 0)) AS footer_watchtv_live_tv,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-manageAccount-mobile') , 1, 0)) AS footer_manageaccount_mobile,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-watchTV-myLibrary') , 1, 0)) AS footer_watchtv_my_library,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-watchTV-onDemand') , 1, 0)) AS footer_watchtv_on_demand,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-legal-policies') , 1, 0)) AS footer_legal_policies,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-legal-privacyRights') , 1, 0)) AS footer_legal_privacy_rights,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-manageAccount-settings') , 1, 0)) AS footer_manageaccount_settings,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-getSupport-supportHome') , 1, 0)) AS footer_getsupport_support_home,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-manageAccount-tv') , 1, 0)) AS footer_getsupport_tv,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-manageAccount-tv') , 1, 0)) AS footer_manageaccount_tv,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-watchTV-dvr') , 1, 0)) AS footer_watchtv_dvr,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-social-twitter') , 1, 0)) AS footer_social_twitter,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-manageAccount-voice') , 1, 0)) AS footer_getsupport_voice,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-manageAccount-voice') , 1, 0)) AS footer_manageaccount_voice,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-contact-weatherOutage') , 1, 0)) AS footer_contactus_weather_outage,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('footer-social-youtube') , 1, 0)) AS footer_social_youtube,
        SUM(IF( FALSE, 1, 0)) AS forgot_password_referred_from_msa,
        SUM(IF( FALSE, 1, 0)) AS forgot_username_referred_from_msa,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('internetAddService') , 1, 0)) AS from_homepage_banner_internet,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('tvAddService') , 1, 0)) AS from_homepage_banner_tv,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('voiceAddService') , 1, 0)) AS from_homepage_banner_voice,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) = LOWER('my-internet-services')   AND LOWER(state__view__previous_page__app_section) = LOWER('support') , 1, 0)) AS from_support_internet,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) = LOWER('my-tv-services')   AND LOWER(state__view__previous_page__app_section) = LOWER('support') , 1, 0)) AS from_support_tv,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) = LOWER('my-voice-services')   AND LOWER(state__view__previous_page__app_section) = LOWER('support') , 1, 0)) AS from_support_voice,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('hamburger-closeSideNav') , 1, 0)) AS hamburger_closesidenav,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('hamburger-createUsername') , 1, 0)) AS hamburger_create_username,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('hamburger-email') , 1, 0)) AS hamburger_email,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('hamburger-getSupport') , 1, 0)) AS hamburger_get_support,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('hamburger-manageAccount') , 1, 0)) AS hamburger_manage_account,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('hamburger-signin') , 1, 0)) AS hamburger_signin,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('hamburger-signout') , 1, 0)) AS hamburger_signout,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('hamburger-voice') , 1, 0)) AS hamburger_voice,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('hamburger-watchTV') , 1, 0)) AS hamburger_watch_tv,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('ask-spectrum'),LOWER('askSpectrumNextIT'),LOWER('askSpectrumASAPP')) , 1, 0)) AS iva_opens,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('localNav-accountSummary') , 1, 0)) AS localnav_acct_summary,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('localNav-billing') , 1, 0)) AS localnav_billing,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('localNav-internet') , 1, 0)) AS localnav_internet,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('localNav-settings') , 1, 0)) AS localnav_settings,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('localNav-tv') , 1, 0)) AS localnav_tv,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('localNav-voice') , 1, 0)) AS localnav_voice,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('loginStop') , 1, 0)) AS login_attempts,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('support-category.voice.reset-equip.contact-us'),LOWER('support-category.internet.reset-equip.contact-us'),LOWER('support-category.tv.reset-equip.contact-us')) , 1, 0)) AS manual_reset_failures,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) IN (LOWER('my-voice-services.manually-reset-equipment'),LOWER('my-tv-services.manually-reset-equipment'),LOWER('my-internet-services.manually-reset-equipment')) , 1, 0)) AS manual_reset_starts,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('support-category.tv.reset-equip.issue-resolved'),LOWER('support-category.voice.reset-equip.issue-resolved'),LOWER('support-category.internet.reset-modem.issue-resolved')) , 1, 0)) AS manual_reset_success,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) IN (LOWER('my-voice-services.manually-reset-equipment'),LOWER('my-tv-services.manually-reset-equipment'),LOWER('my-internet-services.manually-reset-equipment')) , 1, 0)) AS manual_troubleshoot_page_views,
        SUM(IF( FALSE, 1, 0)) AS internet_modem_reset_failures,
        SUM(IF( FALSE, 1, 0)) AS voice_modem_reset_failures,
        SUM(IF( FALSE, 1, 0)) AS internet_modem_reset_successes,
        SUM(IF( FALSE, 1, 0)) AS voice_modem_reset_successes,
        SUM(IF( FALSE, 1, 0)) AS internet_modem_router_reset_starts,
        SUM(IF( FALSE, 1, 0)) AS voice_modem_router_reset_starts,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__app_section) IN (LOWER('tv'),LOWER('voice'),LOWER('internet'))   AND LOWER(state__view__current_page__page_name) IN (LOWER('my-internet-services')) , 1, 0)) AS ed_my_internet_services,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) IN (LOWER('my-internet-services.contact-us')) , 1, 0)) AS ed_my_internet_services_contact_us,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) IN (LOWER('my-internet-services.manually-reset-equipment')) , 1, 0)) AS ed_my_internet_services_manually_reset_equipment,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__app_section) IN (LOWER('tv'),LOWER('voice'),LOWER('internet'))   AND LOWER(state__view__current_page__page_name) IN (LOWER('my-tv-services')) , 1, 0)) AS ed_my_tv_services,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) IN (LOWER('my-tv-services.contact-us')) , 1, 0)) AS ed_my_tv_services_contact_us,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) IN (LOWER('my-tv-services.manually-reset-equipment')) , 1, 0)) AS ed_my_tv_services_manually_reset_equipment,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__app_section) IN (LOWER('tv'),LOWER('voice'),LOWER('internet'))   AND LOWER(state__view__current_page__page_name) IN (LOWER('my-internet-services.contact-us'),LOWER('my-voice-services')) , 1, 0)) AS ed_my_voice_services,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) IN (LOWER('my-voice-services.contact-us')) , 1, 0)) AS ed_my_voice_services_contact_us,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) IN (LOWER('my-voice-services.manually-reset-equipment')) , 1, 0)) AS ed_my_voice_services_manually_reset_equipment,
        SUM(IF( FALSE, 1, 0)) AS new_ids_created_attempts,
        SUM(IF( FALSE, 1, 0)) AS new_ids_created_successes,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('featureStop')   AND LOWER(message__feature__feature_name) = LOWER('oneTimeBillPayFlow')   AND operation__success IS NULL   AND LOWER(message__feature__feature_step_name) = LOWER('oneTimePaymentError') , 1, 0)) AS one_time_payment_failures,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('featureStart')   AND LOWER(message__feature__feature_name) = LOWER('oneTimeBillPayFlow') , 1, 0)) AS one_time_payment_starts,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND message__name = 'featureStop' AND message__feature__feature_name IN ('oneTimeBillPayFlow', 'oneTimePayment') AND operation__success = TRUE AND ((message__feature__feature_step_changed = FALSE AND message__event_case_id <> 'SPECNET_selectAction_billPayStop_otp_exitBillPayFlow') OR (message__feature__feature_step_name IN ('oneTimePaymentAppSuccess','oneTimePaymentAutoPayAppSuccess', 'paymentWithAutoPaySuccess', 'paymentSuccess') AND message__feature__feature_step_changed = TRUE)) , 1, 0)) AS one_time_payment_successes,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('featureStop')   AND LOWER(message__feature__feature_name) = LOWER('oneTimeBillPayFlow')   AND LOWER(message__feature__feature_step_name) = ('oneTimePaymentAutoPayError')   AND message__feature__feature_step_changed IS NOT NULL , 1, 0)) AS otp_with_autopay_failures,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND message__name = 'featureStop' AND message__feature__feature_name IN ('oneTimeBillPayFlow', 'oneTimePayment') AND operation__success = TRUE AND message__feature__feature_step_name IN ('oneTimePaymentAutoPayAppSuccess', 'paymentWithAutoPaySuccess') AND message__feature__feature_step_changed = TRUE , 1, 0)) AS otp_with_autopay_successes,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) = LOWER('home-authenticated')   AND visit__account__details__billing_status RLIKE '.*pl:pl-yes.*' , 1, 0)) AS paperless_billing_is_enabled,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) = LOWER('home-authenticated')   AND visit__account__details__billing_status RLIKE '.*pl:pl-no.*' , 1, 0)) AS paperless_billing_is_not_enabled,
        SUM(IF( FALSE, 1, 0)) AS password_reset_attempts,
        SUM(IF( FALSE, 1, 0)) AS password_reset_successes,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) IN ('Progress-Bar-Modal-Internet') , 1, 0)) AS ed_progress_bar_modal_internet,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) IN ('Progress-Bar-Modal-TV') , 1, 0)) AS ed_progress_bar_modal_tv,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) IN ('Progress-Bar-Modal-Voice') , 1, 0)) AS ed_progress_bar_modal_voice,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('apiCall')   AND LOWER(application__api__path) = LOWER('/api/pub/serviceapptedge/v1/appointments/reschedule') , 1, 0)) AS rescheduled_service_appointments,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) IN ('Reset-Equipment-Internet') , 1, 0)) AS ed_reset_equipment_internet,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) IN ('Reset-Equipment-TV') , 1, 0)) AS ed_reset_equipment_tv,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) IN ('Reset-Equipment-Voice') , 1, 0)) AS ed_reset_equipment_voice,
        SUM(IF( FALSE, 1, 0)) AS internet_router_reset_failures,
        SUM(IF( FALSE, 1, 0)) AS voice_router_reset_failures,
        SUM(IF( FALSE, 1, 0)) AS internet_router_reset_successes,
        SUM(IF( FALSE, 1, 0)) AS voice_router_reset_successes,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('searched')   AND state__search__text IS NOT NULL , 1, 0)) AS search_action,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(operation__operation_type) = LOWER('searchResultSelected') , 1, 0)) AS search_results_clicked,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet'), 1, 0)) AS site_unique,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('loginStop')   AND LOWER(operation__success) = LOWER('True') , 1, 0)) AS site_unique_auth,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__app_section) = LOWER('support') , 1, 0)) AS support_section_page_views,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('pageView')   AND LOWER(state__view__current_page__page_name) = LOWER('home-unauth') , 1, 0)) AS unauth_homepage_page_views,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__page_name) = LOWER('home-authenticated')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('Upgrade-Overview-Banner') , 1, 0)) AS upgrade_links_overview,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('equipment.internet.upgrade-service') , 1, 0)) AS upgrade_service_internet,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('equipment.tv.upgrade-service') , 1, 0)) AS upgrade_service_tv,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('equipment.voice.upgrade-your-service') , 1, 0)) AS upgrade_service_voice,
        SUM(IF( FALSE, 1, 0)) AS username_recovery_attempts,
        SUM(IF( FALSE, 1, 0)) AS username_recovery_successes,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('utilityNav-email') , 1, 0)) AS utilitynav_email,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('utilityNav-support') , 1, 0)) AS utilitynav_support,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('utilityNav-voice') , 1, 0)) AS utilitynav_voice,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('equipment.tv.expand-device') , 1, 0)) AS view_equipment_details_tv,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('equipment.voice.expand-device') , 1, 0)) AS view_equipment_details_voice,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND message__name = 'selectAction'    AND state__view__current_page__elements__standardized_name IN( 'downloadStatement', 'pay-bill.billing-statement-download') , 1, 0)) AS view_online_statement,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('equipment.tv.view-troubleshooting-video')   AND LOWER(state__view__current_page__page_name) = LOWER('my-tv-services') , 1, 0)) AS view_support_video_tv_view_troubleshooting_video,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('equipment.tv.view-troubleshooting-video')   AND LOWER(state__view__current_page__page_name) = LOWER('my-internet-services') , 1, 0)) AS view_support_video_voice_view_more_videos,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('equipment.voice.view-troubleshooting-video')   AND LOWER(state__view__current_page__page_name) = LOWER('my-voice-services') , 1, 0)) AS view_support_video_voice_view_troubleshooting_video,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__elements__standardized_name) IN (LOWER('equipment.internet.check-email'),LOWER('utilityNav-email')) , 1, 0)) AS webmail_views,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__page_section__name) = LOWER('equipment')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('internet') , 1, 0)) AS yourservicesequip_internet,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__page_section__name) = LOWER('equipment')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('mobile') , 1, 0)) AS yourservicesequip_mobile,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__page_section__name) = LOWER('equipment')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('tv') , 1, 0)) AS yourservicesequip_tv,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('selectAction')   AND LOWER(state__view__current_page__page_section__name) = LOWER('equipment')   AND LOWER(state__view__current_page__elements__standardized_name) = LOWER('voice') , 1, 0)) AS yourservicesequip_voice,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) IN (LOWER('Wait-15-Error-Modal-Internet'),LOWER('Wait-15-Error-Modal-TV'),LOWER('Wait-15-Error-Modal-Voice')) , 1, 0)) AS equipment_resets_too_many_resets_modal_all,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) = LOWER('Wait-15-Error-Modal-Internet') , 1, 0)) AS equipment_resets_too_many_resets_modal_internet,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) = LOWER('Wait-15-Error-Modal-TV') , 1, 0)) AS equipment_resets_too_many_resets_modal_tv,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(message__name) = LOWER('modalView')   AND LOWER(state__view__modal__name) = LOWER('Wait-15-Error-Modal-Voice') , 1, 0)) AS equipment_resets_too_many_resets_modal_voice,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(visit__device__device_type) RLIKE LOWER('and.*') , 1, 0)) AS os_android,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(visit__device__device_type) RLIKE LOWER('ip.*') , 1, 0)) AS os_ios,
        SUM(IF( LOWER(visit__application_details__application_name) = LOWER('SpecNet')  AND LOWER(visit__device__device_type) NOT RLIKE LOWER('ip.*')   AND LOWER(visit__device__device_type) NOT RLIKE LOWER('and.*') , 1, 0)) AS os_other,
        'asp' AS platform,
        'resi' AS domain,
        
        epoch_converter(cast(received__timestamp as bigint),'America/Denver') as date_denver
    FROM asp_v_venona_staging_portals_specnet
         
    WHERE (partition_date_hour_utc >= '${env:START_DATE_TZ}'
       AND partition_date_hour_utc <  '${env:END_DATE_TZ}')
    GROUP BY
        epoch_converter(cast(received__timestamp as bigint),'America/Denver'),
        
        COALESCE (visit__account__details__mso,'Unknown')
    ;
INSERT OVERWRITE TABLE prod.asp_venona_counts_daily
PARTITION(unit,platform,domain,company,date_denver,source_table)

    SELECT  value,
            metric,
            
            'instances',
            'asp',
            'resi',
            company,
            date_denver,
            'asp_v_venona_staging_portals_specnet'
    FROM (SELECT  company,
                  date_denver,
                  
                  MAP(

                      'ask_spectrum_from_billing_post|Ask Spectrum From Billing Post|Spectrum.net||', ask_spectrum_from_billing_post,
                      'ask_spectrum_from_my_internet_services|Ask Spectrum From My Internet Services|Spectrum.net||', ask_spectrum_from_my_internet_services,
                      'ask_spectrum_from_my_tv_services|Ask Spectrum From My Tv Services|Spectrum.net||', ask_spectrum_from_my_tv_services,
                      'ask_spectrum_from_my_voice_services|Ask Spectrum From My Voice Services|Spectrum.net||', ask_spectrum_from_my_voice_services,
                      'auth_homepage_page_views|Authenticated Homepage Page Views|Spectrum.net||', auth_homepage_page_views,
                      'set_up_auto_payment_failures|Auto Pay Enrollment Failures|Spectrum.net||', set_up_auto_payment_failures,
                      'set_up_auto_payment_successes|Auto Pay Enrollment Successes|Spectrum.net||', set_up_auto_payment_successes,
                      'autopay_confirmation_post|Autopay Confirmation Post|Spectrum.net||', autopay_confirmation_post,
                      'autopay_is_enabled|Autopay Is Enabled|Spectrum.net||', autopay_is_enabled,
                      'autopay_is_not_enabled|Autopay Is Not Enabled|Spectrum.net||', autopay_is_not_enabled,
                      'autopay_step1_post|Autopay Step1 Post|Spectrum.net||', autopay_step1_post,
                      'bill_pay_clicks_from_bill_pay_card_on_hp|Bill Pay Clicks From Bill Pay Card On Hp|Spectrum.net||', bill_pay_clicks_from_bill_pay_card_on_hp,
                      'bill_pay_clicks_from_local_nav|Bill Pay Clicks From Local Nav|Spectrum.net||', bill_pay_clicks_from_local_nav,
                      'bill_flow_ap_step1|Bill Pay Flow - Auto Pay Step 1|Spectrum.net||', bill_flow_ap_step1,
                      'bill_flow_ap_step2_confirm|Bill Pay Flow - Auto Pay Step 2 / Confirm|Spectrum.net||', bill_flow_ap_step2_confirm,
                      'bill_flow_otp_step1|Bill Pay Flow - One Time Payment Step 1|Spectrum.net||', bill_flow_otp_step1,
                      'bill_flow_otp_step2|Bill Pay Flow - One Time Payment Step 2|Spectrum.net||', bill_flow_otp_step2,
                      'bill_flow_otp_step3|Bill Pay Flow - One Time Payment Step 3|Spectrum.net||', bill_flow_otp_step3,
                      'bill_flow_otp_step4|Bill Pay Flow - One Time Payment Step 4|Spectrum.net||', bill_flow_otp_step4,
                      'bill_flow_otp_step5_confirm|Bill Pay Flow - One Time Payment Step 5 / Confirm|Spectrum.net||', bill_flow_otp_step5_confirm,
                      'bill_status_past_due_no|Bill Status Past Due No|Spectrum.net||', bill_status_past_due_no,
                      'bill_status_past_due_yes|Bill Status Past Due Yes|Spectrum.net||', bill_status_past_due_yes,
                      'cancelled_service_appointments|Cancelled Service Appointments|Spectrum.net||', cancelled_service_appointments,
                      'combined_payment_successes|Combined One Time Payment and Auto Pay with One Time Payment Successes|Spectrum.net||', combined_payment_successes,
                      'contact_us_page_views|Contact Us Page Views|Spectrum.net||', contact_us_page_views,
                      'create_username_referred_from_msa|Create Username Referral From MySpectrum App|Spectrum.net||', create_username_referred_from_msa,
                      'site_unique_mobile|Device Count Mobile|Spectrum.net||', site_unique_mobile,
                      'site_unique_pc|Device Count PC|Spectrum.net||', site_unique_pc,
                      'ed_equip_internet_troubleshoot_reset_equip_cancel|Equip Internet Troubleshoot Reset Equip Cancel|Spectrum.net||', ed_equip_internet_troubleshoot_reset_equip_cancel,
                      'ed_equip_internet_troubleshoot_reset_equip_reset_failure_modal_continue|Equip Internet Troubleshoot Reset Equip Reset Failure Modal Continue|Spectrum.net||', ed_equip_internet_troubleshoot_reset_equip_reset_failure_modal_continue,
                      'ed_equip_internet_troubleshoot_reset_equip_start|Equip Internet Troubleshoot Reset Equip Start|Spectrum.net||', ed_equip_internet_troubleshoot_reset_equip_start,
                      'ed_equip_internet_troubleshoot_reset_equip_success_modal_continue|Equip Internet Troubleshoot Reset Equip Success Modal Continue|Spectrum.net||', ed_equip_internet_troubleshoot_reset_equip_success_modal_continue,
                      'ed_equip_internet_troubleshoot_reset_equip_success_modal_issue_resolved|Equip Internet Troubleshoot Reset Equip Success Modal Issue Resolved|Spectrum.net||', ed_equip_internet_troubleshoot_reset_equip_success_modal_issue_resolved,
                      'ed_equip_tv_troubleshoot_reset_equip_cancel|Equip Tv Troubleshoot Reset Equip Cancel|Spectrum.net||', ed_equip_tv_troubleshoot_reset_equip_cancel,
                      'ed_equip_tv_troubleshoot_reset_equip_reset_failure_modal_continue|Equip Tv Troubleshoot Reset Equip Reset Failure Modal Continue|Spectrum.net||', ed_equip_tv_troubleshoot_reset_equip_reset_failure_modal_continue,
                      'ed_equip_tv_troubleshoot_reset_equip_start|Equip Tv Troubleshoot Reset Equip Start|Spectrum.net||', ed_equip_tv_troubleshoot_reset_equip_start,
                      'ed_equip_tv_troubleshoot_reset_equip_success_modal_continue|Equip Tv Troubleshoot Reset Equip Success Modal Continue|Spectrum.net||', ed_equip_tv_troubleshoot_reset_equip_success_modal_continue,
                      'ed_equip_tv_troubleshoot_reset_equip_success_modal_issue_resolved|Equip Tv Troubleshoot Reset Equip Success Modal Issue Resolved|Spectrum.net||', ed_equip_tv_troubleshoot_reset_equip_success_modal_issue_resolved,
                      'ed_equip_voice_troubleshoot_reset_equip_cancel|Equip Voice Troubleshoot Reset Equip Cancel|Spectrum.net||', ed_equip_voice_troubleshoot_reset_equip_cancel,
                      'ed_equip_voice_troubleshoot_reset_equip_reset_failure_modal_continue|Equip Voice Troubleshoot Reset Equip Reset Failure Modal Continue|Spectrum.net||', ed_equip_voice_troubleshoot_reset_equip_reset_failure_modal_continue,
                      'ed_equip_voice_troubleshoot_reset_equip_start|Equip Voice Troubleshoot Reset Equip Start|Spectrum.net||', ed_equip_voice_troubleshoot_reset_equip_start,
                      'ed_equip_voice_troubleshoot_reset_equip_success_modal_continue|Equip Voice Troubleshoot Reset Equip Success Modal Continue|Spectrum.net||', ed_equip_voice_troubleshoot_reset_equip_success_modal_continue,
                      'ed_equip_voice_troubleshoot_reset_equip_success_modal_issue_resolved|Equip Voice Troubleshoot Reset Equip Success Modal Issue Resolved|Spectrum.net||', ed_equip_voice_troubleshoot_reset_equip_success_modal_issue_resolved,
                      'equipment_page_views|Equipment Flow Page Views|Spectrum.net||', equipment_page_views,
                      'all_equipment_reset_flow_failures|Equipment Reset Flow Failures All|Spectrum.net||', all_equipment_reset_flow_failures,
                      'internet_equipment_reset_flow_failures|Equipment Reset Flow Failures Internet|Spectrum.net||', internet_equipment_reset_flow_failures,
                      'tv_equipment_reset_flow_failures|Equipment Reset Flow Failures TV|Spectrum.net||', tv_equipment_reset_flow_failures,
                      'voice_equipment_reset_flow_failures|Equipment Reset Flow Failures Voice|Spectrum.net||', voice_equipment_reset_flow_failures,
                      'all_equipment_reset_flow_starts|Equipment Reset Flow Starts All|Spectrum.net||', all_equipment_reset_flow_starts,
                      'internet_equipment_reset_flow_starts|Equipment Reset Flow Starts Internet|Spectrum.net||', internet_equipment_reset_flow_starts,
                      'tv_equipment_reset_flow_starts|Equipment Reset Flow Starts TV|Spectrum.net||', tv_equipment_reset_flow_starts,
                      'voice_equipment_reset_flow_starts|Equipment Reset Flow Starts Voice|Spectrum.net||', voice_equipment_reset_flow_starts,
                      'all_equipment_reset_flow_successes|Equipment Reset Flow Successes All|Spectrum.net||', all_equipment_reset_flow_successes,
                      'internet_equipment_reset_flow_successes|Equipment Reset Flow Successes Internet|Spectrum.net||', internet_equipment_reset_flow_successes,
                      'tv_equipment_reset_flow_successes|Equipment Reset Flow Successes TV|Spectrum.net||', tv_equipment_reset_flow_successes,
                      'voice_equipment_reset_flow_successes|Equipment Reset Flow Successes Voice|Spectrum.net||', voice_equipment_reset_flow_successes,
                      'footer_manageaccount_account_summary|Footer - Account Summary|Spectrum.net||', footer_manageaccount_account_summary,
                      'footer_getsupport_acct_support|Footer - Acct Support|Spectrum.net||', footer_getsupport_acct_support,
                      'footer_manageaccount_billing|Footer - Billing|Spectrum.net||', footer_manageaccount_billing,
                      'footer_legal_ca_privacy_rights|Footer - CA Privacy Rights|Spectrum.net||', footer_legal_ca_privacy_rights,
                      'footer_contactus_contact_us|Footer - Contact Us|Spectrum.net||', footer_contactus_contact_us,
                      'footer_disability_assistance|Footer - Disability Assistance|Spectrum.net||', footer_disability_assistance,
                      'footer_social_facebook|Footer - Facebook|Spectrum.net||', footer_social_facebook,
                      'footer_contactus_find_spectrum_store|Footer - Find a Spectrum Store|Spectrum.net||', footer_contactus_find_spectrum_store,
                      'footer_contactus_give_website_feedback|Footer - Give Website Feedback |Spectrum.net||', footer_contactus_give_website_feedback,
                      'footer_legal_go_to_assist|Footer - Go to Assist|Spectrum.net||', footer_legal_go_to_assist,
                      'footer_watchtv_guide|Footer - Guide|Spectrum.net||', footer_watchtv_guide,
                      'footer_social_instagram|Footer - Instagram|Spectrum.net||', footer_social_instagram,
                      'footer_getsupport_internet|Footer - Internet|Spectrum.net||', footer_getsupport_internet,
                      'footer_manageaccount_internet|Footer - Internet|Spectrum.net||', footer_manageaccount_internet,
                      'footer_watchtv_live_tv|Footer - Live TV|Spectrum.net||', footer_watchtv_live_tv,
                      'footer_manageaccount_mobile|Footer - Mobile|Spectrum.net||', footer_manageaccount_mobile,
                      'footer_watchtv_my_library|Footer - My Library|Spectrum.net||', footer_watchtv_my_library,
                      'footer_watchtv_on_demand|Footer - On Demand|Spectrum.net||', footer_watchtv_on_demand,
                      'footer_legal_policies|Footer - Policies|Spectrum.net||', footer_legal_policies,
                      'footer_legal_privacy_rights|Footer - Privacy Rights|Spectrum.net||', footer_legal_privacy_rights,
                      'footer_manageaccount_settings|Footer - Settings|Spectrum.net||', footer_manageaccount_settings,
                      'footer_getsupport_support_home|Footer - Support Home|Spectrum.net||', footer_getsupport_support_home,
                      'footer_getsupport_tv|Footer - TV|Spectrum.net||', footer_getsupport_tv,
                      'footer_manageaccount_tv|Footer - TV|Spectrum.net||', footer_manageaccount_tv,
                      'footer_watchtv_dvr|Footer - TV DVR|Spectrum.net||', footer_watchtv_dvr,
                      'footer_social_twitter|Footer - Twitter|Spectrum.net||', footer_social_twitter,
                      'footer_getsupport_voice|Footer - Voice|Spectrum.net||', footer_getsupport_voice,
                      'footer_manageaccount_voice|Footer - Voice|Spectrum.net||', footer_manageaccount_voice,
                      'footer_contactus_weather_outage|Footer - Weather Outage|Spectrum.net||', footer_contactus_weather_outage,
                      'footer_social_youtube|Footer - Youtube|Spectrum.net||', footer_social_youtube,
                      'forgot_password_referred_from_msa|Forgot Password Referral From MySpectrum App|Spectrum.net||', forgot_password_referred_from_msa,
                      'forgot_username_referred_from_msa|Forgot Username Referral From MySpectrum App|Spectrum.net||', forgot_username_referred_from_msa,
                      'from_homepage_banner_internet|From Homepage Banner Internet|Spectrum.net||', from_homepage_banner_internet,
                      'from_homepage_banner_tv|From Homepage Banner Tv|Spectrum.net||', from_homepage_banner_tv,
                      'from_homepage_banner_voice|From Homepage Banner Voice|Spectrum.net||', from_homepage_banner_voice,
                      'from_support_internet|From Support Internet|Spectrum.net||', from_support_internet,
                      'from_support_tv|From Support Tv|Spectrum.net||', from_support_tv,
                      'from_support_voice|From Support Voice|Spectrum.net||', from_support_voice,
                      'hamburger_closesidenav|Hamburger - closeSideNav|Spectrum.net||', hamburger_closesidenav,
                      'hamburger_create_username|Hamburger - Create Username|Spectrum.net||', hamburger_create_username,
                      'hamburger_email|Hamburger - Email|Spectrum.net||', hamburger_email,
                      'hamburger_get_support|Hamburger - Get Support|Spectrum.net||', hamburger_get_support,
                      'hamburger_manage_account|Hamburger - Manage Account|Spectrum.net||', hamburger_manage_account,
                      'hamburger_signin|Hamburger - Sign In|Spectrum.net||', hamburger_signin,
                      'hamburger_signout|Hamburger - Signout|Spectrum.net||', hamburger_signout,
                      'hamburger_voice|Hamburger - Voice|Spectrum.net||', hamburger_voice,
                      'hamburger_watch_tv|Hamburger - Watch TV|Spectrum.net||', hamburger_watch_tv,
                      'iva_opens|IVA Opens|Spectrum.net||', iva_opens,
                      'localnav_acct_summary|LocalNav - Account Summary|Spectrum.net||', localnav_acct_summary,
                      'localnav_billing|LocalNav - Billing|Spectrum.net||', localnav_billing,
                      'localnav_internet|LocalNav - Internet|Spectrum.net||', localnav_internet,
                      'localnav_settings|LocalNav - Settings|Spectrum.net||', localnav_settings,
                      'localnav_tv|LocalNav - TV|Spectrum.net||', localnav_tv,
                      'localnav_voice|LocalNav - Voice|Spectrum.net||', localnav_voice,
                      'login_attempts|Login Attempts|Spectrum.net||', login_attempts,
                      'manual_reset_failures|Manual Reset Failures|Spectrum.net||', manual_reset_failures,
                      'manual_reset_starts|Manual Reset Starts|Spectrum.net||', manual_reset_starts,
                      'manual_reset_success|Manual Reset Success|Spectrum.net||', manual_reset_success,
                      'manual_troubleshoot_page_views|Manual Troubleshooting Page Views|Spectrum.net||', manual_troubleshoot_page_views,
                      'internet_modem_reset_failures|Modem Reset Failures Internet|Spectrum.net||', internet_modem_reset_failures,
                      'voice_modem_reset_failures|Modem Reset Failures Voice|Spectrum.net||', voice_modem_reset_failures,
                      'internet_modem_reset_successes|Modem Reset Successes Internet|Spectrum.net||', internet_modem_reset_successes,
                      'voice_modem_reset_successes|Modem Reset Successes Voice|Spectrum.net||', voice_modem_reset_successes,
                      'internet_modem_router_reset_starts|Modem Router Reset Starts Internet|Spectrum.net||', internet_modem_router_reset_starts,
                      'voice_modem_router_reset_starts|Modem Router Reset Starts Voice|Spectrum.net||', voice_modem_router_reset_starts,
                      'ed_my_internet_services|My Internet Services|Spectrum.net||', ed_my_internet_services,
                      'ed_my_internet_services_contact_us|My Internet Services Contact Us|Spectrum.net||', ed_my_internet_services_contact_us,
                      'ed_my_internet_services_manually_reset_equipment|My Internet Services Manually Reset Equipment|Spectrum.net||', ed_my_internet_services_manually_reset_equipment,
                      'ed_my_tv_services|My Tv Services|Spectrum.net||', ed_my_tv_services,
                      'ed_my_tv_services_contact_us|My Tv Services Contact Us|Spectrum.net||', ed_my_tv_services_contact_us,
                      'ed_my_tv_services_manually_reset_equipment|My Tv Services Manually Reset Equipment|Spectrum.net||', ed_my_tv_services_manually_reset_equipment,
                      'ed_my_voice_services|My Voice Services|Spectrum.net||', ed_my_voice_services,
                      'ed_my_voice_services_contact_us|My Voice Services Contact Us|Spectrum.net||', ed_my_voice_services_contact_us,
                      'ed_my_voice_services_manually_reset_equipment|My Voice Services Manually Reset Equipment|Spectrum.net||', ed_my_voice_services_manually_reset_equipment,
                      'new_ids_created_attempts|New IDs Created Attempts|Spectrum.net||', new_ids_created_attempts,
                      'new_ids_created_successes|New IDs Created Successes|Spectrum.net||', new_ids_created_successes,
                      'one_time_payment_failures|One Time Payment Failures|Spectrum.net||', one_time_payment_failures,
                      'one_time_payment_starts|One Time Payment Starts|Spectrum.net||', one_time_payment_starts,
                      'one_time_payment_successes|One Time Payment Successes|Spectrum.net||', one_time_payment_successes,
                      'otp_with_autopay_failures|One Time Payment with Auto Pay Enrollment Failures|Spectrum.net||', otp_with_autopay_failures,
                      'otp_with_autopay_successes|One Time Payment with Auto Pay Enrollment Successes|Spectrum.net||', otp_with_autopay_successes,
                      'paperless_billing_is_enabled|Paperless Billing is Enabled|Spectrum.net||', paperless_billing_is_enabled,
                      'paperless_billing_is_not_enabled|Paperless Billing Is Not Enabled|Spectrum.net||', paperless_billing_is_not_enabled,
                      'password_reset_attempts|Password Reset Attempts|Spectrum.net||', password_reset_attempts,
                      'password_reset_successes|Password Reset Successes|Spectrum.net||', password_reset_successes,
                      'ed_progress_bar_modal_internet|Progress Bar Modal Internet|Spectrum.net||', ed_progress_bar_modal_internet,
                      'ed_progress_bar_modal_tv|Progress Bar Modal Tv|Spectrum.net||', ed_progress_bar_modal_tv,
                      'ed_progress_bar_modal_voice|Progress Bar Modal Voice|Spectrum.net||', ed_progress_bar_modal_voice,
                      'rescheduled_service_appointments|Rescheduled Service Appointments|Spectrum.net||', rescheduled_service_appointments,
                      'ed_reset_equipment_internet|Reset Equipment Internet|Spectrum.net||', ed_reset_equipment_internet,
                      'ed_reset_equipment_tv|Reset Equipment TV|Spectrum.net||', ed_reset_equipment_tv,
                      'ed_reset_equipment_voice|Reset Equipment Voice|Spectrum.net||', ed_reset_equipment_voice,
                      'internet_router_reset_failures|Router Reset Failures Internet|Spectrum.net||', internet_router_reset_failures,
                      'voice_router_reset_failures|Router Reset Failures Voice|Spectrum.net||', voice_router_reset_failures,
                      'internet_router_reset_successes|Router Reset Successes Internet|Spectrum.net||', internet_router_reset_successes,
                      'voice_router_reset_successes|Router Reset Successes Voice|Spectrum.net||', voice_router_reset_successes,
                      'search_action|Search Action|Spectrum.net||', search_action,
                      'search_results_clicked|Search Results Clicked|Spectrum.net||', search_results_clicked,
                      'site_unique|Site Unique Values|Spectrum.net||', site_unique,
                      'site_unique_auth|Site Unique Values Authenticated|Spectrum.net||', site_unique_auth,
                      'support_section_page_views|Support Section Page Views|Spectrum.net||', support_section_page_views,
                      'unauth_homepage_page_views|Unauthenticated Homepage Page Views|Spectrum.net||', unauth_homepage_page_views,
                      'upgrade_links_overview|Upgrade Links Overview|Spectrum.net||', upgrade_links_overview,
                      'upgrade_service_internet|Upgrade Service Internet|Spectrum.net||', upgrade_service_internet,
                      'upgrade_service_tv|Upgrade Service Tv|Spectrum.net||', upgrade_service_tv,
                      'upgrade_service_voice|Upgrade Service Voice|Spectrum.net||', upgrade_service_voice,
                      'username_recovery_attempts|Username Recovery Attempts|Spectrum.net||', username_recovery_attempts,
                      'username_recovery_successes|Username Recovery Successes|Spectrum.net||', username_recovery_successes,
                      'utilitynav_email|Utility Navigation - Email|Spectrum.net||', utilitynav_email,
                      'utilitynav_support|Utility Navigation - Support|Spectrum.net||', utilitynav_support,
                      'utilitynav_voice|Utility Navigation - Voice|Spectrum.net||', utilitynav_voice,
                      'view_equipment_details_tv|View Equipment Details Tv|Spectrum.net||', view_equipment_details_tv,
                      'view_equipment_details_voice|View Equipment Details Voice|Spectrum.net||', view_equipment_details_voice,
                      'view_online_statement|View Online Statement|Spectrum.net||', view_online_statement,
                      'view_support_video_tv_view_troubleshooting_video|View Support Video Tv View Troubleshooting Video|Spectrum.net||', view_support_video_tv_view_troubleshooting_video,
                      'view_support_video_voice_view_more_videos|View Support Video Voice View More Videos|Spectrum.net||', view_support_video_voice_view_more_videos,
                      'view_support_video_voice_view_troubleshooting_video|View Support Video Voice View Troubleshooting Video|Spectrum.net||', view_support_video_voice_view_troubleshooting_video,
                      'webmail_views|Webmail Views|Spectrum.net||', webmail_views,
                      'yourservicesequip_internet|Your Services Equipment - Internet|Spectrum.net||', yourservicesequip_internet,
                      'yourservicesequip_mobile|Your Services Equipment - Mobile|Spectrum.net||', yourservicesequip_mobile,
                      'yourservicesequip_tv|Your Services Equipment - TV|Spectrum.net||', yourservicesequip_tv,
                      'yourservicesequip_voice|Your Services Equipment - Voice|Spectrum.net||', yourservicesequip_voice,
                      'equipment_resets_too_many_resets_modal_all|Equipment Resets Too Many Resets Modal|Spectrum.net||', equipment_resets_too_many_resets_modal_all,
                      'equipment_resets_too_many_resets_modal_internet|Equipment Resets Too Many Resets Modal Internet|Spectrum.net||', equipment_resets_too_many_resets_modal_internet,
                      'equipment_resets_too_many_resets_modal_tv|Equipment Resets Too Many Resets Modal TV|Spectrum.net||', equipment_resets_too_many_resets_modal_tv,
                      'equipment_resets_too_many_resets_modal_voice|Equipment Resets Too Many Resets Modal Voice|Spectrum.net||', equipment_resets_too_many_resets_modal_voice,
                      'os_android|Operating System - Android|Spectrum.net||', os_android,
                      'os_ios|Operating System - iOS|Spectrum.net||', os_ios,
                      'os_other|Operating System - Not Android or iOS|Spectrum.net||', os_other
                  ) as map_column
          FROM ${env:TMP_db}.asp_venona_counts_daily_counts_instances_columns
        ) as derived_table
    LATERAL VIEW EXPLODE (map_column) exploded_table AS metric, value
;
