#!/usr/bin/env groovy
@Library('jenkins-util') _    // don't miss the '_' at the end of the line, this is the magical library that does the, uh, 'magic'
PIDeliveryPipeline {
    azkabanProjectName = "asp_extract_adobe_apps_multidimension" // required
    azkabanEnv = 'dev' // optional, default to dev
    azkabanProjectDesc = "Comprehensive code base for preparing counts from the Adobe Consumer data source that include one or more dimensions, such as page name, OS, app store, and so forth" // required
    azkabanProjectOwner = 'eeasterly' // required, put your AD login here
    azkabanPlatform = 'ASP'  // required
    azkabanEscalation = 'Andrew Ngeow' // required, one of ['Andrew Ngeow', 'Yong Liu', 'Ty Prinkki', 'Majorie Truitt', 'Micheal Baldino', 'Nate Vogel']
    azkabanSLA = 'Critical - Immediate Response' // required, one of ['Optional - Next Day', 'Important - Within 12 hrs', 'Critical - Immediate Response']
    azkabanFlowRun=[] // not implemented, could have loop here too
    azkabanProdFlowSchedule=[]
    gitDir='extract/adobe/apps/multidimension'  // the sub dir where your project dir is
}
