#!/usr/bin/env groovy
@Library('jenkins-util') _    // don't miss the '_' at the end of the line, this is the magical library that does the, uh, 'magic'
PIDeliveryPipeline {
    azkabanProjectName = "cs_call_in_rate" // required, Azkaban project name. Jenkins build will prepend "${platform}_" before in prod/dev
                                     // and append "_${branch}" after in dev Azkaban.
    azkabanEnv = 'prod'              // optional, default to dev
    azkabanProjectDesc = "This project contains the ETL code to ingest BI/Call Care Atom data" // required
    azkabanProjectOwner = 'Nate Blessing'    // required, put your AD login here
    azkabanPlatform = 'ASP'        // required, one of ['ASP', 'Authentication', 'Core', 'DAI', 'DynExp', 'HSD', 'Mobile',
                                    //          'MVNO', 'ODN', 'Platform Ops', 'SGR', 'SpecGuide', 'Venona', 'VOD', 'Voice', 'WiFi']
    azkabanEscalation = 'Marjorie Truitt'  // required, one of ['Andrew Ngeow', 'Yong Liu', 'Ty Prinkki', 'Marjorie Truitt', 'Michael Baldino', 'Nate Vogel']
    azkabanSLA = 'Important - Within 12 hrs' // required, one of ['Optional - Next Day', 'Important - Within 12 hrs', 'Critical - Immediate Response']
    azkabanFlowRun = [] // optional, leave out or empty([]) if you do not want to kick off specified flow as a test
    azkabanProdFlowSchedule = [flowName:'daily_call_in_rate', cronExpression: '0 10 ? * *']
    gitDir = 'call_in_rate'  // required, the sub dir where your project dir is
}
