#!/usr/bin/env groovy
@Library('jenkins-util') _    // don't miss the '_' at the end of the line
PIDeliveryPipeline {
    azkabanProjectName = "asp_extract_migration" // required
    azkabanEnv = 'prod' // optional, default to dev
    azkabanProjectDesc = "Migration Metrics for SpecNet and SMB" // required
    azkabanProjectOwner = 'azheng' // required, put your AD login here
    azkabanPlatform = 'ASP'  // required
    azkabanEscalation = 'Marjorie Truitt' // required, one of ['Andrew Ngeow', 'Yong Liu', 'Ty Prinkki', 'Marjorie Truitt', 'Micheal Baldino', 'Nate Vogel']
    azkabanSLA = 'Optional - Next Day' // required, one of ['Optional - Next Day', 'Important - Within 12 hrs', 'Critical - Immediate Response']
    azkabanFlowRun=[] // not implemented, could have loop here too
    azkabanProdFlowSchedule=[flowName:'asp_extract_migration_end', cronExpression:'0 47 20 ? * *']
    gitDir='extract/consolidation/migration'  // the sub dir where your project dir is
}
