#!/usr/bin/env groovy
@Library('jenkins-util') _    // don't miss the '_' at the end of the line
PIDeliveryPipeline {
    azkabanProjectName = "asp_search_support_tab_refresh_check" // required
    azkabanEnv = 'prod' // optional, default to dev
    azkabanProjectDesc = "refresh amd check refresh of search support performance" // required
    azkabanProjectOwner = 'lbollineni' // required, put your AD login here
    azkabanPlatform = 'ASP'  // required
    azkabanEscalation = 'Marjorie Truitt' // required, one of ['Andrew Ngeow', 'Yong Liu', 'Ty Prinkki', 'Marjorie Truitt', 'Micheal Baldino', 'Nate Vogel']
    azkabanSLA = 'Optional - Next Day' // required, one of ['Optional - Next Day', 'Important - Within 12 hrs', 'Critical - Immediate Response']
    azkabanFlowRun=[] // not implemented, could have loop here too
    azkabanProdFlowSchedule=[]
    gitDir='extract/cs_portals_events/support_content_performance_tab'  // the sub dir where your project dir is
}
