.m_portals_m2dot0_set_agg_variables: &m_portals_m2dot0_set_agg_variables
  JOB_NAME: "m-portals-m2dot0-set-agg"
  MONTHLY_PORTALS_M2DOT0_SET_AGG_DIR: "parameterized/monthly-portals-m2dot0-set-agg"
  ARTIFACTS_DIR: "parameterized/monthly-portals-m2dot0-set-agg/artifacts"
  TERRAFORM_DIR: "parameterized/monthly-portals-m2dot0-set-agg/terraform"
  SCRIPTS_DIR: "parameterized/monthly-portals-m2dot0-set-agg/scripts"
  S3_ARTIFACTS_DIR: "parameterized/monthly-portals-m2dot0-set-agg"

m_portals_m2dot0_set_agg_build:
  extends: .build
  variables:
    DDL_DIR: "$MONTHLY_PORTALS_M2DOT0_SET_AGG_DIR/ddl"
    HQL_DIR: "$MONTHLY_PORTALS_M2DOT0_SET_AGG_DIR/hql"
    <<: *m_portals_m2dot0_set_agg_variables

#STG
m_portals_m2dot0_set_agg_plan_stg:
  extends: .plan_stg
  variables:
    <<: *m_portals_m2dot0_set_agg_variables
  dependencies:
    - m_portals_m2dot0_set_agg_build

m_portals_m2dot0_set_agg_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *m_portals_m2dot0_set_agg_variables
  dependencies:
    - m_portals_m2dot0_set_agg_build
    - m_portals_m2dot0_set_agg_plan_stg

m_portals_m2dot0_set_agg_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *m_portals_m2dot0_set_agg_variables
  dependencies:
    - m_portals_m2dot0_set_agg_build


#PROD
m_portals_m2dot0_set_agg_plan_prod:
  extends: .plan_prod
  variables:
    <<: *m_portals_m2dot0_set_agg_variables
  dependencies:
    - m_portals_m2dot0_set_agg_build

m_portals_m2dot0_set_agg_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *m_portals_m2dot0_set_agg_variables
  dependencies:
    - m_portals_m2dot0_set_agg_build
    - m_portals_m2dot0_set_agg_plan_prod

m_portals_m2dot0_set_agg_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *m_portals_m2dot0_set_agg_variables
  dependencies:
    - m_portals_m2dot0_set_agg_build
