#  Azkaban job
type=command
dependencies=03_portals_privacysite_set_agg_reprocess_daily_instances,03_portals_privacysite_set_agg_reprocess_daily_visits,03_portals_privacysite_set_agg_reprocess_daily_devices,03_portals_privacysite_set_agg_reprocess_daily_accounts
command=whoami

command.1=/bin/bash -c 'export execid=${azkaban.flow.execid}; echo $execid; export domain=${domain}; echo $domain; export project=${project}; echo $project;  echo $execid; export domain=${domain}; echo $domain; export project=${project}; echo $project; export ProcessUser="${azkaban.flow.submituser}"; echo $ProcessUser; hive -f ../../../src/portals_privacysite_set_agg_final.hql'
