# Azkaban job that creates required tables and views

type=command

command=whoami

command.1=/bin/bash -c 'export ReprocessDateTable_daily="${ReprocessDateTable_daily}"; echo $ReprocessDateTable_daily; export ReprocessDateTable_fiscal_monthly="${ReprocessDateTable_fiscal_monthly}"; echo $ReprocessDateTable_fiscal_monthly; export ReprocessDateTable_monthly="${ReprocessDateTable_monthly}"; echo $ReprocessDateTable_monthly; export ReprocessDateTable_weekly="${ReprocessDateTable_weekly}"; echo $ReprocessDateTable_weekly;  hive -f ../../src/init/create_tables_and_views.hql '
