.m_billing_agg_variables: &m_billing_agg_variables
  JOB_NAME: "parameterized-monthly-billing-agg"
  MONTHLY_BILLING_AGG_DIR: "parameterized/monthly-billing-agg"
  ARTIFACTS_DIR: "parameterized/monthly-billing-agg/artifacts"
  TERRAFORM_DIR: "parameterized/monthly-billing-agg/terraform"
  SCRIPTS_DIR: "parameterized/monthly-billing-agg/scripts"
  S3_ARTIFACTS_DIR: "parameterized/monthly-billing-agg"

m_billing_agg_build:
  extends: .build
  variables:
    DDL_DIR: "$MONTHLY_BILLING_AGG_DIR/ddl"
    HQL_DIR: "$MONTHLY_BILLING_AGG_DIR/hql"
    <<: *m_billing_agg_variables

#PROD
m_billing_agg_plan_prod:
  extends: .plan_prod
  variables:
    <<: *m_billing_agg_variables
  dependencies:
    - m_billing_agg_build

m_billing_agg_deploy_prod:
  extends: .deploy_prod
  variables:
    <<: *m_billing_agg_variables
  dependencies:
    - m_billing_agg_build
    - m_billing_agg_plan_prod

m_billing_agg_destroy_prod:
  extends: .destroy_prod
  variables:
    <<: *m_billing_agg_variables
  dependencies:
    - m_billing_agg_build

# STG
m_billing_agg_plan_stg:
  extends: .plan_stg
  variables:
    <<: *m_billing_agg_variables
  dependencies:
    - m_billing_agg_build

m_billing_agg_deploy_stg:
  extends: .deploy_stg
  variables:
    <<: *m_billing_agg_variables
  dependencies:
    - m_billing_agg_build
    - m_billing_agg_plan_stg

m_billing_agg_destroy_stg:
  extends: .destroy_stg
  variables:
    <<: *m_billing_agg_variables
  dependencies:
    - m_billing_agg_build
